### PR TITLE
add web_advanced_search_wildcard module

### PR DESCRIPTION
**Pull request by OSguard**
Allows =ilike operator to advanced search option.
Use % as a placeholder. 
Example: "Zip matches 1%" gives all zip starting with 1
Also allows insensitive exact search.
Example "Name matches john" will find "John" and "john" but not "Johnson".

PR moved from https://github.com/OCA/server-tools/pull/56

### CODE REVIEW

**Comment by guewen** [comment]
Great!
Could you just rename `web_advanced_search_wildcard/i18n/search_enhanced_operators.po` to `web_advanced_search_wildcard/i18n/search_enhanced_operators.pot`?

Once that done, :+1:

**Comment by OSguard** [comment]
i rename it to web_advanced_search_wildcard/i18n/web_advanced_search_wildcard.pot i guess this what you mean ;)

**Comment by guewen** [comment]
oh right, I did not noticed about the filename but just about the extension, thanks

:+1:

**Comment by pedrobaeza** [comment]
And you need also to rename the text inside the pot file that references old module name.

**Comment by OSguard** [comment]
renaming done

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
