### PR TITLE
[10.0][FIX] web_responsive: Menu Height on Init

### PR DESCRIPTION
**Pull request by lasley**
* Add a call to the window resize method during init to fix OCA#773

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Code & functional. Linter errors are not this PR's fault.

**Review by pedrobaeza — COMMENTED** [review]
Please change module version number

**Comment by lasley** [comment]
Bumped to 10.0.1.2.1

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please forward port it to 11.0

**Pull request merged**
