### PR TITLE
[13.0][IMP] web_widget_numeric_step: Add auto_select option

### PR DESCRIPTION
**Pull request by Tardo**
cc @tecnativa TT28955

numeric_step

### CODE REVIEW

**Comment by legalsylvain** [comment]
@quentinDupont : this PR could interest you. (if yes, should be backported in V12.)

**Comment by pedrobaeza** [comment]
Not sure if this should be an option or always act as this one. Do you see any drawback on not doing? How other widgets work with this auto-selection?

**Review by chienandalu — APPROVED** [review]
Nice

**Comment by quentinDupont** [comment]
I'm not seeing any drawback indeed. In my opinion, it should be even for every float field !
Bravo and thanks !

**Comment by Tardo** [comment]
Odoo's default behavior is to select content in tree mode but not in form mode. Currently this widget only "auto select" if the corresponding option is used.

Maybe leaving the option, making the widget "auto select" in tree mode and making a change in "web_responsive" to "auto select" the inputs, could be a good solution to keep the "Odoo behavior".

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
