### PR TITLE
[ADD] web_notify_channel_message

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module will send an instant notifications to all users of a channel when a new message has been posted.

cc @thiagomforgeflow @davidjforgeflow @JoanSForgeFlow

### CODE REVIEW

**Review by JoanSForgeFlow — APPROVED** [review]
Functional and code review. Works as expected! :+1:

**Review by DavidJForgeFlow — APPROVED** [review]

**Review by ThiagoMForgeFlow — APPROVED** [review]

**Comment by JoanSForgeFlow** [comment]
Hi @etobella, 

It is possible to merge this? :pray: 
Thank you

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Comment by lucaslc7s** [comment]
fork for 15.0?

**Pull request merged**
