### PR TITLE
[11.0][FIX]web_timeline: fix group orders

### PR DESCRIPTION
**Pull request by jcdrubay**
Super-seeds the git history mess I created in https://github.com/OCA/web/pull/1239/commits

### CODE REVIEW

**Review by tarteo — APPROVED** [review]
Thanks, please take a look at the lint error.

**Review by Tardo — APPROVED** [review]
LGTM :+1:, code review

**Comment by pedrobaeza** [comment]
Can you please forward-port it to v12?

**Comment by jcdrubay** [comment]
Yes, i can.

**Comment by pedrobaeza** [comment]
Please, thanks!

**Comment by denislour** [comment]
I ported it to v12. [PR!1314](https://github.com/OCA/web/pull/1314)

**Pull request closed without merging**
