### PR TITLE
[12.0][IMP] web_pwa_oca: Add support for require system

### PR DESCRIPTION
**Pull request by Tardo**
Refactor module to support require system.

Service workers need to load "Odoo Bootstrap" to be able to use "require". The problem is that "Odoo Bootstrap" does operations on the DOM (by using jQuery) and to avoid errors a minimal compatibility layer "jquery-sw-compat.js" has been created to allow using "require" in the service worker.

Moved Service Worker (js) code from the xml to python.

cc @tecnativa

### CODE REVIEW

**Comment by Tardo** [comment]
PR Updated

**Review by pedrobaeza — APPROVED** [review]
Please squash everything together

**Comment by pedrobaeza** [comment]
And please put explanation in the commit message (not the PR comment).

**Comment by Tardo** [comment]
changes done

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
