### PR TITLE
[ADD] web_save_discard_button module

### PR DESCRIPTION
**Pull request by synconics**

### CODE REVIEW

**Comment by synconics** [comment]
Is there any one to review this?

**Comment by legalsylvain** [comment]
Hi @synconics. I don't know why, but it looks like there are still some troubles in the commits. 
I fixed the problem here #2594
regards !

**Comment by synconics** [comment]
Hi @legalsylvain , Thanks for your updates, should I need to do anything now?

**Comment by StefanRijnhart** [comment]
Closing as this was merged in the superseding PR

**Pull request closed without merging**
