### PR TITLE
[12.0] apply OCA repo template and use GitHub actions

### PR DESCRIPTION
**Pull request by sbidoul**
Next try following https://github.com/OCA/web/pull/2171

### CODE REVIEW

**Comment by sbidoul** [comment]
So this is green (GitHub actions tests and runboat).

The difference is that we don't pin mpld3, which was probably the culprit. Now I don't know if the pin was important for that addon, but at least this unlocks the situation.

**Comment by sbidoul** [comment]
@OCA/web-maintainers feel free to merge if this looks ok for you.

**Review by legalsylvain — APPROVED** [review]
Thanks !

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
Thanks!!!
/ocabot merge patch

**Comment by ypapouin** [comment]
Thank you !

**Pull request merged**
