### PR TITLE
[ADD] Added module web_draw

### PR DESCRIPTION
**Pull request by tarteo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This seems very similar to https://github.com/OCA/web/tree/8.0/web_widget_digitized_signature. Can you check?

**Comment by tarteo** [comment]
With web_widget_digitized_signature you can select a signature (picture) from file system. With web_draw you can draw a signature (or any other drawing depends on context). So it's not similar.

**Comment by pedrobaeza** [comment]
Why do you close it?

**Comment by tarteo** [comment]
It's very similar.

**Comment by pedrobaeza** [comment]
OK, thanks. Maybe if this one has some benefits or features, you can merge them in the other widget. The other also is for v8, and this one is for v9. You can make a mix of them and propose it for v9.

**Pull request closed without merging**
