### PR TITLE
[17.0][MIG] web_chatter_position

### PR DESCRIPTION
**Pull request by Jp-alitec**
Migrated to V17.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @Jp-alitec 

Thanks for your contribution. 
* please respect the history, following OCA convention : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#how-to
* Please take a look on red pre-commit check, executing locally ``pre-commit run -a``

thanks

**Comment by duyquyen96** [comment]
Screenshot 2024-05-18 at 11 18 42 AM
@Jp-alitec It seems that forcing position sided when there is "webClientViewAttachmentViewHookXml" will be problematic.

**Comment by Jp-alitec** [comment]
Will open a new one with proper guidelines @legalsylvain .

**Pull request closed without merging**
