### PR TITLE
[12.0][FIX] web_widget_open_tab: Allow to open tab on dashboards or trees inside other forms

### PR DESCRIPTION
**Pull request by jarroyomorales**
Cherry-pick of https://github.com/OCA/web/pull/1471/commits/b824a1351e0b135c32a29d11e2572b312dc3cb29 with some fixes to allow opening a new tab on dashboards or trees inside other forms.

@etobella @simahawk @HviorForgeFlow @AdriaGForgeFlow

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM thanks for the :cherries:-pick

**Comment by jarroyomorales** [comment]
I had to apply a fix in this `if` statement https://github.com/OCA/web/pull/1639/files#diff-26c08b7f4531985df9d2a9ae79a2fb98R27 so I think it is not working fine on 11.0. Maybe after this we have to backport this minor change.

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
