### PR TITLE
[15.0][MIG] web_pwa_oca: Migration to v15 (Legacy mode)

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

ping @chienandalu @CarlosRoca13 

Supersed of https://github.com/OCA/web/pull/2151

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Remove WIP label

**Comment by francesco-ooops** [comment]
Hi @sergio-teruel runboat is displaying this error after a few seconds of inactivity: 

image

**Comment by pedrobaeza** [comment]
The error appears in all v15 runboat instances. I guess it's something of the way it's deployed. The PWA also doesn't work with HTTP. Change manually to https://.

**Review by francesco-ooops — APPROVED** [review]
functional ok then!

**Review by Tardo — APPROVED** [review]
Tested and looks OK to me

**Comment by pedrobaeza** [comment]
Broken now due to https://github.com/odoo/odoo/pull/107719

**Pull request merged**
