### PR TITLE
[12.0][IMP] web_widget_one2many_product_picker: Backport from 13.0

### PR DESCRIPTION
**Pull request by Tardo**
- All calls to onchange are now 'shadowed'. So, no more "loading overlay" is showed
- Now the elements are displayed in the correct order
- Now the record is blocked while the request is being processed on the server
- Avoid 'sale.order' onchanges for 'order_line' subfields to improve the performance
- More friendly with users showing status messages
- Consolidated autosave functionality

cc @tecnativa TT32688  @chienandalu @GSLabIt

### CODE REVIEW

**Comment by GSLabIt** [comment]
@Tardo Should the branch be rebased? Seems there are changes that are not realted to this pr.

**Comment by Tardo** [comment]
@GSLabIt rebased

**Comment by GSLabIt** [comment]
@Tardo it's a bit hard to get changes that are not formatting ones 😬

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge it as it has been battle tested in production for a while:

/ocabot merge major

**Pull request merged**
