### PR TITLE
[ADD][7.0] New module: web_exportall

### PR DESCRIPTION
**Pull request by craiggowing**
This module adds a feature to export all records from the current search view including all records from all other pages. This also adds a handler to the server to send a streamed response to prevent timeouts and reduce memory usage when many records are being read.

### CODE REVIEW

**Comment by laetitia-gangloff** [comment]
:+1: (functional only)
It is really great, thank you !

**Comment by pedrobaeza** [comment]
Please apply same comments than in 8.0: https://github.com/OCA/web/pull/171

**Comment by OSguard** [comment]
can we finish this module?

**Comment by pedrobaeza** [comment]
Is this still interesting for anyone? AFAIK, there are comments unattended.

**Comment by pedrobaeza** [comment]
Closing as no answer. Any way, FYI, `web_export_view` (in v8) now exports all the recordset when you select on the upper part.

**Pull request closed without merging**
