### PR TITLE
MIG:12.0 web sheet full width module

### PR DESCRIPTION
**Pull request by ovnicraft**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is included in new `web_responsive` module, so no need to migrate it.

**Comment by ovnicraft** [comment]
I cant find `web_responsive` migrated.

**Comment by pedrobaeza** [comment]
You haven't searched too much... #1066

**Comment by ovnicraft** [comment]
Thanks! so how decide on that ? close this ? 
Now we are migrating many modules to 12.0 and could be an independent module if not use `web_responsive`

**Comment by pedrobaeza** [comment]
I would go for the full responsive experience sincerely. The PR is functional, but we want to add a couple more features.

**Comment by pedrobaeza** [comment]
`web_responsive` module is now merged.

**Comment by ovnicraft** [comment]
Great i close this in favor `web_responsive` is doing the job, would be good info about this on migration issue.

**Comment by pedrobaeza** [comment]
Done

**Pull request closed without merging**
