### PR TITLE
[8.0] web_dialog_size: make dialog window moveable

### PR DESCRIPTION
**Pull request by wpichler**
Push request for 8.0 version - i did tested it against 8.0 - does work

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But you have moved also a lot of commits that doesn't belong here. You only have to cherry-pick the commit with the change. Over a clean 8.0 branch, make:

```
git cherry-pick 4e245cd55c7e35a14ea8d6acb7210d5c6d157346
```

**Comment by wpichler** [comment]
sorry - my git skills are limited ;-)
I have done a fresh clone from OCA/web original repository - did added my remote - tried to cherry-pick - but did not work.
Can you explain it more detailed - or should i simple delete the current fork - and make a fresh one ?

**Comment by pedrobaeza** [comment]
I think you have forgotten to make `git fetch <your_remote_name>` for downloading the information of your branches to make the commit known.

**Comment by fossoult** [comment]
I don't like add draggable because with that you are not able to select text anymore (in Chrome and Firefox)

**Comment by pedrobaeza** [comment]
AFAIK you only lose the possibility of selecting the title of the window, not the rest. Isn't it?

**Comment by fossoult** [comment]
No i am not able to select fields label, paragraphe like this:
`<p class="alert alert-warning">blabla</p>`

I am able to use the view (write think add elem on o2m..).

**Comment by pedrobaeza** [comment]
Uhm, that's indeed not desirable, but maybe we can program the behaviour I described.

**Comment by fossoult** [comment]
Mmm..

Also I have a pull request to do with this module adding new fonctionnalities allowing to auto extend by default via the context from an action or a M2M/O2M field. 

I would like to propose it but there is an not already accepted PR which seems good ( https://github.com/pedrobaeza/web/blob/692d1ba0f4ee8c9d6f45327b21148db485aa935a/web_dialog_size/static/src/js/web_dialog_size.js )

I also upgrade this module on v9 and will make a PR..

I don't know who is able to validate pull request but I think it could be nice to clean this module before send my PR...

**Comment by pedrobaeza** [comment]
We need enough people to review the PRs (3 in case of merging before 5 days, 2 on the rest of the cases). Feel free to propose an enhanced PR that includes all, and ask for closing these ones.

**Comment by hbrunn** [comment]
please rebase

**Comment by wpichler** [comment]
I do have a new version which does make the window only dragable using the header - so you can select the rest in the form - i will pull it today

**Comment by hbrunn** [comment]
@wpichler sounds good, then I'll close this one

**Pull request closed without merging**
