### PR TITLE
[UPD] web_dialog_size: reduce rpc call to get config

### PR DESCRIPTION
**Pull request by hailangvn**
After installing web_dialog_size and setup its parameter, there's a slight delay where we can see the modal at its normal size and then after a rpc to ir.config_parameter:get_web_dialog_size_config() the modal is maximized.

This commit is to set a session value then use it to set initial dialog size upfront without delay.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Very needed patch!

**Review by StefanRijnhart — APPROVED** [review]
Code review, functional test.

**Comment by pedrobaeza** [comment]
Oops, I have aborted my merge.

**Pull request merged**
