### PR TITLE
[MIG] Migrated web_environment_ribbon to v10.0

### PR DESCRIPTION
**Pull request by Garamotte**
The only thing to change for this migration cas the `require('$')` to replace by `require('jquery')`.

Tested with and without web_enterprise.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
(code review)

**Comment by alexis-via** [comment]
:+1:

**Review by lmignon — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
@alexis-via, for other cases, use new GitHub review options, because I have plans to use this for counting reviews in bots/statistics. I merge the first OCA 10.0 migrated module!

**Comment by alexis-via** [comment]
@pedrobaeza Yes, but I don't always get the button to do that... I don't know why.

**Comment by pedrobaeza** [comment]
You have it always in the third tab "Files changed"

**Pull request merged**
