### PR TITLE
[12.0][MIG] web_view_calendar_column

### PR DESCRIPTION
**Pull request by etobella**
Standard migration. Changing the version was enough to make it work

### CODE REVIEW

**Review by jarroyomorales — APPROVED** [review]

**Review by robyf70 — APPROVED** [review]

**Comment by jarroyomorales** [comment]
The title of this PR is not the same as the module `web_view_calendar_column` !

**Comment by pedrobaeza** [comment]
@dreispt please don't this kind of mass PR merge again, as you have collapsed Travis during 2 days. If you mark 10 PRs of the same branch to merge at the same time, what happen is:

- 10 builds are enqueued.
- The first one is merged. Another 9 are enqueued for the rest with a rebased branch.
- The second one is merged. Another 8 are enqueued for the remaining with a rebased branch.
- etc

So it's very underperformant and we are still suffering the consequences (still 50 remaining builds)

**Comment by dreispt** [comment]
I wish PSCs and maintainers would regularly check the ready to merge PRs. It's not that much work.
@pedrobaeza Is this a merge bot limitation? I was not aware of it.

**Pull request merged**
