### PR TITLE
[17.0][MIG] web_widget_image_download: Migration to 17.0

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

@HaraldPanten 
@ValentinVinagre 
@luis-ron 

T-6451

### CODE REVIEW

**Comment by manuelregidor** [comment]
@luis-ron Could you review, please?

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Review by Tisho99 — APPROVED** [review]
LGTM. Code and functional review

**Pull request merged**
