### PR TITLE
[IMP] fix e265

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: 

You will have to check why we can't merge this automatically. Maybe a rebase? Or a dependent PR?

**Comment by hbrunn** [comment]
no, that was some revision-foo because i fucked up in the first place. this one is for good old merging locally and then pushing

**Comment by guewen** [comment]
:+1:

**Comment by bwrsandman** [comment]
Needs a rebase

**Comment by hbrunn** [comment]
so

**Pull request merged**
