### PR TITLE
10.0 mig support branding

### PR DESCRIPTION
**Pull request by nikiwaibel**

### CODE REVIEW

**Comment by hbrunn** [comment]
same comments as for https://github.com/OCA/web/pull/430 - you might even be better off to start from this branch, add your changes and fix my last comment

**Comment by hbrunn** [comment]
by now, better chrry pick the commits from https://github.com/OCA/web/pull/469

**Review by Martronic-SA — CHANGES_REQUESTED** [review]
Could it be rebased with changes made for v 9.0?
Working well on 10.0 however.

**Comment by pedrobaeza** [comment]
Closing in favor of #646

**Pull request closed without merging**
