### PR TITLE
[14.0][FIX] web_widget_x2many_2d_matrix - show_column_totals and show_row_totals

### PR DESCRIPTION
**Pull request by enriquemartin**
Needs to `parse_boolean()` the `show_column_totals` and `show_row_totals` attributes. 
Also it was aggregating every float, monetary or integer field even if the attribute was false, so OR operator has been changed for AND.

### CODE REVIEW

**Comment by petrus-v** [comment]
is it the same that as been fixed on version 12 in a different way ? https://github.com/OCA/web/pull/1622/files

**Comment by enriquemartin** [comment]
not exactly @petrus-v we need to change the operator, otherwise the totals are always displayed

**Comment by xavier-bouquiaux** [comment]
tested and works great thanks @enriquemartin

**Review by sbejaoui — APPROVED** [review]

**Review by sbejaoui — APPROVED** [review]
Code review. 
Thanks

**Review by OpenCode — APPROVED** [review]
It works

**Review by dariodelzozzo — APPROVED** [review]

**Pull request merged**
