### PR TITLE
[14.0] [MIG] web_widget_digitized_signature

### PR DESCRIPTION
**Pull request by are-agilebg**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Odoo already includes a widget for digitizing a signature. Why migrating this module?

**Comment by are-agilebg** [comment]
> Odoo already includes a widget for digitizing a signature. Why migrating this module?

Ooops.. I didn't know. Are you referring to https://github.com/odoo/enterprise/tree/14.0/sign?

**Comment by pedrobaeza** [comment]
No, nothing enterprise. Community edition includes it. You can see it for example signing a sales order for the portal if you have configured it so.

**Comment by are-agilebg** [comment]
> No, nothing enterprise. Community edition includes it. You can see it for example signing a sales order for the portal if you have configured it so.

It seems to me that Odoo CE includes only the digital signature through the portal (odoo/addons/portal), not as a general widget that I can include in any form whereas I need it. Am I missing something?

**Comment by pedrobaeza** [comment]
Not really, AFAIK it can be used anywhere.

**Comment by tarteo** [comment]
@pedrobaeza is right just checked it on [runbot](https://runbot.odoo.com/).
image

```widget="signature"```

**Pull request closed without merging**
