### PR TITLE
[13.0][mig] web_widget_mpld3_chart

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Migration from https://github.com/OCA/web/pull/1516

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@LoisRForgeFlow can you help me here? the pre-commit introduces changes to the manifest file, that cause flake8 to fail. https://travis-ci.org/github/OCA/web/jobs/663369647#L393

**Comment by AdriaGForgeFlow** [comment]
> @LoisRForgeFlow can you help me here? the pre-commit introduces changes to the manifest file, that cause flake8 to fail. https://travis-ci.org/github/OCA/web/jobs/663369647#L393

My commit should fix it

**Review by AdriaGForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
