### PR TITLE
Fix issue with checkbox size in tree view

### PR DESCRIPTION
**Pull request by mohmdlabeeb**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Which error? The big size is on purpose.

**Comment by mohmdlabeeb** [comment]
The UI would be better if it is of normal size

**Comment by ypapouin** [comment]
I agree with @pedrobaeza , this big size is more practical on a daily usage.
But maybe an in-between solution would be nice.

Look at Gmail:
image

The circle is the clickable part and its only appears on hover.

**Comment by pedrobaeza** [comment]
On mobile/tablet, there's no hover. That's why we put it that size.

**Pull request closed without merging**
