### PR TITLE
[12.0][MIG] web_search_with_and

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard migration.

@Eficent

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional test :+1:

**Review by tarteo — APPROVED** [review]
Code LGTM

**Comment by pedrobaeza** [comment]
Ouch, there was #1203 before this one. Is that one correct? If so, it should be prioritized. Deleting branch for avoiding merge.

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza did not see that one, sorry. I guess it will work, no changes were required. I will validate the other one and you can merge.

**Pull request closed without merging**
