### PR TITLE
[16.0][IMP] web_refresher: Backport refresh way from v17

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT48551

- [x] Addapt to allow refreshing "ir.actions.report" and "ir.actions.client"

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
ping @sergio-teruel @chienandalu

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by CarlosRoca13** [comment]
ping @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
