### PR TITLE
[13.0][IMP] web_responsive: Bigger checkboxes in list view

### PR DESCRIPTION
**Pull request by Tardo**
fw-port of #1797 

cc @tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Code review

**Review by yajo — APPROVED** [review]

**Comment by Tardo** [comment]
~~Don't merge this, needs improvements. Waiting for https://github.com/OCA/web/pull/1803 reviews...~~ thanks.

**Comment by Tardo** [comment]
Ok, this is ready for review/merge

**Comment by pedrobaeza** [comment]
Tested on runbot and working well, so:

/ocabot merge patch

**Pull request merged**
