### PR TITLE
[16.0][FIX] web_company_color: Set defaults hardcoded to avoid errors charging the assetbundle

### PR DESCRIPTION
**Pull request by CarlosRoca13**
When trying to charge the assetbundle the theme-color("primary") function is not found what causes problems when trying to set the default values.
Example_no_change

With this changes the default value is the value set on https://github.com/odoo/odoo/blob/ad9f8fae717aae4cad5b3715c1f73ee906b64f8d/addons/web/static/src/scss/primary_variables.scss#L55 this change avoid the problems and the module works fine.
Example_change

Addapted too the class for required fields.

cc @Tecnativa TT50098

ping @sergio-teruel @pilarvargas-tecnativa

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
Added too the migration script for the companies that the change has not beeing applied

**Review by pedrobaeza — APPROVED** [review]
To hardcode the colors is the only option here.

**Review by pilarvargas-tecnativa — APPROVED** [review]
Thanks! :+1:

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
