### PR TITLE
Reduce checkbox size form 24px to 12px

### PR DESCRIPTION
**Pull request by mohamedhagag**
Just a UI enhancement as it looks too big for checkbox

image

image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
That was done on purpose, so we don't want to go back on that. This is friendly with touch devices where our fingers can't mark such small checks. It's just you have to get used to. Closing as won't change.

**Comment by mohamedhagag** [comment]
@pedrobaeza Sure, You are right in your PoV, 

But we can add media for small screens in CSS to show bigger checkbox on mobile and touch devices !

Would you accept such solution ? @pedrobaeza

**Comment by pedrobaeza** [comment]
I don't, as I prefer also these big checkboxes in normal screens. Let's see if others think the contrary.

**Comment by mohamedhagag** [comment]
I was sure you will not, although it's a simple logic 
Best wishes for the community & OCA

**Comment by yajo** [comment]
> But we can add media for small screens in CSS to show bigger checkbox on mobile and touch devices !

This seems a good solution. Would you update the code please?

**Comment by pedrobaeza** [comment]
Our customer feedback is that they want big checkboxes even in desktop. It's difficult to click on such small checkboxes on certain environments.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Unless this is configurable by an option, keeping current preference as default, this is not mergeable.

**Comment by Tardo** [comment]
Since having these larger checkboxes doesn't require reserving more space, I don't think it's wrong to have them always large.

**Comment by yajo** [comment]
I agree they are quite ugly though. So it makes sense for somebody to want to customize them. Let's see what the OP says.

**Comment by pedrobaeza** [comment]
What `OP` means? This can't be removed, so if you want it, it should be configurable.

**Review by sergio-teruel — CHANGES_REQUESTED** [review]
I do not agree with this change.
In responsive mode wwith  small checkbox is complicated to click on it

**Comment by yajo** [comment]
> What `OP` means?

Original Poster. @mohamedhagag in this context. I'm just letting him decide if he wants to do it your way, or if he prefers to close the PR.

**Pull request closed without merging**
