### PR TITLE
[16.0][MIG] web_listview_range_select

### PR DESCRIPTION
**Pull request by CRogos**
supersedes #2355
- fix commit history
- fix firefox bug

### CODE REVIEW

**Comment by CRogos** [comment]
@tarteo , @astirpe could you review this follow-up PR?

**Review by MohamedOsman7 — APPROVED** [review]
Functionality and code LGTM

**Review by lucuswolfius — APPROVED** [review]
Tested on runboat, works fine.

**Comment by CRogos** [comment]
@pedrobaeza can you merge and close #2355 ?

**Comment by CRogos** [comment]
@pedrobaeza  can you retry?

**Comment by CRogos** [comment]
@pedrobaeza rebased... next try?

**Comment by pedrobaeza** [comment]
Is this the folder symbolic link problem?

/ocabot merge nobump

**Comment by CRogos** [comment]
@pedrobaeza  I don't know, but I don't think so. Can you find any useful log?
I now added the change of this commit to the migration commit so it will hopefully prevent this additional commit.
image

**Comment by pedrobaeza** [comment]
Please remove the setup subfolder for this module, and run again pre-commit, and commit changes.

**Comment by CRogos** [comment]
I did this, but there was no change to commit.

**Comment by CRogos** [comment]
@pedrobaeza can you try it one more time? If it is not working I'll make a new migration and cherry-pick the last commit.

**Comment by CRogos** [comment]
@pedrobaeza I did a fresh migration and made a cherry-pick of the "Migration to 16.0" commit. Than I've pushed it with -f on this branch. 
I also checked in runboat that everything is still working. 

Could you try again?

**Comment by pedrobaeza** [comment]
Your pull requests are always showcasing edge cases, hehe:

/ocabot merge nobump

**Comment by CRogos** [comment]
I found this in the code cover action:

->  Pinging Codecov
https://codecov.io/upload/v4?package=github-action-v1.5.2-1.0.3&token=secret&branch=16.0-ocabot-merge-pr-2597-by-pedrobaeza-bump-nobump&commit=b87b351cddbbde6d3151577cafca1cf[49](https://github.com/OCA/web/actions/runs/6160659314/job/16718131042#step:9:50)31433ac&build=6160659314&build_url=http%3A%2F%2Fgithub.com%2FOCA%2Fweb%2Factions%2Fruns%2F6160659314&name=&tag=&slug=OCA%2Fweb&service=github-actions&flags=&pr=&job=tests&cmd_args=n,F,Q
{'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}

**Comment by pedrobaeza** [comment]
That checks are not mandatory, but I don't know what is happening. @sbidoul do you have any clue?

**Comment by CRogos** [comment]
@sbidoul can you help?

**Comment by sbidoul** [comment]
I don't know why it did not merge. Can you retry? I doubt it's related to codecov.

**Comment by pedrobaeza** [comment]
We will never know...

**Pull request merged**
