### PR TITLE
[ADD] web_session_auto_close

### PR DESCRIPTION
**Pull request by IT-Ideas**
This commit adds the web_session_auto_close module which purpose is to is to automatically close the session when the last odoo tab is closed or when the computer gets in idle mode.

The `timeout` occurs 15 seconds after the tab has been closed or the computer got idle.

### CODE REVIEW

**Comment by IT-Ideas** [comment]
@sbidoul here is the PR for the auto session timeout at tab closing. Could you have a look and let me know what you think of it?
Thanks!

**Review by sbejaoui — APPROVED** [review]
Code review + functional test

**Review by pierre-halleux — APPROVED** [review]

**Comment by IT-Ideas** [comment]
Just rebased and corrected typo in `manifest.py`

**Pull request merged**
