### PR TITLE
[REM][requirement.txt] remove the requirement of matploit becase crea…

### PR DESCRIPTION
**Pull request by matteoopenf**
…te conflict when the repo is added on odoo.sh

### CODE REVIEW

**Comment by pedrobaeza** [comment]
But this library is needed for one of the modules in this repository. You can't remove it. Any problem you have, should be solved other way.

**Comment by matteoopenf** [comment]
> But this library is needed for one of the modules in this repository. You can't remove it. Any problem you have, should be solved other way.

which way,  the requirement as  is broken odoo.sh, said me how can I change and I will do?

**Comment by matteoopenf** [comment]
> But this library is needed for one of the modules in this repository. You can't remove it. Any problem you have, should be solved other way.

I also propose The move the specifc version requirement on manifest of module, because if you keep there the requirement odoo.sh try to install both requirement and the build failed

**Comment by pedrobaeza** [comment]
There is no such "move to the manifest of the module". You need to declare the requirements.txt the same. If odoo.sh doesn't interpret correctly both lines, that discriminates by Python version, then it's a problem of Odoo.sh, and you should report it there. Closing this as invalid.

**Pull request closed without merging**
