### PR TITLE
[ADD] web_widget_x2many_2d_matrix_demo

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
# 
# 2D matrix for x2many fields demo

This module prepares an example for the module 'web_widget_x2many_2d_matrix'.

It implements a simple wizards that allows users to enter the planned hours
for all the projects.
# Usage

Go to 'Project / Enter Planned hours'

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
I cannot make the module 'web_widget_x2many_2d_matrix' work. I have created a demo of this widget in order to validate the behavior, establish a productive conversation on how to use it, and debug possible errors, 

At this moment, when I open the matrix nothing is shown:
image

As you can see, at least a task should appear.

Tested also in 8.0 with same results.

cc @pedrobaeza @hbrunn

**Comment by pedrobaeza** [comment]
You don't need this module for a demo. See https://github.com/OCA/sale-workflow/tree/9.0/sale_order_variant_mgmt

**Comment by JordiBForgeFlow** [comment]
Ok, thanks Pedro! I will follow up on the example that you provide. But I will keep this open for a while. I created it as advertised by @hbrunn in the module readme, and it will not work. I'd like to understand better why.

**Comment by JordiBForgeFlow** [comment]
I could make it work, but forcing the x and y values to be chars. If I put them as non-chars, it won't work.

image

**Comment by pedrobaeza** [comment]
In my module axis are many2one. Check how is done.

**Pull request closed without merging**
