### PR TITLE
[ADD] web_widget_text_count

### PR DESCRIPTION
**Pull request by leemannd**
Solving pre-commit issue of https://github.com/OCA/web/pull/1357 which is ready to be merged.

NB: the author of the previous PR is no longer active on the OCA

### CODE REVIEW

**Review by bosd — APPROVED** [review]

**Review by StephaneMangin — APPROVED** [review]

**Review by cyrilmanuel — APPROVED** [review]

**Comment by simahawk** [comment]
@leemannd I've blocked the merge: can you please squash the commits and amend the msg w/ the right module name?

**Comment by bosd** [comment]
Would love to get this one onv 14.

**Pull request merged**
