### PR TITLE
[10.0] [MIG] web_duplicate_visibility module

### PR DESCRIPTION
**Pull request by Fenkiou**
Hi guys,

Just a small update to be able to install this module with pip when it will be released with your tool.

Question, does your toolchain push releases to pypi automatically ?

Damned, I'm so dumb, didn't check if the module was available for 10.0 or not and it's not..

### CODE REVIEW

**Comment by Fenkiou** [comment]
Now its migrated and tested.

@Yajo, about my question on the release pushed to pypi, do you know who's in charge of this?

**Comment by yajo** [comment]
Possibly @sbidoul and @lmignon can help here more than me. AFAIK this should be done automatically nightly, but not sure honestly.

**Review by yajo — APPROVED** [review]

**Comment by lmignon** [comment]
@Fenkiou @Yajo Indeed it should be done automatically nightly once merged.

**Comment by pedrobaeza** [comment]
@Fenkiou have you followed migration to rescue missing commits? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by lmignon** [comment]
@Fenkiou @Yajo @pedrobaeza A PR already exists for a long time https://github.com/OCA/web/pull/557. Unfortunately I'm not able to fix the JS tests

**Comment by yajo** [comment]
Hmm ok then closing in favor of that one, which seems more complete.

**Comment by Fenkiou** [comment]
Oh sorry, didn't search for existing PR, I was in hurry..

**Comment by pedrobaeza** [comment]
If you are able to fix the test in the other PR, we can superseed that one with yours.

**Pull request closed without merging**
