### PR TITLE
Possibilty to create a non square matrix

### PR DESCRIPTION
**Pull request by sebastiken**
When using *web_widget_x2many_2d_matrix* and some values *(cells)* of the matrix does not exists, it did raise **js** error. With this *PR*, it shows empty cell.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you explain a bit the PR? Is this a backport of some funcionalities? If so, please try to respect original commits.

**Comment by sebastiken** [comment]
@pedrobaeza excuse it was a WIP, I wanted to PR with my fork until it will be finished. Please, close this merge *unmerged*.

**Comment by pedrobaeza** [comment]
No problem. We can set it up as WIP right now.

**Comment by sebastiken** [comment]
So, I would like to split this PR in two. Because 1b19b11 is a fiinished commit and 074c830 is WIP.

**Comment by pedrobaeza** [comment]
OK, you can leave the correct commit here and rename PR, and remove the other one for doing other PR.

**Pull request closed without merging**
