### PR TITLE
[14.0][IMP] Show AppsMenu by default

### PR DESCRIPTION
**Pull request by SplashS**
I made some hacks to display apps menu when user logged in system instead of Communications module.
Also I made Enterprise-style AppsMenu behavior on Website.
This is implementation of #1435

### CODE REVIEW

**Comment by mileo** [comment]
LGTM tested on runbot, could you make this optional like: 

https://github.com/SplashS/web/blob/14.0-default-appdrawer/web_responsive/models/res_users.py#L10

**Review by mileo — APPROVED** [review]

**Comment by SplashS** [comment]
I thought about this customization.
But there is one. You can choose default action for each user. In this case user will get this action on start instead of appsmenu.
This customization has sense only in case if we plan to leave current behavior by default.
I wanted to make new behavior by default.
What do you think?

**Comment by GSLabIt** [comment]
@SplashS any chance to back port to 12.0?

**Comment by SplashS** [comment]
> @SplashS any chance to back port to 12.0?

I can say about 13.0 that it is possible without serious changes in this PR.
I haven't seen 12.0 so deep.

**Comment by pedrobaeza** [comment]
I don't think we should perform such changes in stable versions, as they change seriously the behavior, and the risk of bugs is high.

**Comment by SplashS** [comment]
> I don't think we should perform such changes in stable versions, as they change seriously the behavior, and the risk of bugs is high.

Did you mean 12.0 or 14.0 too?

**Comment by pedrobaeza** [comment]
12 and 13. 14 module has just arrived, so it's still a good moment to introduce these changes.

**Comment by SplashS** [comment]
> 14 module has just arrived, so it's still a good moment to introduce these changes.

What do you think about default behavior? There is option to override default screen for each user already. Should we make another option to on/off behavior from this PR?

**Comment by pedrobaeza** [comment]
I think it can be OK to leave as default behavior while not home action is defined.

**Comment by SplashS** [comment]
@Tardo maybe you can review this?

**Comment by andreampiovesana** [comment]
merge?

**Comment by SplashS** [comment]
> merge?

I think @pedrobaeza is right. There is too late to provide this feature in stable version.

It was included in 15.0.

I consider this PR is outdated.

**Comment by andreampiovesana** [comment]
how it works in version 15? and in version 16?

**Comment by pedrobaeza** [comment]
It was partially reverted. It has the side effect of not allowing to put a home action.

**Pull request closed without merging**
