### PR TITLE
[16.0][FIX] web_responsive: Wrap text when display_name is too long

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT43540

ping @pedrobaeza @chienandalu

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
The name `bootstrap_overriden` is correct?

**Comment by CarlosRoca13** [comment]
I change it to form_controller.scss

**Review by chienandalu — APPROVED** [review]
:+1:

**Review by chienandalu — APPROVED** [review]
:+1:

**Pull request merged**
