### PR TITLE
[IMP] web_translate_dialog: fwd port to 13.0

### PR DESCRIPTION
**Pull request by etobella**
Same changes applied on https://github.com/OCA/web/pull/1836

### CODE REVIEW

**Comment by etobella** [comment]
Without web_translate_dialog it was working properly

**Review by hkapatel-initos — APPROVED** [review]
code review LGTM

**Comment by hkapatel-initos** [comment]
it would be nice if someone add a review.

**Comment by hkapatel-initos** [comment]
it would be nice if someone add a review.

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Review by simahawk — APPROVED** [review]

**Pull request merged**
