### PR TITLE
[16.0][MIG] web_widget_plotly_chart

### PR DESCRIPTION
**Pull request by robyf70**

### CODE REVIEW

**Review by odooNextev — COMMENTED** [review]
LGTM

**Review by odooNextev — APPROVED** [review]
LGTM

**Comment by ccandito** [comment]
approved

**Review by ccandito — APPROVED** [review]
approved

**Review by len-foss — APPROVED** [review]
Works great!

**Comment by robyf70** [comment]
@pedrobaeza Can we get it merged?

**Pull request merged**
