### PR TITLE
[MIG] web_view_calendar_list: Migration to 14.0

### PR DESCRIPTION
**Pull request by olgamarcocb**
HELP: I do not understand why "CalendarRenderer.extend" is acting as an include.

### CODE REVIEW

**Review by etobella — CHANGES_REQUESTED** [review]
On Runboat I created a Calendar List for Maintenance Request with the following format:

```
<calendar_list date_start="schedule_date" date_delay="duration" color="user_id" event_limit="5">
                <field name="user_id" filters="1"/>
                <field name="priority"/>
                <field name="maintenance_type"/>
            </calendar_list>
```
I was unable to test it (it seems to happen the same error on the standard calendar view)

**Comment by olgamarcocb** [comment]
I do not understand why "CalendarRenderer.extend" is acting as an include. Any thoughts?

**Comment by olgamarcocb** [comment]
Include fixed with the change of @Martronic-SA Thanks!

**Review by etobella — APPROVED** [review]
Tested locally and it works

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Pull request merged**
