### PR TITLE
[FIX][12.0] web_timeline

### PR DESCRIPTION
**Pull request by hpatelserpentcs**
Users are having trouble scrolling timeline view.

### CODE REVIEW

**Comment by hpatelserpentcs** [comment]
@max3903 Can you please review this PR.

Cc @wolfhall

**Comment by pedrobaeza** [comment]
Please show before and after screenshots

**Review by wolfhall — APPROVED** [review]

**Review by smangukiya — APPROVED** [review]

**Review by max3903 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I have asked for screenshots of the changes because I'm not sure about these changes. I will check and if not agree, I will revert.

**Comment by wolfhall** [comment]
Pedro, 
The current time view has some serious limitation: We have unassigned work that needs to be dragged to a worker (see screenshot)  we have maybe 50 items scheduled for the same time and 100 people to do the work.  then the items need to be dragged and dropped onto the workers below.  the current time view does not support that because you cannot drop an item on workers down in the list. See attached screen for the current implementation.
FSM-0002
The proposed fix creates separate sections that are individually scrollable. 
If this is too disruptive for other users who have fewer items to work with, we could make these views turn on or off via configurations.

**Comment by hpatelserpentcs** [comment]
@pedrobaeza As per above @whafhall comment I will add .gif file of it.

**Before Scroll configuration :** 
demo1


**After Scroll Configuration:**

demo2

Cc @wolfhall @max3903

**Comment by pedrobaeza** [comment]
Thanks for the screenshots. That's exactly what I needed before merging so fast for discussing this.

Seeing the GIFs, can you tell me what is the grey area?

**Comment by hpatelserpentcs** [comment]
@pedrobaeza 

In grey area(First row of timeline view) displaying all orders list which is not assigned to partner.

**Comment by pedrobaeza** [comment]
This is what I supposed, and this is why I don't like this change: doing sticky something that way matches your use case for field-service, but not the general one. Sticky group must be optional to be selected through the timeline definition. I would say that it would be even desirable to have the possibility of setting which value of the group must be the sticky one. Imagine you group by state, and you want the stick one to be the state "Draft".

**Comment by hpatelserpentcs** [comment]
> This is what I supposed, and this is why I don't like this change: doing sticky something that way matches your use case for field-service, but not the general one. Sticky group must be optional to be selected through the timeline definition. I would say that it would be even desirable to have the possibility of setting which value of the group must be the sticky one. Imagine you group by state, and you want the stick one to be the state "Draft".

@max3903 @wolfhall

**Comment by wolfhall** [comment]
@hpatelserpentcs  ok. we can make it configurable.  Hemangini, please make the change to allow the scrollable function to be turned on and off.  If it is not much effort  (one hour) , selecting the field to see what is in the upper area is a plus.  Others can make that improvement otherwise.

**Comment by gaikaz** [comment]
This seems to be breaking some uses of the timeline module. We (company I'm from) are developing a custom app for restaurant menu tracking and after this PR got merged, these problems rose:
1. It doesn't work well with `web_responsive`, as the new sticky part of the timeline is on top of app menu (see **pic. 1**)
2. Some odd spacings appear above and inside the sticky part. (see **pic. 2**)
3. ~~If the active model of items has the Y axis field set to required, we get an error (see **error** below) if the item is put inside the sticky part. _I guess the solution here would be, that the sticky part should not exist, if Y axis field is a required field._~~ _Edit: This was a non-related issue, just much less noticeable before this PR. Might need a separate issue created_

~~**error about the required field**:~~
```
The operation cannot be completed:
- Create/update: a mandatory field is not set.
- Delete: another model requires the record being deleted. If possible, archive it instead.

Model:  ...
```

**pic 1**:
pic1

**pic 2**:
pic2

**Comment by pedrobaeza** [comment]
Reverting the PR then, as confirmed it can't be done this wild mergings without more agreement

**Comment by pedrobaeza** [comment]
Reversed on 79df8aadbe538b83ec2ad620291bbd2007b42478.

Please do another patch and take into account all the remarks, and checking that you don't break things.

**Pull request closed without merging**
