### PR TITLE
[15.0][MIG] web_tree_image_tooltip

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @ChrisOForgeFlow. 

Thanks a lot for porting this usefull module.

One point, could you cherry-pick that commit in that V12 PR. It saves a lot of bandwith.
https://github.com/OCA/web/pull/2163

Otherwise : Diff review / no test : LGTM. Thanks !

kind regards.

**Comment by ChrisOForgeFlow** [comment]
> Hi @ChrisOForgeFlow.
> 
> Thanks a lot for porting this usefull module.
> 
> One point, could you cherry-pick that commit in that V12 PR. It saves a lot of bandwith. #2163
> 
> Otherwise : Diff review / no test : LGTM. Thanks !
> 
> kind regards.
Thanks for review, I think that maybe be better wait for the other pr to be approved, and then we can make forward port

**Review by JuanyDForgeflow — APPROVED** [review]
Tested Locally LGTM!

**Comment by legalsylvain** [comment]
#2163 has been accepted. Could you cherry pick ? 

Also runboat is red. trying to rebase

/ocabot rebase

**Comment by ChrisOForgeFlow** [comment]
> #2163 has been accepted. Could you cherry pick ?
> 
> Also runboat is red. trying to rebase
> 
> /ocabot rebase

I have some issues on cherry-pick, I think because in v15 you should declare assets in manifest, and in js file has conflicts, I suggest make other PR to port your feature

image

image

**Comment by legalsylvain** [comment]
Well. It's not a feature, it's a fix that reduce load time. (By 15 !)
Could you take a time to port it ?

**Comment by ChrisOForgeFlow** [comment]
> Well. It's not a feature, it's a fix that reduce load time. (By 15 !) Could you take a time to port it ?

Done!

**Comment by AaronHForgeFlow** [comment]
@legalsylvain is now ok? :)

**Review by legalsylvain — APPROVED** [review]
Thanks for taking the time to port the patch.

Lgtm code review / no test.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests

**Review by etobella — APPROVED** [review]
Lgtm

/ocabot merge nobump

**Pull request merged**
