### PR TITLE
[14.0][MIG]web_widget_mermaid

### PR DESCRIPTION
**Pull request by hpatelserpentcs**
Migrated the module web_widget_mermaid in v14.

### CODE REVIEW

**Comment by hpatelserpentcs** [comment]
Needs help for below pre- commit error
image

mermaid is Library.

thanks.

**Comment by patrickrwilson** [comment]
@hpatelserpentcs I reached out to Max, he provided some info on the eslint error shown in pre-commit. It looks like either you can add a constant like the example here https://github.com/OCA/web/blob/14.0/web_responsive/static/src/js/web_responsive.js#L25 
OR it may just need a var, something like: var mermaid = require('mermaid'); 

Here is a forum post that may help: 
https://stackoverflow.com/questions/57673384/overriding-javascript-function-throws-error-some-modules-could-not-be-started

**Comment by hpatelserpentcs** [comment]
@patrickrwilson 
 I have checked with example details but did not work, it throws the error, and the chart not showing.

**Comment by Ammar-OSI** [comment]
@patrickrwilson , 

Ready for review

**Review by patrickrwilson — APPROVED** [review]
Tested and works as intended. Thanks, code looks good to me too. LGTM.

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@Urvisha-OSI Can you fix this PR?

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Can you fix this PR?

@max3903 The pre-commit issue is fixed

**Comment by pedrobaeza** [comment]
Maxime, beware with the merge commits inside pull requests.

**Comment by max3903** [comment]
@pedrobaeza What negative impacts can they have?

**Comment by pedrobaeza** [comment]
On next version, when rescuing commit history, a lot of conflicts will arise.

**Comment by max3903** [comment]
@Urvisha-OSI Can you fix the failing tests please?

**Pull request merged**
