### PR TITLE
[9.0][MIG][web_x2many_delete_all] Backport 10.0 -> 9.0

### PR DESCRIPTION
**Pull request by tarteo**
This is a backport 10.0 -> 9.0 for module web_x2many_delete_all

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Works like a charm!

**Comment by levkar** [comment]
What are chances that this will be ported to v8?

Thanks in advance

**Comment by pedrobaeza** [comment]
The JS API changes a lot from 8 to 9 is big, so it's more difficult to backport.

**Comment by tarteo** [comment]
@levkar I'll look into it.

**Comment by tarteo** [comment]
@levkar #486

**Review by yajo — APPROVED** [review]
I took the freedom to apply some minor changes, LGTM now.

**Comment by pedrobaeza** [comment]
@Yajo Should your changes apply also to v10?

**Comment by yajo** [comment]
Yes

**Comment by pedrobaeza** [comment]
Can you please do it?

**Comment by yajo** [comment]
Done: c1d1f0d726c99ec64e58d1cb9f0029d597bac44d

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
