### PR TITLE
[10.0] web_widget_color allow empty values

### PR DESCRIPTION
**Pull request by Martronic-SA**
Allow for empty values and let Odoo framwork to decide it the field is required or not.

### CODE REVIEW

**Review by tarteo — CHANGES_REQUESTED** [review]
Can you increase the version number?

**Comment by Martronic-SA** [comment]
Hi @tarteo I'm sorry but I haven't made any testings on the v11/12 versions.
It's probably working but it would require some checks first.

**Comment by tarteo** [comment]
@Martronic-SA I mean in the manifest file. 😄

**Review by tarteo — APPROVED** [review]
Thanks!

**Review by pedrobaeza — APPROVED** [review]
This should be forward-ported to v11/v12

**Pull request merged**
