### PR TITLE
[14.0][MIG] web_remember_tree_column_width: backport from 15.0

### PR DESCRIPTION
**Pull request by ferran-S73**

### CODE REVIEW

**Comment by ferran-S73** [comment]
Hi @frahikLV @MihranThalhath this is a pretty straightforward port, could you review please?

**Comment by sysadminmatmoz** [comment]
Tested on a multi user high usage database. No issues detected.

**Review by sysadminmatmoz — APPROVED** [review]

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Review by MihranThalhath — APPROVED** [review]

**Review by marcelofrare — APPROVED** [review]
LGTM

**Comment by ferran-S73** [comment]
@OCA/web-maintainers this should be ready to merge

**Comment by francesco-ooops** [comment]
@ferran-S73 can you rebase to rebuild runboat?

**Comment by ferran-S73** [comment]
@francesco-ooops rebased

**Comment by andreampiovesana** [comment]
merge?

**Review by francesco-ooops — APPROVED** [review]
Functional ok

@OCA/web-maintainers go?

**Comment by ioans73** [comment]
@pedrobaeza Can you merge please?

**Pull request merged**
