### PR TITLE
Fix for #116 menu elements wrapping in v8.0

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by legalsylvain** [comment]
@pedrobaeza, could you check if this PR fixes your bug ?
Regards.

**Comment by pedrobaeza** [comment]
I tried on runbot, messing up menus to have a lot of upper entries, and it seems that the problem is gone, so :+1:

**Comment by thomaspaulb** [comment]
Hmm I've been working with it now for several days but it seems that the document ready event still comes too early sometimes..... we need another Javascript event that really fires after the menu item is rendered

**Comment by pedrobaeza** [comment]
Well, I haven't detected the problem in the tests I made. Do you have any method to get the problem?

**Comment by thomaspaulb** [comment]
I normally get the problem in Chrome, whenever I rightclick a top menu item
such as Sales or Settings and open it in a new tab. When I refresh the
page, the problem used to still be always there, now, sometimes it is gone,
sometimes it is still there, IMO this depends on the timing: when docready
occurs "too early" and calls the resize event it will not solve the
problem. But after that when I call the Javascript function from the
console, or resize the page, it will solve the problem.

Possible your Odoo server/client computer is faster than mine so your
timing gets lucky, or the configuration of your menus is different and the
wrapping gets lucky, and so you cannot reproduce?

How I would like to proceed in this is to discuss with you guys about if
there are some Javascript events that I can hook in order to call the
resize event at the appropriate time.... have you guys some experience with
8's Javascript stuff? Otherwise I'll just have to dig in deeper myself...

**Comment by yvaucher** [comment]
BTW this commit is authored by "root". You can fix it with a git commit --amend --author='name <email>'

**Comment by thomaspaulb** [comment]
I think I changed the name now. I also pushed a fix with my lame setTimeout
solution as a workaround for the problems I mentioned before.

**Comment by yvaucher** [comment]
@antiflu First commit is still wrong now that you added commit you need to rebase and amend
using `git rebase -i`

Then do a `git push -f`to apply your changes here

**Comment by hbrunn** [comment]
closing due to inactivity

**Comment by thomaspaulb** [comment]
Have rebased finally, so can we reopen this?

**Comment by pedrobaeza** [comment]
The rebase is not correct. Closing again.

**Pull request closed without merging**
