### PR TITLE
[12.0][FIX] web_edit_user_filter: Use filter label when no value is set

### PR DESCRIPTION
**Pull request by ypapouin**
@tarteo, fix for https://github.com/OCA/web/issues/1261

### CODE REVIEW

**Comment by tarteo** [comment]
I want to test if the changes fixes it, but I can't reproduce the error, can you help?

**Comment by tarteo** [comment]
@ypapouin I want to test if the changes fixes it, but I can't reproduce the error, can you help?

**Comment by ypapouin** [comment]
To reproduce go to a pivot view, add « Time Ranges » filter, then click on it to remove it, a JavaScript error should be raised.

image

**Review by tarteo — APPROVED** [review]
Tested locally this fixes one part of the issue. I still can't edit a filter with a time range in it.

**Pull request merged**
