### PR TITLE
[14.0][MIG] web_dialog_size: Migration to 14.0

### PR DESCRIPTION
**Pull request by pierre-pizzetta**
- Standard Procedure
- Adjusted draggable element to only include its first-child to avoid dragging the whole grayed background with the window

My first migration from OCA Days 2020

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Good work!

**Review by tonygalmiche — APPROVED** [review]
LGTM : Code review and functional review with runbot

image

**Review by fuentes73 — APPROVED** [review]
👌 Tested on runbot

**Pull request merged**
