### PR TITLE
[7.0] Backport web_sheet_full_width from 8.0

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by hbrunn** [comment]
For name consistency, you might better backport https://github.com/OCA/web/tree/8.0/web_sheet_full_width

**Comment by ghost** [comment]
@hbrunn ok, can you add a work in progress label please ?

**Comment by ghost** [comment]
@hbrunn Backported the module from v8.0.

**Comment by hbrunn** [comment]
thanks! Travis error is unrelated, :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by sebalix** [comment]
Works well on the `*-base` database (runbot), but the `-all` one does not work (blank screen), can it be related?

**Comment by hbrunn** [comment]
@sebalix a blank screen is usually caused by an error in a js file. This module doesn't javascript, so I don't think it's related. Open the db in debug mode and see where the error is thrown

**Comment by sebalix** [comment]
@hbrunn thanks! It's related to http://3115223-226-42fa91.runbot2.odoo-community.org/web_pytz/static/src/js/web_pytz.js (line 55) `TypeError: moment.tz is undefined`.
Not related to this PR.

A must have :+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Pull request merged**
