### PR TITLE
[IMP] web_translate_dialog: Allow to use it on a list inside a record

### PR DESCRIPTION
**Pull request by etobella**
With the current widget,you cannot update a field on a record list inside a form. the model was taken from the form.

With the upgrade, it has been solved :wink:

### CODE REVIEW

**Comment by etobella** [comment]
Peek 04-03-2021 15-40

**Review by albariera — APPROVED** [review]

**Comment by etobella** [comment]
@OCA/web-maintainers This solves an issue, any comments are welcome :wink:

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Comment by cubells** [comment]
Solves https://github.com/OCA/web/issues/1734

**Pull request merged**
