### PR TITLE
[15.0][IMP] web_notify html format

### PR DESCRIPTION
**Pull request by hhgabelgaard**
In v12 the message was rendered as HTML
This restore that as an option

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Rebase your branch so you have only your PR commit

**Comment by hhgabelgaard** [comment]
@chienandalu branch rebased

**Review by chienandalu — APPROVED** [review]
LGTM. Thanks!

**Review by Bilbonet — APPROVED** [review]
LGTM 👍

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
