### PR TITLE
[15.0][IMP] web_ir_actions_act_view_reload: Change IrActionsActViewReload to AbstractModel

### PR DESCRIPTION
**Pull request by victoralmau**
Change IrActionsActViewReload to AbstractModel.

Please @pedrobaeza can you review it?

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't get why a model is needed. @ryanc-me Can you explain why?

**Comment by victoralmau** [comment]
Any news about this?

**Review by chienandalu — COMMENTED** [review]
I'd say for this case it could be handled with an `AbstractModel`. Somenthing like would have the same efffect without the need to create a table and all the things that go along with it:

```
class IrActionsActViewReload(models.AbstractModel):
    _name = "ir.actions.act_view_reload"
    _description = "View Reload"
```

**Comment by victoralmau** [comment]
> I'd say for this case it could be handled with an `AbstractModel`. Somenthing like would have the same efffect without the need to create a table and all the things that go along with it:
> 
> ```
> class IrActionsActViewReload(models.AbstractModel):
>     _name = "ir.actions.act_view_reload"
>     _description = "View Reload"
> ```

Although it is a good idea, it is necessary to inherit from `ir.actions.actions`, and in doing so we have the following error.

_The abstract model 'ir.actions.act_view_reload' cannot inherit from the non-abstract model 'ir.actions.actions'._

**Comment by pedrobaeza** [comment]
And adding an ACL this way is never a good idea.

**Comment by chienandalu** [comment]
> Although it is a good idea, it is necessary to inherit from `ir.actions.actions`, and in doing so we have the following error.
> 
> _The abstract model 'ir.actions.act_view_reload' cannot inherit from the non-abstract model 'ir.actions.actions'._

Maybe you can fool it not inheriting from `ir.actions.actions`  but adding a `_get_readable_fields` method:

```
    def _get_readable_fields(self):
        return self.env['ir.actions.actions']._get_readable_fields()
```

**Review by chienandalu — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
