### PR TITLE
[CHG][13.0] web_responsive: normal chatter compliant with enterprise version

### PR DESCRIPTION
**Pull request by benwillig**
This simply makes the normal chatter work in odoo enterprise

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please specify what "odoo enterprise" means? (maybe screenshots of before and after).

You should check also Travis status.

Anyway, both maintainers are on holidays, so this won't be checked in at least a week.

**Comment by benwillig** [comment]
At the moment, when having web_enterprise installed, the chatter was always on the side of the screen even when having "normal" in user preferences. This PR fixes this behavior in this situation.

**Comment by pedrobaeza** [comment]
I think there's no sense in having both, as this is a replacement of `web_enterprise`.

**Comment by yajo** [comment]
Yes, I agree. Sorry but this one is meant to be 100% incompatible with `web_enterprise` :shrug:

**Pull request closed without merging**
