### PR TITLE
7.0 [ADD] web_widget_datepicker_options

### PR DESCRIPTION
**Pull request by veloutin**
# 
# Allow passing options to datepicker widgets

This will set all options specified in the "datepicker" option of datetime
fields to the datepicker.

See http://api.jqueryui.com/datepicker/ for options

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Don't you think a better name can be _web_widget_date_options_?

Also, I think it's convenient to make a PR with this to Odoo for v8/master.

**Comment by veloutin** [comment]
@pedrobaeza Yes, it deserved a better name! #103 created for v8

**Comment by StefanRijnhart** [comment]
Like #103, :+1:

**Comment by veloutin** [comment]
#103 was merged, any further comments on this one?

**Comment by pedrobaeza** [comment]
Yeah, :+1:

**Pull request merged**
