### PR TITLE
[16.0][UPD] web_theme_classic Make placeholders more visible

### PR DESCRIPTION
**Pull request by remi-filament**
This PR proposes to have placeholder in fields more visible, since these were hardly visible since v16...

Previous display : 
image

New display : 
image

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Makes sense ! thanks for your contribution !

**Review by benj-filament — APPROVED** [review]

**Review by Tardo — CHANGES_REQUESTED** [review]
This should be done using `web._assets_primary_variables` asset bundle to modify the `$input-placeholder-color` variable.

**Comment by remi-filament** [comment]
> This should be done using `web._assets_primary_variables` asset bundle to modify the `$input-placeholder-color` variable.

Thanks @Tardo for looking into this, it is indeed much simpler and cleaner, done !

**Comment by Tardo** [comment]
Now I see it a little darker than in the screenshots. I don't know why :/...

**Comment by remi-filament** [comment]
I kept the same value, so there should be no difference, maybe this is related to browser ?

**Comment by Tardo** [comment]
Yes... Firefox seems to apply a color fading, while chromium does not :S

**Comment by Tardo** [comment]
Useful info: https://stackoverflow.com/a/19871806

So, you should modify 'web theme_classic.scss' and add those rules with opacity 1.0 :/

** For me this should be fixed directly in Odoo.

**Comment by remi-filament** [comment]
Thanks for your findings. I see this is now fixed in upstream (https://github.com/odoo/odoo/commit/aa7ab0a92c16a2e911ad39b73d2535572f892e75) so this PR is not needed anymore AFAICT

**Pull request closed without merging**
