### PR TITLE
[14.0] web_search_and - Make functional again

### PR DESCRIPTION
**Pull request by richard-willdooit**
Fixes breaking change introduced at #1976 

[Similar to #2283 - Found a number of breaking changes had been introduced at the other code update.]

nb: The breaking change had not carried forward to v15 or v16

### CODE REVIEW

**Review by davejames — APPROVED** [review]
code and functional review. LGTM

**Comment by matteoopenf** [comment]
image

functional test ok

**Review by matteoopenf — APPROVED** [review]
functional test ok

**Review by federicomassi-of — APPROVED** [review]
It seems me it works neatly.

**Review by destroT — APPROVED** [review]
LGTM

**Comment by matteoopenf** [comment]
@pedrobaeza  is it possibile merge?
thank you for the help

**Comment by filcius** [comment]
I am confused. This MR fix https://github.com/OCA/web/issues/2291
but not 
https://github.com/OCA/web/issues/2331

??

**Comment by matteoopenf** [comment]
> I am confused. This MR fix #2291 but not #2331
> 
> ??

right

**Pull request merged**
