### PR TITLE
[13.0][ADD] web_confirm_duplicate

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
This module adds a confirmation dialog when duplicating a record.

image

@ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
Functional review 👍🏼

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok !!

**Comment by LoisRForgeFlow** [comment]
@OCA/web-maintainers I think this one is ready to merge, could someone trigger it?

**Review by legalsylvain — COMMENTED** [review]
/ocabot merge patch

**Pull request merged**
