### PR TITLE
[11.0][FIX][web_group_expand] Fix issue #987 & Improvements

### PR DESCRIPTION
**Pull request by Tardo**
- Fixes issue #987 
- Follow new readme structure
- Use Less
- Hide expand/collapse buttons if select a view type that isn't a 'list'

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What do you mean with `Hide expand/collapse buttons if select a view type that isn't a 'list'`?

**Comment by Tardo** [comment]
@pedrobaeza I refer to this behavior:
- View Type == List
expand_s
- View Type != List
expand_n

**Comment by aldo774** [comment]
@Tardo, hi dude, I made local tests, and it's worked perfectly, but an error is raised when i tried to access the action edit option in debugger options.
PS: The error isn't raised in previous implementation, at least in my local tests.

test_987

**Comment by Tardo** [comment]
Thanks for the report @aldo774 ... fixed!

**Review by aldo774 — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Thanks!

**Pull request merged**
