### PR TITLE
[FIX][web_option_auto_color] Compatibility with MS Browsers.

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by hbrunn** [comment]
what is edge's problem with the original? If jquery operations don't work there, don't we need to fix this on a more fundamental level?

**Comment by adrienpeiffer** [comment]
For information, this problem is also on IE. I thinks it's better and more clean to put `t-operation="attributes"`

image001

**Comment by hbrunn** [comment]
okay, thanks. In this specific case, I think `position="attributes"` is a better choice anyways. But do I understand correctly that embedded javascript in QWeb never works in IE?

For this change: :+1:

**Comment by pedrobaeza** [comment]
Following @hbrunn's expert approval, then my :+1:

**Comment by jabibi** [comment]
I did not test it, but looking at the code seems correct :+1:

**Comment by adrienpeiffer** [comment]
Thanks !

**Pull request merged**
