### PR TITLE
[10.0-MIG] web_dialog_size for v10.0

### PR DESCRIPTION
**Pull request by bud-e**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot and working!

**Review by elicoidal — CHANGES_REQUESTED** [review]
Can you adapt the copyright headers to the short style?

**Comment by bud-e** [comment]
@elicoidal , Its done.

**Review by elicoidal — APPROVED** [review]

**Review by tarteo — APPROVED** [review]
Tested it on runbot 👍 

Only one minor non-blocking request:
Can you move view/qweb.xml to templates/assets.xml

**Comment by bud-e** [comment]
@tarteo ,

You want me to rename the file `qweb.xml` to `assets.xml`
Or change the file name with directory name (`view` to `templates`) ??!!!
Why change in the directory name...??

**Comment by tarteo** [comment]
@bud-e Rename directory 'view' to 'templates' and rename 'qweb.xm'l to 'assets.xml', to conform the template. https://github.com/OCA/maintainer-tools/tree/master/template/module

**Comment by bud-e** [comment]
@tarteo , Ok thanks for the info.

I'll do the same as per the `maintainer-tools` guidelines.

**Comment by bud-e** [comment]
@tarteo , Its done.

**Comment by tarteo** [comment]
@bud-e Thanks! :)

**Pull request merged**
