### PR TITLE
[15.0][MIG]web_widget_image_download

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]
LGTM @pedrobaeza could you merge?

**Comment by HaraldPanten** [comment]
> /ocabot merge nobody

Trying new commands? 😝

**Comment by pedrobaeza** [comment]
Mobile keyboard auto-correction is very treacherous, hehe

**Pull request merged**
