### PR TITLE
Fix enterprise mobile bug

### PR DESCRIPTION
**Pull request by cormaza**
On enterprise mobile version, on m2o fields show error on variable search_val.length line 313 because this value come as undefined value

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash both commits into one.

**Review by ivantodorovich — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please squash commits?

**Comment by cormaza** [comment]
In the merge you can squash commits and make only one commit, can you review please

**Comment by celm1990** [comment]
> In the merge you can squash commits and make only one commit, can you review please

@cormaza please review https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Pull request closed without merging**
