### PR TITLE
[16.0][MIG] web_widget_dropdown_dynamic

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by anothingguy** [comment]
hello @gbrito-erpopen, It seems you didn't migrate this module at all, all the code is migrated to OWL, also, the unitest didn't work.
image

**Review by anothingguy — CHANGES_REQUESTED** [review]
@gbrito-erpopen: please check migration code to OWL and rework on this PR

**Comment by ChrisOForgeFlow** [comment]
@gbrito-erpopen Can you please check comments to continue with migration, Thanks!

**Comment by simahawk** [comment]
https://github.com/OCA/web/pull/2563

**Pull request closed without merging**
