### PR TITLE
[15.0][IMP] web_drop_target: Avoid errors for undefined elements

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT48179

This changes are done to avoid errors in dms_field. This error is
found using this other PR: https://github.com/OCA/dms/pull/310

The steps to reproduce the error are:
1. Create a directory or a file without using drag and drop
2. Drag and drop a file into a folder and you will see the error

ping @victoralmau @chienandalu

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by victoralmau — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
ping @pedrobaeza

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem? Put it both in the PR main message and in the commit message.

**Comment by CarlosRoca13** [comment]
It's related with this other PR: https://github.com/OCA/dms/pull/310

1. Create a directory or a file without using drag and drop
2. Drag and drop a file into a folder and you will see the error

**Comment by CarlosRoca13** [comment]
done @pedrobaeza

**Pull request merged**
