### PR TITLE
[16.0][MIG] web_widget_one2many_tree_line_duplicate: Migration to 16.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT46605

ping @victoralmau @chienandalu

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Working great :+1:

**Comment by CarlosRoca13** [comment]
Set to draft because there are a problem with purchase_variant_configurator that has to be solved

**Comment by CarlosRoca13** [comment]
Now it is working fine! :)

**Review by pedrobaeza — APPROVED** [review]
Tested on local with `purchase_variant_configurator` and working great, thanks.

/ocabot merge nobump

**Pull request merged**
