### PR TITLE
[13.0][IMP] web_responsive: Adapt label width

### PR DESCRIPTION
**Pull request by Tardo**
Add more width for form labels in large screens.

cc @tecnativa TT33093

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Put it on the README

**Review by carlosdauden — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@Tardo please add the new feature in the README and I'll merge it.

**Review by ivantodorovich — APPROVED** [review]

**Comment by Tardo** [comment]
Readme updated

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please fw-port it to v14

**Pull request merged**
