### PR TITLE
[13.0][MIG] web_widget_dropdown_dynamic

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@tarteo if you have a spare slice of time, please review

**Comment by alexey-pelykh** [comment]
```
/home/travis/build/OCA/web/web_widget_dropdown_dynamic/static/tests/web_widget_dropdown_dynamic_tests.js
    9:5  error  'QUnit' is not defined  no-undef
   10:9  error  'QUnit' is not defined  no-undef
   42:9  error  'QUnit' is not defined  no-undef
   74:9  error  'QUnit' is not defined  no-undef
  108:9  error  'QUnit' is not defined  no-undef
```
seems linter overreacted a bit?

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional review in runbot (Demo module) and code review

**Comment by alexey-pelykh** [comment]
@OCA/web-maintainers it's a simple one :)

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@pedrobaeza please hit the button, if possible :)

**Pull request merged**
