### PR TITLE
[15.0][MIG] web_widget_one2many_tree_line_duplicate

### PR DESCRIPTION
**Pull request by ThiagoMForgeFlow**
@ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Tested in runboat with sales module. Working as expected :+1:

**Review by JoanSForgeFlow — APPROVED** [review]
LGMT!

**Comment by pedrobaeza** [comment]
Merging based on the reviews. The migration to 16.0 with the OWL refactor has already been done.

/ocabot migration web_widget_one2many_tree_line_duplicate
/ocabot merge nobump

**Pull request merged**
