### PR TITLE
[FIX] higher python version, no system site packages

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change module version number... No, it's a joke :yum: 

Let's see Travis.

**Comment by hbrunn** [comment]
it will fail because there's some syntax error in javascript which makes phantomjs choke. But I've trouble finding the place where this happens

**Comment by pedrobaeza** [comment]
No, it's green! I think you had the phantom PhantomJS failure (today I'm comical, hehe).

**Comment by hbrunn** [comment]
interesting, will have a look then in my PR. Given runbot seems to have trouble (https://runbot2.odoo-community.org/runbot/static/build/3322475-909-3913e6/logs/job_20_test_all.txt), I think we can fasttrack this so that other 10 PRs get green, right?

In my native language and then the 80ies, I'd say you had a clown for breakfast today ;-)

**Comment by pedrobaeza** [comment]
Yes, fast-tracking this

**Comment by pedrobaeza** [comment]
I'm thinking that maybe the reason for runbot to fail is not having `system_site_packages: true`... @moylop260 can you confirm?

**Comment by moylop260** [comment]
I saw the following error in the [runbot base log](https://runbot2.odoo-community.org/runbot/static/build/3322475-909-3913e6/logs/job_10_test_base.txt)
 - `/.repo_requirements/virtualenv/python2.7.13/bin/activate: No such file or directory`

Runbot don't have python2.7.13 version pre-loaded in the base image...
I will fix it

**Comment by hbrunn** [comment]
@moylop260 which ones are there? (and where do I have to look that up to avoid the next stupid question?) we don't specifically need .13, I think from .8 or .9 we should be fine

**Comment by moylop260** [comment]
@hbrunn 
The file binary of python is not named with the minor version and so it is not found it.

 - screen shot 2018-04-10 at 12 23 24

But if the python2.7.12 works for you then we can remove that subversion for the case of runbot for now.

I just used py2.7 for py2.7.12 from travis2docker package: 
 - https://github.com/Vauxoo/travis2docker/pull/115

I tested and now this project is building the image fine.

 - screen shot 2018-04-10 at 12 26 09


Note: The ideal case is added all minor version of python in the base image but is a lot of work... for now this quick fix resolve the main issue.

**Comment by moylop260** [comment]
@gurneyalex 
Could you help us to update `travis2docker` python package latest version (4.0.6) for OCA's runbot server, please?

**Comment by hbrunn** [comment]
wow, what a service. thank you so much!

**Comment by gurneyalex** [comment]
@moylop260  Update done.

**Comment by moylop260** [comment]
Thanks @gurneyalex
@hbrunn Now the 10.0 build is green in runbot
https://runbot.odoo-community.org/runbot/build/3322643

**Comment by hbrunn** [comment]
I had no doubt that when the three of us combine we can generate greenness :-) Thanks everyone!

Do we have an opinion if I should PR my change to MQT?

**Comment by moylop260** [comment]
Are you talking about bumpversion of python from [sample_files/.travis.yml](https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L9)?

**Comment by hbrunn** [comment]
and removing system site packages, my understanding is we did this for speed (lxml), but now with the binary python package stuff (wheels) that's not really an issue any more

**Comment by moylop260** [comment]
I got it
+1
It was for old Travis architecture. In fact, for py3.5 we need remove `system-packages` too.

And we should use minimal postgresql 9.4 in order to avoid other issues related like as:
 - https://github.com/OCA/maintainer-quality-tools/issues/432

**Pull request merged**
