### PR TITLE
[14.0] [ADD] web_notify_upgrade

### PR DESCRIPTION
**Pull request by paradoxxxzero**
This module uses web_notify send a notification to every active users whenever a module has been installed or upgraded.

The notification will ask the user to refresh the page to get the latest changes.

20240628_11h54m48s_grim

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM code review
Thanks for your work

**Review by bealdav — APPROVED** [review]

**Comment by sebastienbeau** [comment]
@paradoxxxzero can you migrate it to V16 ?

**Pull request merged**
