### PR TITLE
[14.0][MIG] web_widget_x2many_2d_matrix

### PR DESCRIPTION
**Pull request by Saran440**
Standard Migration

### CODE REVIEW

**Comment by kittiu** [comment]
Functional Tested OK.
No major change.

**Review by kittiu — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test.

**Comment by thomaspaulb** [comment]
@guewen Could you merge this?

**Review by DavidBForgeFlow — APPROVED** [review]

**Pull request merged**
