### PR TITLE
[16.0][IMP] web_m2x_options: some french translations

### PR DESCRIPTION
**Pull request by glitchov**
Some translations were'nt done yet.

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Translations are handled in the OCA's weblate instance: https://translation.odoo-community.org

**Comment by glitchov** [comment]
I know but my user seems to have some trouble when clicking the weblate button: page not found !

**Comment by chienandalu** [comment]
I'm seeing it fine: https://translation.odoo-community.org/projects/web-16-0/web-16-0-web_m2x_options/fr/

**Comment by glitchov** [comment]
Not me unfortunately

**Pull request closed without merging**
