### PR TITLE
[15.0][FIX]-web_responsive module: Go to wrong action menu when access from Root Screen Search Bar when user is set with Home Action Menu

### PR DESCRIPTION
**Pull request by hieulucky111**
# How to reproduce

- Install module web_responsive
- Set Home Action for user in the tab Preferences
- Refresh the page
- Type menu on the Search Bar
- Click on the menu we want
- Redirect us to wrong menu

### CODE REVIEW

**Comment by jcdrubay** [comment]
There is no link to runboat test available?

**Comment by jcdrubay** [comment]
Tested in our test environment, it works nicely.

**Review by jcdrubay — APPROVED** [review]

**Review by Tardo — APPROVED** [review]
Thanks!

**Pull request merged**
