### PR TITLE
[MIG] : Migrated web_dialog_size to v13

### PR DESCRIPTION
**Pull request by sudhir-erpharbor**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
Tested: OK

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The change you have made in JS is affecting the functionality, as now 2 arrows appear when opening a popup dialog:

Selección_003

I suspect the previous instruction was waiting for solving full window before applying the conditions, and now you have removed that asynchronous part. The system has changed to use JS ES6 promises, so you have to adapt the code accordingly.

**Comment by sudhir-erpharbor** [comment]
> The change you have made in JS is affecting the functionality, as now 2 arrows appear when opening a popup dialog:
> 
> Selección_003
> 
> I suspect the previous instruction was waiting for solving full window before applying the conditions, and now you have removed that asynchronous part. The system has changed to use JS ES6 promises, so you have to adapt the code accordingly.

Fixed the issue.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
