### PR TITLE
[MIG] web_widget_child_selector: Migration to 13.0

### PR DESCRIPTION
**Pull request by etobella**
No major changes

### CODE REVIEW

**Comment by olgamarcocb** [comment]
LGTM :+1:

**Review by olgamarcocb — APPROVED** [review]
LGTM :+1:

**Review by dsolanki-initos — APPROVED** [review]
LGTM.

**Comment by dsolanki-initos** [comment]
It would be nice if the maintainers merge this PR

**Comment by dsolanki-initos** [comment]
It would be nice if the maintainers merge this PR

**Comment by dsolanki-initos** [comment]
It would be nice if the maintainers merge this PR

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
@dreispt Can you please try to merge this?

**Pull request merged**
