### PR TITLE
MIG: Migrated web_view_calendar_column from v11 to v13

### PR DESCRIPTION
**Pull request by tpa-odoo**
Migrate web_view_calendar_column from v11 to v13 added new changes also done in core odoo calendar view.

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@tpa-odoo I suppose here we need to preserve the history

**Comment by tpa-odoo** [comment]
> @tpa-odoo I suppose here we need to preserve the history

Agree but module is not available forv12 even. If there is any way or step to follow let me know and will do needful.

**Comment by nikul-serpentcs** [comment]
@tpa-odoo please check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto

**Comment by tpa-odoo** [comment]
> @tpa-odoo please check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto

I think all of that steps are done. Let me know if i missed any will do it.

**Comment by HviorForgeFlow** [comment]
> > @tpa-odoo please check https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto
> 
> I think all of that steps are done. Let me know if i missed any will do it.

2 missing details:
- To preserve commit history: `git format-patch --keep-subject --stdout origin/13.0..origin/11.0 -- $MODULE | git am -3 --keep`
- Run pre-commit  before migrate commit.

**Comment by jarroyomorales** [comment]
Hi @tpa-odoo @nikul-serpentcs @HviorForgeFlow !  Migration to v12 is already in progress here https://github.com/OCA/web/pull/1522, maybe we should try to get v12 merged and then finish this one.

**Pull request closed without merging**
