### PR TITLE
[FIX] description;

### PR DESCRIPTION
**Pull request by legalsylvain**
cosmetic changes in readme file;

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
But this change makes that the images are not shown on module form view:

seleccion_007

**Comment by yvaucher** [comment]
so are visible either on Odoo or on github :/ that's sad.

And it is currently not visible on apps.odoo.com (I have little hope it could be shown there with this patch but it could not work with both.)

https://www.odoo.com/apps/modules/8.0/web_dashboard_tile/

**Comment by lmignon** [comment]
@yvaucher https://www.odoo.com/apps/modules/8.0/web_dashboard_tile/static/src/img/screenshot_dashboard.png > Not found

**Comment by legalsylvain** [comment]
@pedrobaeza. Agree. But better to show on github and apps than on form view. (and it must be fixed in Odoo)

**Comment by pedrobaeza** [comment]
Are you sure this is going to be shown on apps.odoo.com?

**Comment by yvaucher** [comment]
I think as @lmignon pointed it out, that it won't.

**Comment by lmignon** [comment]
It won't be shown if the generated url looks like https://www.odoo.com/apps/modules/8.0/web_dashboard_tile/static/src/img/screenshot_dashboard.png .

**Comment by legalsylvain** [comment]
@pedrobaeza  with this patch, the path  is now a classical relative path, and github can understand it. 
if Odoo apps or Odoo doesn't interprate it correctly, so we have to propose a fix in Odoo. Don't you think ?

CC : @gurneyalex.

**Pull request merged**
