### PR TITLE
[New] widget product selector variant

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please make a proper README following template https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst for seeing what is the feature that this adds.

**Comment by fmdl** [comment]
Dear Pedro, I have add the description, but the screenshot do not appear, do you know why ?

I have made a PR for Odoo to fix the the random order of variante, if you like can put an 👍 : https://github.com/odoo/odoo/pull/17034

**Comment by pedrobaeza** [comment]
I think this is better solved with https://github.com/OCA/product-variant/pull/47, as no specific widget is required, and it allows you more options.

**Comment by fmdl** [comment]
I think is not for the same use.  This module is more universal, it work in bom, purchase, ...

**Comment by pedrobaeza** [comment]
Well, I see a mix of concepts in this widget, developing a full window that can be done with ORM, but let's see what others think. Anyway, in English it's `variant`, not `variante`.

**Comment by fmdl** [comment]
Dear @pedrobaeza, 
The main difference is that the dimension is not limited, the OCA/product-variant#47 is limited at two.

**Comment by pedrobaeza** [comment]
Then you have this module for a similar thing: https://github.com/OCA/product-variant/tree/9.0/purchase_variant_configurator

**Comment by fmdl** [comment]
Yes it is similar, but for me it is not the best integration. In purchase order line you need open a form to add line, even if there no variante. And you need to developpe one new module for each case. My module is more generique.

What do you think that my module use https://github.com/OCA/product-variant/blob/9.0/product_variant_configurator/models/product_configurator.py in the popup configurator ?

**Comment by pedrobaeza** [comment]
You're right, but it's also requires to have all the possible variants created, which sometimes is not feasible as the number of possible combinations is very high. Well, I think we have several different cases that can co-exist, so let's go with the PR and see if people see this interesting.

Please check Travis status.

**Pull request closed without merging**
