### PR TITLE
Slovene translations and translation template

### PR DESCRIPTION
**Pull request by sysadminmatmoz**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by tafaRU** [comment]
Technically :+1:

**Comment by sysadminmatmoz** [comment]
What's the problem with travis!? :)

**Comment by pedrobaeza** [comment]
A possible flick. I have restarted it.

**Comment by yvaucher** [comment]
It's :green_apple: 

:+1:

**Pull request merged**
