### PR TITLE
[14.0][mig] web_decimal_numpad_dot

### PR DESCRIPTION
**Pull request by koenloodts**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test.

**Comment by CasVissers-360ERP** [comment]
Actually @koenloodts I don't think this module is needed anymore:
See: https://github.com/odoo/odoo/pull/56962

Also tested without the the module it works the same. Can you confirm?

**Comment by koenloodts** [comment]
> Actually @koenloodts I don't think this module is needed anymore:
> See: [odoo/odoo#56962](https://github.com/odoo/odoo/pull/56962)
> 
> Also tested without the the module it works the same. Can you confirm?

Hi @CasVissers-360ERP , I tested on new local version of odoo and on a runbot-version. When language Dutch (BE) is used, the dot from the numpad is not recognized as decimal separator.

**Comment by pedrobaeza** [comment]
That PR didn't make it in v14. It landed on master after the freeze. It will be on v15, so this module won't be finally needed then.

**Comment by pedrobaeza** [comment]
@koenloodts you didn't follow migration guide https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 splitting all pre-commit stuff in one commit and the real migration (which is basically to change the version number and regenerate the README) in another.

**Comment by emagdalenaC2i** [comment]
@koenloodts LGTM But you should follow the migration guide

**Comment by enriquemartin** [comment]
LGTM!

**Review by enriquemartin — APPROVED** [review]
LGTM

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
@koenloodts please follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 and separate the pre-commit stuff in one commit and don't modify manually the README.rst file.

**Comment by jjscarafia** [comment]
Hi! one more detail. On v13 module there is [this issue](https://github.com/OCA/web/issues/1843) with tax group pencil. I guess same issue will be there on v14 migration.
We'll try to improve v13 module but is not our expertise this kind of dev.

**Comment by pedrobaeza** [comment]
Superseded by #1933

**Pull request closed without merging**
