### PR TITLE
14.0 mig web widget image download

### PR DESCRIPTION
**Pull request by MeetKD**
Standard Migration

### CODE REVIEW

**Comment by fshah-initos** [comment]
Hi @MeetKD 
You need to adjust the commits to follow the standard migration steps as per the OCA guideline
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by MeetKD** [comment]
@fshah-initos i will look into it.

**Comment by fshah-initos** [comment]
Hi @MeetKD 
Will you please adjust commits as per oca guideline

**Comment by dsolanki-initos** [comment]
Hi @MeetKD
Will you please adjust commits as per oca guideline

**Comment by dsolanki-initos** [comment]
Hi @MeetKD Will you please adjust commits as per the oca guideline.

**Comment by MeetKD** [comment]
Hey @dsolanki-initos I will look into it.

**Comment by dsolanki-initos** [comment]
Hi @MeetKD Will you please adjust commits as per the oca guideline.

**Comment by MeetKD** [comment]
I will try to do it in next week.

**Comment by dsolanki-initos** [comment]
Hi @MeetKD Will you please adjust commits as per the oca guideline.

**Comment by dsolanki-initos** [comment]
Hi @MeetKD Will you please adjust commits as per the oca guideline.

**Comment by dsolanki-initos** [comment]
Hi @MeetKD Will you please adjust commits as per the oca guideline.

**Comment by dsolanki-initos** [comment]
Hi @MeetKD Will you please adjust commits as per the oca guideline.

**Comment by dsolanki-initos** [comment]
@MeetKD could you please add changes for this pull?

**Comment by ikapasi-initos** [comment]
Hi @MeetKD could you please add changes for this pull?

**Comment by ikapasi-initos** [comment]
Hi, @MeetKD any update..?

**Pull request closed without merging**
