### PR TITLE
[11.0][web_decimal_numpad_dot] fix tab navigation issue

### LINKED ISSUE #929: [11.0][web_decimal_numpad_dot] Module breaks tab navigation
The module breaks the tab navigation on editable tree views.

With the module installed:
giphy1

Uninstalling the module:
giphy2

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Fixes the strange navigation jumps. 
Fix #929

### CODE REVIEW

**Review by yajo — CHANGES_REQUESTED** [review]
Still failing.

**Review by tarteo — APPROVED** [review]
Thanks! I agree it's better than it currently is .

**Comment by JordiBForgeFlow** [comment]
Now it works like a charm :)

**Review by pedrobaeza — APPROVED** [review]
Please change module version number

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Done!

**Review by etobella — APPROVED** [review]
Now it works perfectly. LGTM 👍

**Comment by moylop260** [comment]
@Yajo Could you review it again, please?

**Comment by pedrobaeza** [comment]
Merging as @Yajo's comment has been honored.

**Pull request merged**
