### PR TITLE
[IMP] web_invalid_tab: migrating to version 9

### PR DESCRIPTION
**Pull request by kaerdsar**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot

**Comment by lmignon** [comment]
@kaerdsar With OE, once the module is installed the invalid fields are no more highlighted...
With
image
Without

image

**Comment by kaerdsar** [comment]
@lmignon what means 'with OE'? a navigator or a Odoo version?

**Comment by lmignon** [comment]
@kaerdsar Odoo Enterprise :smirk:

**Pull request closed without merging**
