### PR TITLE
[ADD] port web_widget_classes

### PR DESCRIPTION
**Pull request by hbrunn**
# CSS classes for widgets

For simple UI changes, having classes attached to widgets giving
information about the model being displayed can be essential.

For instance, to apply some CSS to the name field in forms for tasks,

::

  .oe_model_project_task input[name='name']
  {
      //your CSS
  }

will be enough.
# Credits
## Contributors
- Holger Brunn hbrunn@therp.nl
## Maintainer

.. image:: http://odoo-community.org/logo.png
   :alt: Odoo Community Association
   :target: http://odoo-community.org

This module is maintained by the OCA.

OCA, or the Odoo Community Association, is a nonprofit organization whose mission is to support the collaborative development of Odoo features and promote its widespread use.

To contribute to this module, please visit http://odoo-community.org.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It looks good, but the name is the only thing I'm not comfortable with. This is not a widget, so that part of the name is not appropiated, but I can't find any good name. Maybe _web_class_ui_adjustment_ can be a good one.

**Comment by hbrunn** [comment]
my reasoning was that it attaches classes to widgets, but indeed, it makes sense to reserve `web_widget_*` for addons providing widgets. Your proposal sounds a bit too generic to me, how about `web_dom_model_classes` (this also reflects better what the addon actually does)

**Comment by pedrobaeza** [comment]
OK, `web_dom_model_classes` sound goood

:+1:

**Comment by hbrunn** [comment]
done

**Comment by pedrobaeza** [comment]
Thanks for the change (although commit message says the contrary :wink: )

:+1:

**Comment by StefanRijnhart** [comment]
Thanks :+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
