### PR TITLE
[12.0][FIX] web_tree_many2one_clickable: Compatible with decoration colors

### PR DESCRIPTION
**Pull request by Tardo**
Using ``<span>`` tag again = Affected by colors
Improved keyboard navigation, now the element is not focusable in readonly mode

cc @tecnativa TT22262

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The name of the module in the title and commit is incorrect.

**Comment by pedrobaeza** [comment]
Are both patches applicable to v13?

**Comment by Tardo** [comment]
Oops! changes done

**Comment by Tardo** [comment]
@pedrobaeza after some tests in 13.0 keyboard navigation appears to work fine without this fix.

**Review by pedrobaeza — APPROVED** [review]

**Review by yajo — APPROVED** [review]
The code looks good, and functional test works, although I'd appreciate at least a screenshot that lets us see what this is fixing... I don't really know what to test.

**Comment by pedrobaeza** [comment]
It's fixing the color of the row through decorators.

/ocabot merge patch

**Comment by pedrobaeza** [comment]
@Yajo do you know why pylint fails?

**Comment by yajo** [comment]
I see this: https://travis-ci.org/github/OCA/web/jobs/678053493#L771

```
BlockingIOError: [Errno 11] write could not complete without blocking
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking
```

My bet is that pylint doesn't work fine when being executed in parallel, although I never saw this before. That can be disabled in pre-commit. Any other ideas @sbidoul @moylop260?

**Comment by pedrobaeza** [comment]
This is not being executed in pre-commit. This is 12.0. I think there's any code here to be analyzed that is blowing up the linter.

**Comment by yajo** [comment]
Oh true.

This could have been some race condition. What about just retrying for now?

**Comment by pedrobaeza** [comment]
It's happening the same on #1589, so it's something structural. I'm analyzing right now.

**Comment by pedrobaeza** [comment]
Fixed with the pylint cleaning I have made:

/ocabot merge patch

**Pull request merged**
