### PR TITLE
[WIP][IMP] web_company_color: Support button and link customizing

### PR DESCRIPTION
**Pull request by manuelregidor**

### CODE REVIEW

**Comment by manuelregidor** [comment]
@ValentinVinagre @HaraldPanten

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@yajo @etobella  do you mind merging this easy one?

THX!

**Comment by etobella** [comment]
I tested on runboat and it didn't work properly. I need to define all parameters, but are not computed with button for the logo :cry: 
Also, with two companies it didn't work properly (I was unable to show different colors :disappointed: )

**Comment by HaraldPanten** [comment]
> I tested on runboat and it didn't work properly. I need to define all parameters, but are not computed with button for the logo 😢 Also, with two companies it didn't work properly (I was unable to show different colors 😞 )

hhhmmm... THX Enric, we'll have a look! @manuelregidor

**Pull request closed without merging**
