### PR TITLE
[14.0][mig]web_switch_context_warning

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Review by fshah-initos — COMMENTED** [review]
LGTM

**Comment by hkapatel-initos** [comment]
@Tardo and @tarteo it would be great if you both can review this PR.

**Comment by hkapatel-initos** [comment]
@MiquelRForgeFlow it would be nice if could you review it here?

**Comment by hkapatel-initos** [comment]
it would be nice if someone could review it here.

**Comment by MiquelRForgeFlow** [comment]
ping: @AdriaGForgeFlow

**Review by AdriaGForgeFlow — APPROVED** [review]
Functional review on runbot changing the user :+1:

**Review by fshah-initos — APPROVED** [review]

**Comment by hkapatel-initos** [comment]
Hello maintainers,
Can you please try to merge it?

**Comment by hkapatel-initos** [comment]
Hello maintainers,
Can you please try to merge it?

**Comment by hkapatel-initos** [comment]
Hello maintainers,
it would be nice if you try to merge it.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
it would be nice if you try to merge it.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
it would be nice if you try to merge it.

**Pull request merged**
