### PR TITLE
[MIG] web_m2x_options: Migration to 15.0

### PR DESCRIPTION
**Pull request by goliveirab**

### CODE REVIEW

**Comment by goliveirab** [comment]
@moylop260 @luisg123v could you please check this...

**Comment by moylop260** [comment]
@goliveirab 

Something is broken could you check the CI result, please?

https://github.com/OCA/web/runs/4119130288?check_suite_focus=true

Note: For now ignore runbot status since that it is unrelated

**Comment by goliveirab** [comment]
> @goliveirab
> 
> Something is broken could you check the CI result, please?
> 
> https://github.com/OCA/web/runs/4119130288?check_suite_focus=true
> 
> Note: For now ignore runbot status since that it is unrelated

@moylop260  @luisg123v all green now (except runbot) could you please check...

Regards.

**Review by moylop260 — APPROVED** [review]
👍

**Review by hugho-ad — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Functionally tested

**Pull request merged**
