### PR TITLE
[14.0][mig] web_widget_text_markdown

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
No major change. LGTM. Functional test

**Comment by hkapatel-initos** [comment]
@thomaspaulb can you please review this PR?

**Comment by hkapatel-initos** [comment]
@Tardo and @njeudy can you both please review this pr?

**Comment by thomaspaulb** [comment]
@hkapatel-initos I will review it once we finish our 13.0 PR.

**Comment by hkapatel-initos** [comment]
it would be nice if  someone could  review it here

**Comment by hkapatel-initos** [comment]
it would be nice if someone could review it here

**Comment by hkapatel-initos** [comment]
@thomaspaulb  Any update?

**Comment by hkapatel-initos** [comment]
@yvaucher can you please review it?

**Comment by kmatthes** [comment]
@hkapatel-initos 
thomaspaulb wrote here https://github.com/OCA/web/pull/1979#issuecomment-885640609 that he want's to finish the 13.0 PR first. He was refering to #1965. So no need to ask thomaspaulb again, before #1965 is done.

**Review by njeudy — APPROVED** [review]
Functionnal test and real test on production database for weeks now. thanks!

**Comment by dsolanki-initos** [comment]
@pedrobaeza can we merge this PR?

**Pull request merged**
