### PR TITLE
8.0 web ckeditor4

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Port of CKeditor widget for html fields to 8.0. Due to updates of CKeditor itself, the diff is out of control but the revelant changes to the integration code is in this commit https://github.com/StefanRijnhart/web/commit/c7080651a22e66f612277ec4845518bb6764c8b9. BTW removing _lib_ from this repo's .gitignore because this is a common path by convention for web related addons.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
A little remark, the rest :+1: 

Thanks!

**Comment by guewen** [comment]
:+1:

**Comment by antespi** [comment]
:+1:

**Comment by legalsylvain** [comment]
Thanks! :+1: (Code review, no test)

**Pull request merged**
