### PR TITLE
[14.0][MIG] web_search_with_and: Migration to 14.0

### PR DESCRIPTION
**Pull request by pedroguirao**
Migration to 14.0 , this module is not in issues list at the moment

### CODE REVIEW

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok

**Review by tibor-barna — COMMENTED** [review]
Code and function checked. No changes are necessary for me. LGTM.
Thanks for your development efforts, @pedroguirao

**Comment by antoniocanovas** [comment]
> Code and function checked. No changes are necessary for me. LGTM. Thanks for your development efforts, @pedroguirao

Thanks tibor-barna!

**Comment by pedroguirao** [comment]
Thanks @tibor-barna !

**Review by jcdrubay — APPROVED** [review]
Tested on runboat, works very well.

**Comment by sviluppo-msa** [comment]
@pedrobaeza could it be merged ?

**Comment by alessandro-fiorino** [comment]
@pedrobaeza could it be merged ?

**Pull request merged**
