### PR TITLE
[17.0][MIG] web_timeline

### PR DESCRIPTION
**Pull request by EdgarRetes**

### CODE REVIEW

**Comment by EdgarRetes** [comment]
@max3903

**Comment by fliot** [comment]
This pull request is "closed",
But the code have not been merge into [OCA:17.0](https://github.com/OCA/web/tree/17.0) branch,
And also [ursais:17.0-mig-web_timeline](https://github.com/ursais/web/tree/17.0-mig-web_timeline) is not available anymore..
Where can I find this code ?
Thanks in advance.

**Comment by EdgarRetes** [comment]
> This pull request is "closed", But the code have not been merge into [OCA:17.0](https://github.com/OCA/web/tree/17.0) branch, And also [ursais:17.0-mig-web_timeline](https://github.com/ursais/web/tree/17.0-mig-web_timeline) is not available anymore.. Where can I find this code ? Thanks in advance.

Hi @fliot. The migration wasn't finished because we had some issues with the code, so there isn't an available code for v. 17.0

**Pull request closed without merging**
