### PR TITLE
[15.0][IMP] web_advanced_search: add legacy compability to avoid issues on pivot

### PR DESCRIPTION
**Pull request by yankinmax**
Steps to reproduce the issue:

1. Open on any model pivot view.
2. Try `Add custom filter`, for example choose `company` field -> any domain.
3. Get error `Uncaught Promise > Cannot find the definition of component "RecordPicker"`

https://user-images.githubusercontent.com/29202630/178727750-a7e036a3-f833-4d8b-aa9b-9f9dbdf03a36.mp4

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by yankinmax** [comment]
@pedrobaeza 
1. Open on any model pivot view.
2. Try `Add custom filter`, for example choose `company` field -> any domain.
3. Get error `Uncaught Promise > Cannot find the definition of component "RecordPicker"`

**Comment by pedrobaeza** [comment]
Thanks, please put that information on the commit message.

**Comment by yankinmax** [comment]
Yeah, I'm updating the description) I didn't expect so fast response on the PR.
And it's WIP.

**Comment by pedrobaeza** [comment]
I mean the commit message. I have put the PR as draft then. You are able to do that as well if this is not the final result.

**Comment by yankinmax** [comment]
@pedrobaeza put steps to reproduce on commit message, thx

**Comment by pedrobaeza** [comment]
Thanks. Tell me when this is ready to be reviewed.

**Comment by pedrobaeza** [comment]
Superseded by #2258

**Pull request closed without merging**
