### PR TITLE
[ADD] web_field_html_customizable

### PR DESCRIPTION
**Pull request by etobella**
Following the comments from #1921 I made new module

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by albariera — APPROVED** [review]

**Comment by etobella** [comment]
@OCA/web-maintainers This is approved. Might be able to merge this before github closes it?

**Comment by pedrobaeza** [comment]
The name should be `web_widget_html_auto_height`. I know you want this to be a potential container for other options, but this has not happened yet, and at the end, it's better to isolate things unless they are developed at once or makes sense to be together.

**Comment by etobella** [comment]
We are not currently using this module, and it was just an idea (I implement the necessary changes on my module). If it really has no interest, it has no sense to keep the PR as open (also, a lot of changes happens with the new html field, si I don't know if this has sense...)

**Pull request closed without merging**
