### PR TITLE
[16.0][FIX] web_responsive: Align menu for dates in filters

### LINKED ISSUE #2436: [16.0][BUG] web_responsive : menus for dates in filter show on top of opened menu
## Module
web_responsive

## Describe the bug
When clicking on Filters menu and selecting an existing filter with dates (meaning it opens a submenu for selecting granularity), the submenu is shown on top of the line (although after the text). 

Filters :
image

## To Reproduce
**Affected versions**: 16.0

1. Open CRM app (for instance, any object with predefined filter on date has the same behavior)
2. Click on filter, then select Creation Date > (or any Date filter)

**Expected behavior**
Submenu is expected to show on the right of the first level menu (after >), like it is done in Group by field (and by default in Odoo) :
Group by :
image

### PR DESCRIPTION
**Pull request by bvanjeelharia**
PR to resolve issue mentioned in https://github.com/OCA/web/issues/2436

### CODE REVIEW

**Comment by legalsylvain** [comment]
Fixes #2436


(note you can use this syntax to make this PR as a solution of the Issue). So once this PR is merged, the issue will be closed automatically.

**Comment by bvanjeelharia** [comment]
> Fixes #2436
> 
> (note you can use this syntax to make this PR as a solution of the Issue). So once this PR is merged, the issue will be closed automatically.

Ok, thanks for letting me know @legalsylvain

**Review by youring — COMMENTED** [review]
LGTM.

**Review by remi-filament — APPROVED** [review]
Tested OK on Runboat !

**Pull request merged**
