### PR TITLE
10.0 web confirm window close

### PR DESCRIPTION
**Pull request by StefanRijnhart**
I could not use the bus functionality anymore because that now uses async promises which don't work well with a synchronous event like beforeunload.

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Comment by guewen** [comment]
Code review LGTM, but on runbot it didn't seem to have any effect?

**Comment by StefanRijnhart** [comment]
@guewen seems to work for me. Note that Odoo only sets the 'dirty' flag when your focus leaves the field that you edited. It does not work when you close the window when your cursor is still in that field.

**Comment by StefanRijnhart** [comment]
Added the above as a Known issue in the README.rst.

**Review by legalsylvain — APPROVED** [review]
Thanks a lot @StefanRijnhart for porting this module.
code review. no test.

**Pull request merged**
