### PR TITLE
[16.0][MIG] web_company_color

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Comment by bobslee** [comment]
I tested on Odoo Enterprise 16.0.
The (company) colors don't appear.

**Comment by bobslee** [comment]
It works now. But I didn't reviewed the code.

**Review by antoniocanovas — APPROVED** [review]
Functional review Ok !!

**Review by atchuthan — APPROVED** [review]
Tested functionally

**Review by atchuthan — CHANGES_REQUESTED** [review]
We don't have commit history.
Please follow guidelines at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

**Comment by LoisRForgeFlow** [comment]
@Murtaza-OSI could you fix commit history and attend CI?

**Comment by LoisRForgeFlow** [comment]
I have superseded this PR to complete the migration respecting the commit history and fixing pre-commit errors. New PR is here https://github.com/OCA/web/pull/2527.

**Comment by pedrobaeza** [comment]
This one is incorrect about commit history, so closing.

**Pull request closed without merging**
