### PR TITLE
[17.0][MIG] web_group_expand

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by CRogos** [comment]
@sbidoul any idea why runboat is missing here?

**Comment by sbidoul** [comment]
The runboat build is [there](https://runboat.odoo-community.org/webui/builds.html?repo=oca/web&target_branch=17.0&pr=2863) but for some reason, the GitHub status API call failed with `This SHA and context has reached the maximum number of statuses`. No idea what this means for now.

**Comment by sbidoul** [comment]
This happens for all PRs. I suspect a GitHub issue. Will wait a bit to see if it resolves itself.

**Review by CRogos — APPROVED** [review]
Working fine.

Some of the commits in the history could be merged.
image

**Review by flotho — APPROVED** [review]
tested on runboat
LGTM

**Comment by astirpe** [comment]
Commits squashed, thanks!

**Comment by CRogos** [comment]
@pedrobaeza can you merge?

**Comment by pedrobaeza** [comment]
/ocabot migration web_group_expand

Merging following reviews:

/ocabot merge nobump

**Pull request merged**
