### PR TITLE
12.0 mig web drop target

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functiona test.

I notice only after a reload you see the attached file. Maybe it should be added in the Known issues. If not easily can be solved.

**Review by etobella — CHANGES_REQUESTED** [review]
Review why _onFileUploaded is not being called please

**Review by LoisRForgeFlow — APPROVED** [review]
Tested and it work perfectly in runbot (issues commented above are solved).  :+1: 

Thank you

**Pull request merged**
