### PR TITLE
[MIG] web_hide_db_manager_link: Migration to 11.0

### PR DESCRIPTION
**Pull request by JBF91**
Hi! I just had to do minor changes (utf-8, version number...) I think it's working properly.

### CODE REVIEW

**Comment by yajo** [comment]
Is this addon really needed? Check: https://github.com/odoo/odoo/blob/840e260794d0d495e4811b73064f5e755e213987/odoo/tools/config.py#L247-L250

**Comment by JBF91** [comment]
Well, apparently it's doesnt :sweat_smile: let's close this PR and add a comment in the migration issue so people will know this option.

Thanks @Yajo

**Comment by pedrobaeza** [comment]
You can add OpenUpgrade migration script for merging this module in base for better migration path.

**Comment by yajo** [comment]
Nice, closing then.

**Pull request closed without merging**
