### PR TITLE
[12.0][IMP] web_widget_one2many_product_picker: Prevent lost search input focus

### PR DESCRIPTION
**Pull request by Tardo**
cc @tecnativa TT27546

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I can't try in runbot, but is this really the expected behavior? I'm guessing reading code that this will return focus to text search after clicking on any button, but that includes the search button, which is not the desired behavior. Only clicking on rubber icon should do this, and note that when you do that, the focus can be in any other part.

**Comment by Tardo** [comment]
Now the focus of the "search input" is restored when:
- Click the "eraser" button (the rubber)
- ~~When press on search button~~ When the search is launched by pressing the enter key
- When changes the search mode (Search button dropdown options)

**Comment by pedrobaeza** [comment]
I think that when pressing search button, we shouldn't return the focus to the search input box, but only on the rest of cases you mention.

**Review by victoralmau — APPROVED** [review]

**Review by chienandalu — COMMENTED** [review]
Agreed. The second case makes no sense

**Comment by Tardo** [comment]
My fault. Second point is:
- When the search is launched by pressing the enter key

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
