### PR TITLE
[11.0][ADD] Enable multiselect and fixed time axis in timeline

### PR DESCRIPTION
**Pull request by tarteo**
This way you can select and move multiple items at once (using Ctrl key). This is a stock option of visjs.

http://visjs.org/docs/timeline/#Configuration_Options

image

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What happens with double click then (which currently edit the selected item)?

**Comment by tarteo** [comment]
@pedrobaeza If you double click with ctrl it deselects and selects it again. If you double click it (without ctrl pressed), it will deselect all the others (because ctrl is not pressed) and open the one you double clicked. Double clicking will not open all the selected onces. You can also select with shift which selects all items between 2 clicks if you double click while holding shift, it doesn't reset the selection and opens the double clicked item.

**Comment by pedrobaeza** [comment]
OK, that's great then. You are improving this view a lot.

**Review by simahawk — CHANGES_REQUESTED** [review]
LG. No mention of the feature in README?

**Review by pedrobaeza — APPROVED** [review]

**Comment by tarteo** [comment]
@simahawk There already was a mention in the README (see line 102).

I also added / fixed the functionality to add new records by dragging (using the Ctrl key)

**Comment by tarteo** [comment]
@simahawk Can you reconsider your review please? ☺️

**Review by simahawk — APPROVED** [review]

**Pull request merged**
