### PR TITLE
[15.0][MIG] web_pivot_computed_measure: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36578

Refactored to use OWL

git_computed_measure

ping @sergio-teruel @chienandalu

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]
Functional review

**Comment by CarlosRoca13** [comment]
I have added a new improvement to avoid searching for values using jquery but using the new feature that allows data-binding using state variables on js and t-model on xml

**Comment by CarlosRoca13** [comment]
> I have added a new improvement to avoid searching for values using jquery but using the new feature that allows data-binding using state variables on js and t-model on xml

Removed, because when testing it with tours @chienandalu and me found some incompatibility and it made us suspect that it is not fully implemented on 15.0, so we preffer to make the change when trying to migrate to 16.0

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
