### PR TITLE
[ADD] web_touchscreen: enable kanban sub-form views for tablets

### PR DESCRIPTION
**Pull request by yajo**
This module prefers kanban sub-form views when using a tablet, or any other device with a touch screen, no matter its size.

@moduon MT-4472

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review, 

image


LGTM, thank you @yajo

**Review by rafaelbn — APPROVED** [review]
👍🏼 let's go!

**Comment by arturoovf** [comment]
Hi, I don't get what this module is supposed to do? I tried with my iPad with this module installed and I didn't see any difference, can you provide an example where to appreciate the changes?  @yajo Thanks!

**Comment by Shide** [comment]
> Hi, I don't get what this module is supposed to do? I tried with my iPad with this module installed and I didn't see any difference, can you provide an example where to appreciate the changes? @yajo Thanks!

According to the comment in .js file:

> Create a new env that extends the original one but overrides the way Odoo considers this device small: it will be small if it has touch capabilities, not only if the screen is small. 
> In practice, this will make the inline subforms prefer the kanban mode if possible.

**Comment by yajo** [comment]
Before:
image


After:
image

**Comment by yajo** [comment]
I improved the readme in https://github.com/OCA/web/pull/2716

**Comment by arturoovf** [comment]
> Before: image
> 
> After: image

Thank you!

**Pull request merged**
