### PR TITLE
[13.0][MIG] web_widget_one2many_product_picker: Migration to 13.0

### PR DESCRIPTION
**Pull request by Tardo**
cc @tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include latest changes from 12.0 and check Travis.

**Comment by pedrobaeza** [comment]
I'm missing documentation for `name_search` option.

**Comment by Tardo** [comment]
@pedrobaeza Here is documented: https://github.com/OCA/web/pull/1858/files#diff-c2a870b37b6a1893b639e17182fa8b7c05035d33e9214ec6eadb74bf5b54c0e9R79

**Review by chienandalu — COMMENTED** [review]
Have you forwarded changes from #1879 #1912 and #1917 ?

**Review by pedrobaeza — APPROVED** [review]
Tested during several months in 2 customer instances, so it's stable enough. Please squash a bit commit history.

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
