### PR TITLE
[FIX][16.0] web_responsive: Fix UI title of task

### PR DESCRIPTION
**Pull request by tranngocson1996**
This PR
--------
Fix UI title of task
After:
aa

Before:
bb

### CODE REVIEW

**Comment by tranngocson1996** [comment]
@Tardo Please review.

**Comment by pedrobaeza** [comment]
It should put the ellipsis `…` there, isn't it?

**Comment by tranngocson1996** [comment]
> It should put the ellipsis `…` there, isn't it?

No, I mean the kanban status button is being hidden with the old scss. And the title is being shortened leading to the kanban status button hanging in the middle of the line

**Comment by pedrobaeza** [comment]
@tranngocson1996 can you fix pre-commit

**Comment by pedrobaeza** [comment]
Any news?

**Comment by tranngocson1996** [comment]
Hi @pedrobaeza 
I'm no longer interested in this PR; you can close it. Waiting nearly two years to fix a UI bug is too long for me. Thank you so much.

**Pull request closed without merging**
