### PR TITLE
[12.0][IMP] web_responsive: Bigger checkboxes in list view

### PR DESCRIPTION
**Pull request by Tardo**
big_checkboxes

Needs a fw-port after merging!

cc @tecnativa TT27826

### CODE REVIEW

**Comment by pedrobaeza** [comment]
They look a bit ugly... Can you check several things?:

- The border color is the same?
- Can you round a bit the corners?

**Review by legalsylvain — COMMENTED** [review]
Hi @tardo

Regarding the UX, your PR is cool. (=more easy to click on checkbox, that was before too small)
From an aesthetic point of view, I agree with @pedrobaeza, the border are too wide. 

image






image

thanks.

**Comment by Tardo** [comment]
Thanks. Yes... i'm trying to use "zoom" instead of "scale" to avoid 'pixelation'... but using zoom is a little more tedious because it changes the row height.

**Comment by Tardo** [comment]
Updated!
- No pixelation
- New border style

**Review by pedrobaeza — APPROVED** [review]
That's way better!

**Comment by legalsylvain** [comment]
Tested again.
From an aesthetic point of view, it's OK.
But the UX remains the same as before. (the button is not bigger, so there is a lot of space where it is possible to click without selecting).

Not a blocking point, though, just a remark.

image

kind regards.

**Comment by pedrobaeza** [comment]
Something weird is happening then, as that doesn't match with the initial screenshot. I made a code review though.

**Comment by Tardo** [comment]
Thanks @legalsylvain ... Appears that firefox doesn't like "zoom" property on checkboxes... :/

**Comment by legalsylvain** [comment]
> Thanks @legalsylvain ... Appears that firefox doesn't like "zoom" property on checkboxes... :/

Indeed : 
- Firefox : :-1: 
- Chromium : :+1:

**Comment by Tardo** [comment]
Updated!

big_checkboxes

**Review by legalsylvain — APPROVED** [review]
Thanks ! works like a charm on Firefox. (84.0.2)

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I think it's worth to check the before/after comparing them side by side for seeing that no extra height is consumed:

checkboxes

**Review by mamcode — APPROVED** [review]
LGTM :+1:

**Review by etobella — APPROVED** [review]
Awesome!!!

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Please fw-port it to v13

**Comment by legalsylvain** [comment]
Hi @Tardo 

I just checked in a tree view with the widget ``widget="boolean_toggle"``
without your commit. The display is OK.
image
with your commit, the display seems KO
image

Could you check if you have a similar problem ? 

thanks ! 

(Occures on Chromium and Firefox).

**Pull request merged**
