### PR TITLE
[12.0][FIX] web_widget_one2many_product_picker: auto save timer

### PR DESCRIPTION
**Pull request by Tardo**
backport #2185

cc @tecnativa TT35567

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Check Travis

**Comment by pedrobaeza** [comment]
Merging as well:

/ocabot merge patch

**Comment by pedrobaeza** [comment]
Please fix:
```
web_widget_one2many_product_picker/models/base.py:49:89: E501 line too long (95 > 88 characters)
web_widget_one2many_product_picker/models/base.py:54:89: E501 line too long (94 > 88 characters)
```

**Comment by dreispt** [comment]
Merged with #2828

**Pull request closed without merging**
