### PR TITLE
[14.0] [IMP] web_drop_target

### PR DESCRIPTION
**Pull request by etobella**
Apply improvements from 13.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm getting this weird drop box when the message is put as popup:

Selección_023

**Comment by etobella** [comment]
Ouch!!! You are right, the problem also happens on 13 :disappointed:  I will check how to solve it in all versions :wink:

**Comment by pedrobaeza** [comment]
Do you plan to fix the other comment?

**Comment by etobella** [comment]
I think it works fine @pedrobaeza

**Comment by pedrobaeza** [comment]
I mean the problem I depicted in https://github.com/OCA/web/pull/2066#issuecomment-955672542

**Comment by pedrobaeza** [comment]
Or do you prefer to merge this one and fw-port the other?

**Comment by etobella** [comment]
> I mean the problem I depicted in [#2066 (comment)](https://github.com/OCA/web/pull/2066#issuecomment-955672542)

Yes, it was solved on the last commit :wink: .

The right comment would be "I think it work fine with the last change"

**Comment by victoralmau** [comment]
Sorry @etobella finally, it's ready to review again and merge to unlock other PRs?

**Comment by etobella** [comment]
I think it is ready for review

**Review by victoralmau — APPROVED** [review]
Checked in runbot and it works as expected.

**Comment by pedrobaeza** [comment]
Merging, although I think there's one pending issue (for both 13.0 and 14.0):

/ocabot merge patch

**Pull request merged**
