### PR TITLE
[10.0][FIX] web_widget_bokeh_chart: force the version of bokeh when using pip

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
@sbidoul is this correct?

### CODE REVIEW

**Comment by sbidoul** [comment]
@lreficent the syntax is correct. But you should not pin a specific version. It's better to state a minimum version (>=0.12.7 for instance). Otherwise if another part of a project requires a more recent version of bokeh, you will have conflict.

**Comment by LoisRForgeFlow** [comment]
@sbidoul The problem is that this module specifically uses the 0.12.7 version ([see libraries on the addon](https://github.com/OCA/web/tree/10.0/web_widget_bokeh_chart/static/src/lib/bokeh)). So when installing ddmrp using pip, the version installed is the latest (I think 0.12.14 or so) and the bokeh charts fail.

**Comment by sbidoul** [comment]
Ah I see. In this case, ideally you should "vendor" the python part like you do with the js part. 

BTW, do you really need to include the js part in the Odoo addon? I thought bokeh was generating self contained js snippets to include in pages.

**Comment by LoisRForgeFlow** [comment]
What do you mean with "vendor"?

Well, that was a fair point. Just locally tested, it seems that they are required.

**Comment by sbidoul** [comment]
> What do you mean with "vendor"?

include the bokeh lpython lib inside the module in a sub namespace of `odoo.addons.web_widget_bokeh_chart`: not easy to do, probably.

**Comment by sbidoul** [comment]
When I generate an HTML chart with bokeh, I get something like this in the HTML headers:

image

You should be able to do the same here.

**Comment by LoisRForgeFlow** [comment]
>include the bokeh lpython lib inside the module in a sub namespace of odoo.addons.web_widget_bokeh_chart: not easy to do, probably.

what would be the benefit of doing so instead of just forcing the version?

>When I generate an HTML chart with bokeh, I get something like this in the HTML headers:

The way we are using it on DDMRP the js is inserted inline. Something like:

```<div class="bk-root">
    <div class="bk-plotdiv" id="dab7b716-25b8-4321-9105-5aeae263fbb8"></div>
</div>
<script type="text/javascript">
    (function() {
  var fn = function() {
    Bokeh.safely(function() {
    (...)
     });
  };
  if (document.readyState != "loading") fn();
  else document.addEventListener("DOMContentLoaded", fn);
})();

</script>
```
We are using this method `from bokeh.embed import components` that after the "bokeh magic" return you the html div and js script in a html tag. Honestly didn't try other options, which one do you use?

**Comment by sbidoul** [comment]
Forcing the version will generate conflicts in bigger projects where bokeh would be used for something else.

> which one do you use

TBH I never mixed Odoo and bokeh in the same process so far.

**Comment by LoisRForgeFlow** [comment]
Oh, yes that is true. But it someone use a more recent version of bokeh within odoo, they should also make a similar module for the libraries, like `web_widget_bokeh_v12.14`. And that reminds me this issue: https://github.com/OCA/web/issues/842. The problem is there but the solution seems not easy :sweat_smile:

**Comment by hbrunn** [comment]
is this PR also the right place to fix https://travis-ci.org/OCA/web/jobs/350784115#L607-L614 (that's a bokeh dependency if I read teh buid correctly) or is this a general travis problem?

**Comment by sbidoul** [comment]
@hbrunn the default python 2.7.6 used by travis is getting pretty old, could you try using 

```yaml
python:
  - "2.7.13"
```
in travis.yml?

**Comment by LoisRForgeFlow** [comment]
@hbrunn @sbidoul I opened an issue some days ago for that problem: https://github.com/OCA/web/issues/893

**Comment by hbrunn** [comment]
this one nearly drove me crazy, but with https://github.com/OCA/web/pull/907/commits/606158d02316f7d58c504b488346e703e5a7afbb, the build only crashes on 'normal' stuff. I'd suggest we go with this for the time being for 9, as the issue https://github.com/travis-ci/travis-ci/issues/8097 seems to be quite old; cf https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2

Don't remember why we want system site packages in the first place.

**Comment by sbidoul** [comment]
> Don't remember why we want system site packages in the first place.

I think it was to get the apt installed lxml because compiling it was slow. Now that pypi has a binary wheel for it its not necessary anymore.

**Comment by hbrunn** [comment]
https://github.com/OCA/web/pull/909

**Comment by MiquelRForgeFlow** [comment]
@lreficent could you rebase?

**Pull request closed without merging**
