### PR TITLE
[16.0][MIG] web_time_range_menu_custom: Migration to 16.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT50727

ping @pilarvargas-tecnativa @chienandalu

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @CarlosRoca13 : On the runboat, I'm not sure to understand what is the feature added. Could you elaborate  in a usage.rst function the way to use it ? and ideally a print screen ? Thanks !

**Comment by CarlosRoca13** [comment]
Added usage and here you have a gif to see the result:

example adding filters

**Comment by legalsylvain** [comment]
Thanks a lot ! it's very clear !

**Review by chienandalu — APPROVED** [review]
Working ok :+1: thanks :)

**Review by pilarvargas-tecnativa — APPROVED** [review]

**Pull request merged**
