### PR TITLE
web_company_color: change odoo color by variables

### PR DESCRIPTION
**Pull request by DonatasV**
Before this PR, the colors are changes only on navbar and with custom scss. 
After this PR is changed odoo variables, so color changes in all system

### CODE REVIEW

**Comment by pedrobaeza** [comment]
So does it mean that reports are also affected by this color change?

**Comment by DonatasV** [comment]
I just checked and yes, reports are also affected by this color

**Comment by pedrobaeza** [comment]
Then I don't think it's a good idea.

**Comment by gaikaz** [comment]
@pedrobaeza Before finding how well changing the primary color variable works for changing all the interface colors, @DonatasV also had made an extended version of this module, where it simply changed all places one by one overriding them, the way the module does it for the navbar. But the solution doesn't feel very elegant.

Now I'm wondering, do you agree with the general idea of extending this module to colorize more of the UI?
Assuming, it doesn't affect the reports (though honestly, the standard reports look pretty nice colored like that).

**Comment by pedrobaeza** [comment]
Well, I'm not really comfortable with something that modifies the visual ergonomics of your system through a user color pick. One thing is to modify the navbar, which is for highlighting something, and another that touches a lot of things.

Why don't you see how Odoo has implemented this in v13, that offers the same kind of feature?

**Comment by gaikaz** [comment]
Changing the SCSS variable like this PR does works really well. The color pick field should probably be considered technical and only available for admins, yet it doesn't require much designer knowledge to make the whole interface look and feel more personalized for the company. Say company's branding color is green, just by picking similarly shaded green to Odoo's purple, the result could be:
image
This screenshot is from PR's runbot instance. If by any chance this is interesting, please do play around with it. 

Just an idea, but what if the module would try and suggest a more fitting shade of the color chosen?

I will do check v13 implementation. Didn't know it now has something like that. :+1:

**Pull request closed without merging**
