### PR TITLE
[15.0][MIG] web_widget_char_size: Migration to 15.0

### PR DESCRIPTION
**Pull request by BankyKmitl**

### CODE REVIEW

**Review by tarteo — CHANGES_REQUESTED** [review]
Tested locally. Doesn't seem to work:

I've set the option in the view:
image

But I can enter more than 10 characters:
image

Attribute maxlength is not applied:
image

**Comment by BankyKmitl** [comment]
fixed

**Review by tarteo — APPROVED** [review]
It works now. Thanks for your contributions.

**Comment by BankyKmitl** [comment]
@pedrobaeza Could you check this for a merge?

**Review by dreispt — APPROVED** [review]

**Pull request merged**
