### PR TITLE
[ADD] web_field_required_invisible_manager

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
This module allows to set a field required or invisible for users belonging to a specific group.

The field can be required or invisible in any case, or according to specific conditions.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

**Review by geomer198 — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/web-maintainers opinions on this one?

**Comment by hbrunn** [comment]
for <16, you can create the same effect with a view override restricted to some group

**Comment by francesco-ooops** [comment]
@hbrunn do you think this version is ok for v14?

**Comment by hbrunn** [comment]
I won't spend time reviewing this, but won't object it either

**Comment by francesco-ooops** [comment]
fair enough 👍

**Comment by francesco-ooops** [comment]
@OCA/web-maintainers review please?

**Review by GSLabIt — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@simahawk can I request a review? :)

**Comment by francesco-ooops** [comment]
@simahawk ping :)

**Comment by francesco-ooops** [comment]
@OCA/web-maintainers hi, this PR has been approved both technically and functionally, could you please check it?

Thank you

**Comment by francesco-ooops** [comment]
@pedrobaeza resorting to you 🙏

**Pull request merged**
