### PR TITLE
[MIG][12.0] web_widget_image_webcam

### PR DESCRIPTION
**Pull request by ivantodorovich**
This PR is continuing the work in https://github.com/OCA/web/pull/964 and migrating to `12.0`

ping @bud-e

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi.  @ivantodorovich. 
First thanks for porting this module.

Just made a test on runbot and it works.
However, it is using flask Adobe Flash Player. Not sure to understand, it's because runbot is not using https ?

**Comment by ivantodorovich** [comment]
> Hi. @ivantodorovich.
> First thanks for porting this module.
> 
> Just made a test on runbot and it works.
> However, it is using flask Adobe Flash Player. Not sure to understand, it's because runbot is not using https ?

Yes, it's because of runbot not using https. I've tested it with https:
httpshtml


To be honest I've just picked up @bud-e 's work on https://github.com/OCA/web/pull/964, and migrated the relevant code to `12.0`. Didn't have to change anything on js code :sweat_smile:

**Review by mamcode — APPROVED** [review]
Looks good to me! Good job.

**Review by bud-e — APPROVED** [review]
LGTM

**Comment by ivantodorovich** [comment]
Can we merge this one? :)

**Comment by ivantodorovich** [comment]
https://github.com/OCA/web/pull/964 is also ready IMO.
I've just migrated on top of @bud-e 's work here.

@legalsylvain maybe you can approve his PR for 11.0 as well?

**Comment by ivantodorovich** [comment]
@OCA/web-maintainers can we merge this one?

**Comment by ivantodorovich** [comment]
thanks @pedrobaeza :heart:

**Comment by pedrobaeza** [comment]
Not sure which is the problem, but I'm going to merge directly.

**Pull request merged**
