### PR TITLE
[15.0][MIG] web_widget_dropdown_dynamic: Migration to 15.0

### PR DESCRIPTION
**Pull request by BankyKmitl**

### CODE REVIEW

**Comment by HaraldPanten** [comment]
@BankyKmitl could you rebase?

THX.

**Review by HaraldPanten — APPROVED** [review]
@rafaelbn @Yajo We've been checking this PR in our environment and seems that the migration has been done properly.

Could you review, please?

THX.

**Review by yajo — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by HaraldPanten** [comment]
Do you mind merging this one, @Yajo ? Then we will go for others that depend on it 👍

THX!

**Pull request merged**
