### PR TITLE
[14.0] [mig] web_widget_many2one_simple

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
LGTM :+1:

**Comment by fshah-initos** [comment]
It would be nice if we get the reviews here

**Comment by hkapatel-initos** [comment]
It would be nice if we get the reviews here

**Comment by hkapatel-initos** [comment]
It will be nice if someone gets the reviews here.

**Comment by pedrobaeza** [comment]
Why don't you review other PRs and ask in exchange to review this one? It's the usual flow in OCA.

**Comment by hkapatel-initos** [comment]
Hello, @etobella it would be nice if you add a review here.

**Comment by hkapatel-initos** [comment]
It will be nice if someone gets the reviews here.

**Comment by hkapatel-initos** [comment]
@Tardo and @victoralmau it would be great if you both add a review here.

**Comment by hkapatel-initos** [comment]
It will be nice if someone add a reviews here.

**Review by Tardo — APPROVED** [review]
LGTM :+1:

**Pull request merged**
