### PR TITLE
[MIG] web_tree_dynamic_colored_field: Migration to 15.0

### PR DESCRIPTION
**Pull request by amh-mw**

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @amh-mw. thanks for porting this module.
could you cherry-pick that commits ? https://github.com/OCA/web/pull/1950

otherwise, LGTM. (diff review / no test).

thanks !

**Review by legalsylvain — APPROVED** [review]
thanks ! 
(note : you should rerun ``pre-commit run -a`` to make CI green).

**Comment by amh-mw** [comment]
Build is failing with
`/bin/bash: /.repo_requirements/virtualenv/python3.8/bin/activate: No such file or directory`

**Comment by amh-mw** [comment]
Build was red for Runbot, but is now green for Runboat. Must have failed in the gap between.

**Comment by pedrobaeza** [comment]
https://odoo-community.org/blog/the-oca-blog-1/post/goodbye-runbot-welcome-runboat-116

**Comment by amh-mw** [comment]
Merge?

**Comment by square-ava** [comment]
@pedrobaeza Could this be merged ?

**Comment by pedrobaeza** [comment]
> @pedrobaeza Could this be merged ?

No, it requires at least 2 approvals, and one of them should be from a PSC (Sylvain is in this case).

**Comment by amh-mw** [comment]
@pedrobaeza Given that @legalsylvain has already approved this pull request, what would be the least obnoxious way to get a second approval? It's the eight month anniversary of my opening of this pull request, so I would expect it to be born by next month. 😄

**Comment by amh-mw** [comment]
@pedrobaeza @legalsylvain Scratch that, I re-read https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review and realized that I had been under the mistaken assumption that maintainers were responsible for code reviews. I'll see about reviewing some other pull requests in the repositories that I use and requesting reciprocity. RTFM @amh-mw

**Comment by pedrobaeza** [comment]
Hi, Adam, yes, you can get traction and more reciprocity when doing more activity apart from proposing pull request. Putting the first stone for your thousands of future contributions, hehe, I will approve and merge this when you reorder the commits to have the latest 2 with pre-commit stuff and then the migration one. That can be done for example using `git rebase -i origin/15.0` being `origin` the OCA remote, and then changing the lines with the proper commit order and maybe solving conflict problems. Please try and tell us back.

**Comment by amh-mw** [comment]
@pedrobaeza 🟢

**Comment by pedrobaeza** [comment]
Thanks

/ocabot merge nobump

**Pull request merged**
