### PR TITLE
[FIX] web_responsive : fixed the issue of fullscreen

### LINKED ISSUE #859: [10.0] web_responsibe - Attendance Kiosk Mode won't go full page
Hi!,

Odoo 10 - https://github.com/odoo/odoo/commit/66e76d681d41b6c007a0394b078ddbe872989985
web_responsibe - https://github.com/OCA/web/commit/8a3afd4173f4c7a3e16d11a93bf96229d3a286b7

When installing the attendance app/module, if we launch the Kiosk Mode.
The top header menu bar won't go away, I've looked for and seems like the page should become a full page with no other way to manipulate the site as for a closer behavior of a kiosk mode.

Here my only evidence where I can base this thought.
https://youtu.be/m9Nbv2Xl12k?t=22s

Here the actual result:
kioskmode

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**
Fixes #859

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Functional and code review

**Comment by pedrobaeza** [comment]
Please change module version number

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot.

**Comment by pedrobaeza** [comment]
Can you please propose the patch for v9 and v11?

**Comment by JayVora-SerpentCS** [comment]
Sure, will do soonest.

**Pull request merged**
