### PR TITLE
[MIG][13.0] web_tree_dynamic_colored_field

### PR DESCRIPTION
**Pull request by guewen**
**Important:** I removed the support of the `colors` attribute on the `<tree>` element as Odoo removed the attribute from the RelaxNG schema and didn't found a good alternative yet, see https://github.com/OCA/web/issues/1479 for discussing this issue.

### CODE REVIEW

**Comment by simahawk** [comment]
@guewen can you add relevant info into ROADMAP?

**Comment by guewen** [comment]
@simahawk good call, done

**Review by simahawk — APPROVED** [review]
@guewen can you squash your commits?

**Comment by simahawk** [comment]
ah #1499 has been  merged. Maybe worth to rebase and run pre-commit here.

**Comment by guewen** [comment]
Pre-commit fails to install :-(

```
INFO:pre_commit:This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/gbaconnier/.cache/pre-commit/repob0f5lduc/node_env-default/bin/node', '/home/gbaconnier/.cache/pre-commit/repob0f5lduc/node_env-default/bin/npm', 'install', '-g', '.')
return code: 254
expected return code: 0
stdout: (none)
stderr:
    npm WARN angular-estree-parser@1.1.5 requires a peer of @angular/compiler@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

    npm ERR! code ENOENT
    npm ERR! syscall chmod
    npm ERR! path /home/gbaconnier/.cache/pre-commit/repob0f5lduc/node_env-default/lib/node_modules/prettier/bin/prettier.js
    npm ERR! errno -2
    npm ERR! enoent ENOENT: no such file or directory, chmod '/home/gbaconnier/.cache/pre-commit/repob0f5lduc/node_env-default/lib/node_modules/prettier/bin/prettier.js'
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/gbaconnier/.npm/_logs/2020-01-31T06_40_28_579Z-debug.log
```

**Comment by guewen** [comment]
For now I squashed but not rebased due to my issue with pre-commit.

**Comment by guewen** [comment]
Rebased, run the new pre-commit config and fixed the js errors/warnings.

**Review by grindtildeath — APPROVED** [review]
LGTM :+1:

**Pull request merged**
