### PR TITLE
[14.0][MIG] web_widget_image_download

### PR DESCRIPTION
**Pull request by Peerapong-Supasompob**
Standard Migration.

### CODE REVIEW

**Review by etobella — APPROVED** [review]
No major changes

**Comment by Peerapong-Supasompob** [comment]
@etobella 
Thank you for your review

**Comment by Peerapong-Supasompob** [comment]
Do I need to do anything more to get this PR merge?

I'm just using mig module for the first time.

**Comment by kittiu** [comment]
Just some hint. Normally I will just delete the file README.rst and index.html as they will be generated automatically from files in readme folder once it is merged.

Note: some time it take a while to get merged. No worry, meanwhile we can use it as a PR.

**Comment by kittiu** [comment]
You might be interested to learn this tools so you can use the unmerged PR in your project 

https://github.com/acsone/git-aggregator

Many if us using it :)

**Comment by Peerapong-Supasompob** [comment]
@kittiu 

thank you

**Comment by kittiu** [comment]
You wrongly add yourself name into another module.
web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.rst 

By the way, as people in OCA are discussing whether we should add our name on CONTRIBUTORS.rst, we think that if we have something that we contribute, i.e., fixing lines of code, then it is OK. So, it is up to you to decide na.

**Comment by Peerapong-Supasompob** [comment]
> You wrongly add yourself name into another module.
> 
> web_widget_x2many_2d_matrix/readme/CONTRIBUTORS.rst 
> 
> 
> 
> By the way, as people in OCA are discussing whether we should add our name on CONTRIBUTORS.rst, we think that if we have something that we contribute, i.e., fixing lines of code, then it is OK. So, it is up to you to decide na.

I'm sorry, I updated the code to the wrong module, I'll fix it.

**Comment by Peerapong-Supasompob** [comment]
@kittiu 
Thank you for your review.
I fixed CONTRIBUTORS.rst Done.

**Review by kittiu — APPROVED** [review]

**Review by manuelregidor — APPROVED** [review]
LGTM

**Pull request merged**
