### PR TITLE
[FIX] don't eval() json, but json.loads it

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
All data will come always as JSON then?

**Comment by hbrunn** [comment]
Yes, it's a javascript-style domain json.stringified: https://github.com/OCA/web/blob/7.0/web_advanced_filters/static/src/js/web_advanced_filters.js#L250

**Comment by pedrobaeza** [comment]
:+1: 

Thanks.

**Comment by lmignon** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
