### PR TITLE
13.0 mig web widget color

### PR DESCRIPTION
**Pull request by vancouver29**
[13.0][MIG]web_widget_color

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This one also exists in core.

**Comment by vancouver29** [comment]
> This one also exists in core.

@pedrobaeza oh no! does this module also exist in core v14?

**Comment by pedrobaeza** [comment]
Yes, now it's a native widget.

**Comment by vancouver29** [comment]
> Yes, now it's a native widget.

ok, thanks! I will close this PR as well. Since it is a native core widget!

**Pull request closed without merging**
