### PR TITLE
web_last_viewed_records: add active_id to url

### PR DESCRIPTION
**Pull request by yelizariev**
This PR fixes issue, which can be reproduce as follows:
- install project module
- open project settings
- click on Tasks smart button
- open some task
- Navigate to any place (e.g. Messaging, Settings)
- open a Task from last viewed records

You'll get client-side error.

So, some actions doesn't work without active_id

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by legalsylvain** [comment]
Hi @yelizariev Thanks for your fix. Could you send your CLA please ?
Kind regards.

**Comment by OSguard** [comment]
:+1:

**Comment by yelizariev** [comment]
@legalsylvain CLA is sent

**Comment by legalsylvain** [comment]
Thanks.

**Pull request merged**
