### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/OCA/web/ci/#badges) to your project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/OCA/web).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi @xcorail, thanks for this,

I'm not sure if the general language alerts are suitable for this kind of project, as it uses an specific JS framework + Python ORM, so most of them are due to these uses. Can you configure them?

We also have a warning system through Travis builds (impacting on the build result). Do you have something similar, or is it only badges?

**Comment by xcorail** [comment]
Hi @pedrobaeza 

> I'm not sure if the general language alerts are suitable for this kind of project, as it uses an specific JS framework + Python ORM, so most of them are due to these uses. Can you configure them?

You can
* exclude some queries from the analysis, by adding a lgtm.yml file with these exclusions, as explained [here](https://lgtm.com/help/lgtm/showing-hiding-query-results)
* suppress some alerts in specific parts of the code with `//lgtm` comments, as explained [here](https://lgtm.com/help/lgtm/alert-suppression)
* contribute to [our open source queries](https://github.com/Semmle/ql), and write some queries that are fit to your use, after [learning](https://lgtm.com/help/ql/introduction-to-ql) the QL query language
* and of course report the false positives that you may find  

> Do you have something similar, or is it only badges?

Our recommended usage is indeed to activate Pull Request integration. LGTM will report any new problem (or fix), directly within the PR, and can even block the merge. This is a [one click operation](https://lgtm.com/projects/g/OCA/web/ci/)

Hope it's clearer, let me know

**Comment by thomaspaulb** [comment]
@xcorail, writing code quality checks from scratch in QL is very tedious, and a duplicate effort because a whole lot of useful code checks are already done by "PyLint-odoo" and the running of unit tests. 

However, checking the result of those requires rummaging through the logs and is not very visually attractive.

Just from the top of my head, but could we use your badges to write QL to check the output of Travis, and point people directly to the relevant lines that have issues? (By clicking one of several displayed badges?)

**Comment by xcorail** [comment]
Hi @thomaspaulb 

> writing code quality checks from scratch in QL is very tedious, and a duplicate effort because a whole lot of useful code checks are already done by "PyLint-odoo" and the running of unit tests.

I understand. We want to integrate LGTM more with frameworks, natively, in the near future. We planned some effort in this Q4 quarter roadmap for this. I don't know however if odoo is at the top of the list, and the effort just starts now, so I cannot tell you more. 
Another thing: there are lots of good linters, that are very useful, especially at code writing time. LGTM is more useful for deeper analysis, requiring some extensive control-flow analysis, and of course more time and memory. A linter or a unit test cannot cover these problems. So the idea would be to write the queries for problems who are **not** detected by the linters, and not to duplicate the effort.     

> Just from the top of my head, but could we use your badges to write QL to check the output of Travis, and point people directly to the relevant lines that have issues? (By clicking one of several displayed badges?)

Technically yes, but it would be overkill IMO. Our tool hooks into the compilation to create an AST and save this data into a DB, that can be queried later on. In your case, you won't need any of this, as you will just "read" from the Travis report (XML, JSON ...) and create a LGTM alert for each item, with the difficulty of linking it to the right line of code (difficulty that doesn't go away as you need to read this from the Travis report anyways). So I think LGTM and QL won't bring a lot of value here.

**Comment by thomaspaulb** [comment]
Thanks for the explanation, it's very interesting. So perhaps not for now, but we could reopen this in the future?

**Comment by xcorail** [comment]
Hi @thomaspaulb 

Sure, I'd recommend to 
* close this PR for now, 
* continue to have a look at the LGTM alerts, that are always there for you for free (repo polled once a day), 
* voice your suggestion of handling natively the odoo framework [here](https://discuss.lgtm.com/c/suggestions-and-feedback), with examples of false positive or of queries that need adaptation.

Cheers, and thanks for your feedback.

**Pull request closed without merging**
