### PR TITLE
[17.0] [MIG] web_notify

### PR DESCRIPTION
**Pull request by Nikul-OSI**

### CODE REVIEW

**Comment by Nikul-OSI** [comment]
Hii @lmignon @pedrobaeza Can you please review this PR?

**Comment by pedrobaeza** [comment]
/ocabot migration web_notify

I don't know enough about the module itself.

**Comment by Nikul-OSI** [comment]
@shepilov-vladislav @kevinkhao @chienandalu Can you please take a look?

**Comment by lmignon** [comment]
@Nikul-OSI Why are all the commit prefixed with `[PATCH X/Y]`? Can we avoid this prefix?

**Comment by Nikul-OSI** [comment]
> commit prefixed with `[PATCH X/Y]`

@lmignon  I captured only preserve history, I don't why it happens.

Using **git format-patch --stdout origin/17_mig_nc_web_notify..ups/16.0 -- web_notify | git am -3 --keep**

same commend I used others repo. too, but not add prefixed.

**Review by shepilov-vladislav — APPROVED** [review]

**Comment by Nikul-OSI** [comment]
> @Nikul-OSI Why are all the commit prefixed with `[PATCH X/Y]`? Can we avoid this prefix?

Fixed Prefix, Ready to review.

**Comment by kobros-tech** [comment]
I can review and contribute as I have made the same upgrade to version 17, but people in OCA sent me this PR so it is better to cooperate to publish it.

I checked all parts that need to be modified in order to make the upgrade successful, and I see they are met.

if the author @Nikul-OSI  needs to recheck or inspect my upgrade, here is my module:

[https://github.com/kobros-tech/web_notify/tree/main](https://github.com/kobros-tech/web_notify/tree/main)

**Comment by lbisiach** [comment]
@Nikul-OSI Do you estimate when you are going to close this PR ?

**Comment by Nikul-OSI** [comment]
> @Nikul-OSI Do you estimate when you are going to close this PR ?

Yes, I reviewed, can you please create new PR. Thank you

**Review by nguyenminhchien — CHANGES_REQUESTED** [review]
- UI tests: ok
- But, need to move the pre-commit stuff into another commit: `[IMP] $module: pre-commit auto fixes`. Fyi, https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#tasks-to-do-in-the-migration

**Review by chienandalu — CHANGES_REQUESTED** [review]
Code review ok. However, apply the requested guidelines so its correct in form

**Comment by pedrobaeza** [comment]
Superseded by #2948

**Pull request closed without merging**
