### PR TITLE
[17.0] mig web chatter position

### PR DESCRIPTION
**Pull request by tva-subteno-it**
This a fork from [2833](https://github.com/OCA/web/pull/2833)

I know there is another PR currently opened ([2893](https://github.com/OCA/web/pull/2893)) but this one doesn't seem to work. On the other hand, the original PR (2833) was working fine. So not knowing why the second one was created, and being in the urge to migrate this module for a customer, I'm opening this PR and letting you decide which one works best for you.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Could you fix precommit errors ?

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by antoniocanovas — APPROVED** [review]
Functional review ok !!

**Comment by tva-subteno-it** [comment]
Hello everyone, this PR was created because the other PR (#2893) was not ready. But I think it is now. So if anyone of you has the opportunity to do so, can you go check this one out, for the code review, and merge it when ready?
Thanks in advance.

**Comment by yajo** [comment]
Superseded by https://github.com/OCA/web/pull/2893.

**Pull request closed without merging**
