### PR TITLE
[14.0] [MIG] web_widget_open_tab: Migration to 14.0

### PR DESCRIPTION
**Pull request by rven**

### CODE REVIEW

**Review by BT-aestebanez — APPROVED** [review]
LGTM

**Comment by rven** [comment]
Fixed pre-commit errors by rebasing branch with latest 14.0 changes.

**Review by etobella — APPROVED** [review]
LGTM

**Comment by clementmbr** [comment]
Hi @rven @etobella,
What is needed for this PR to be merged ?

**Comment by etobella** [comment]
@OCA/web-maintainers might be possible to merge as it has two reviews?

**Pull request merged**
