### PR TITLE
[IMP] web_company_color: Support button and link customizing

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not `[ADD]`, but `[IMP]`.

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
@pedrobaeza I only see additions ;-)

**Comment by pedrobaeza** [comment]
@StefanRijnhart @hbrunn `[ADD]` is for adding modules, not for adding things inside a module. If you add new features inside the same module, that's an improvement, so `[IMP]`.

**Comment by hbrunn** [comment]
I didn't want to start a discussion about this, but if you have such strong intuitions about this, please propose them to https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message - otherwise we discuss forever about this on different PRs

**Comment by pedrobaeza** [comment]
It's not my intuition. See in first place the initial message of such guidelines:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#1introduction

pointing to the Odoo ones, and there you can see such reference:

https://www.odoo.com/documentation/14.0/reference/guidelines.html#commit-message-structure

We can point directly in our guidelines if you prefer, and add `[MIG]` and other OCA specific codes.

**Comment by hbrunn** [comment]
I think we should point to this, because 'loosely based' tells us where the inspiration comes from, not that all or any of it applies.

Thanks for this link, I must admit it's a while ago I read the Odoo ones, and never came across this. I like uniformity even though I'd do this differently, so here we go: https://github.com/OCA/odoo-community.org/pull/61

**Review by etobella — APPROVED** [review]
LGTM :+1: Functional review

**Comment by StefanRijnhart** [comment]
Wut. OCA scripts depend on an unmaintained library from 2014? https://pypi.org/project/anybox.testing.openerp/#description

```
ERROR: Could not find a version that satisfies the requirement anybox.testing.openerp (from versions: none)
ERROR: No matching distribution found for anybox.testing.openerp
The command "pip install anybox.testing.openerp" failed and exited with 1 during .
```

**Comment by pedrobaeza** [comment]
The problem now is that Pypi is having problems (the same as certain parts in GitHub).

https://www.githubstatus.com/
https://status.python.org/

**Pull request merged**
