### PR TITLE
Fixed web_timeline.css

### PR DESCRIPTION
**Pull request by npiganeau**
CSS classes have changed with the updated version of vis.js

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the changes. Please bump module version number.

**Comment by npiganeau** [comment]
Done

**Review by pedrobaeza — APPROVED** [review]
@Yajo please review

**Review by yajo — APPROVED** [review]
Seems obvious while reading code, although I didn't do any functional tests.

**Pull request merged**
