### PR TITLE
[13.0][Migrate] web_export_view migrated 13.0

### PR DESCRIPTION
**Pull request by sinandurgut07**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

**Comment by StefanRijnhart** [comment]
Is this perhaps the same functionality as is now included in core Odoo? 
image showing the 'Export all' button in the upper right corner of the Odoo list view widget
When clicking this button, an XLSX file is fetched containing the records and the column layout from the current list view.

**Comment by StefanRijnhart** [comment]
Confirmed by Pedro's comment in the alternative PR

**Comment by pedrobaeza** [comment]
There are some slight differences:

- Odoo core feature exports also the group information. Very good to have it!
- Odoo core always export full available recordset, while OCA's module is only exporting the selection. One approach or the other is not better or worse. It's simply the way it works and you have to get used to.

**Pull request closed without merging**
