### PR TITLE
Use clickable icon for image also in form view

### PR DESCRIPTION
**Pull request by ghost**
Add the widget also with name "image_preview" and add a corresponding form view widget that will also show a clickable icon for preview.
The name change to "image_preview" allows the widget to be used in a tree view with inline form view, such that the form view will still show the clickable icon for preview, instead of the default behavior of showing the full size image for the form view "image" widget.

### CODE REVIEW

**Comment by ecino** [comment]
This is a good improvement :+1:

**Comment by pedrobaeza** [comment]
Please add the documentation for the new features on the README file.

**Comment by dreispt** [comment]
I'm not sure how this is used. I tried on runbot to click on a partner image and it did nothing. How can I see this working?

**Comment by ecino** [comment]
@pedrobaeza What this PR does is adding a widget "image_preview" that behaves like "image" except that it doesn't display the full image when entering editing mode (icon or thumbnail instead).

@dreispt To test this, you must have a tree view with a field that has attribute widget="image_preview". I think the module does not add any view so the runbot does not display it.

**Pull request closed without merging**
