### PR TITLE
[ADD] web_widget_embed: new module to display an embedded document in a form view

### PR DESCRIPTION
**Pull request by benwillig**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't it be `web_widget_embedded`?

**Comment by benwillig** [comment]
The HTML tag is named ```embed```.

**Comment by pedrobaeza** [comment]
OK then

**Comment by sudhir-erpharbor** [comment]
It would be better if you add sample code (example) to use the widget.
Would be best if you add the screenshots as well in the README file.

**Comment by bosd** [comment]
@benwillig Can you force push to create a new runboat?

**Pull request closed without merging**
