### PR TITLE
[12.0][ADD] Timeline view for Calendar

### PR DESCRIPTION
**Pull request by apineux**

### CODE REVIEW

**Comment by sbejaoui** [comment]
@apineux , thank you for this module.

I think this PR should be in [calendar](https://github.com/OCA/calendar/tree/12.0) repository.

**Comment by tarteo** [comment]
@apineux I agree with @sbejaoui

**Comment by Tardo** [comment]
@apineux Any news here?

**Comment by apineux** [comment]
@tarteo @sbejaoui @Tardo Replaced by https://github.com/OCA/calendar/pull/9

**Pull request closed without merging**
