### PR TITLE
[12.0][FIX] web_export_view: Remove newlines from fields having many2many_tags

### LINKED ISSUE #2012: [12.0] web_export_view: plenty of spaces and newlines when exporting Many2Many fields' values
Versions:
- [ ] 12.0

Tried on runbot:
Export a product line on Excel:
immagine
Result:
immagine
Expected:
immagine

### PR DESCRIPTION
**Pull request by SimoRubi**
Fix #2012

### CODE REVIEW

**Review by SimoneVagile — APPROVED** [review]
LGTM

**Comment by SimoRubi** [comment]
@OCA/web-maintainers can this be merged?
Thanks!

**Comment by SimoRubi** [comment]
@OCA/web-maintainers can someone have a look?
There is also a nice test in here, any feedback would be appreciated :)

**Comment by SimoRubi** [comment]
@OCA/web-maintainers can someone have a look? Thanks

**Review by simahawk — APPROVED** [review]
LG, only code review

**Pull request merged**
