### PR TITLE
[MIG] [9.0] Web widget text markdown migrate 90

### PR DESCRIPTION
**Pull request by njeudy**
- Update to 9.0 js compliant
- Use markdown-it for better plugin possibility
- Add new generic module web_widget_text_ace to enable ace editor in textarea
- Update and refactor this module
- Correct a bug with multiple markdown textarea in one form view.

### CODE REVIEW

**Comment by njeudy** [comment]
WIP: I began to refactor this and use ace editor with markdown syntaxe and some other clean addons.

**Comment by njeudy** [comment]
Hello. I completly refactor web_widget_text_markdown to use ace editor in edit mode.
- I add new dependancy to web_widget_text_ace, a generic module for ace editor enabled fields.

Sorry for the big rebase .. now it's clean to review

**Comment by njeudy** [comment]
@pedrobaeza ping

**Comment by pedrobaeza** [comment]
This one is very hard/big to review and I won't be able to do it in a month or so, so maybe others can do it.

**Comment by njeudy** [comment]
ci return error but I can not see what is the error ?

**Comment by lasley** [comment]
Hi @njeudy - Awesome submission, thank you!

I am going to take a crack at a review, but I cannot find notation as to which Ace version is being used in this module.

Would it be possible for you to notate this somewhere (not sure as to the SOP here, maybe one of the more experienced folks can jump in on this)? It seems that this is contained in the `jquery-ace.js` file in the Ace download, but that is outside of the library folder so didn't make it to this module.

This will assist in my review so that I can diff against the versions, but also when it comes time to upgrade the library core.

**Comment by v3ss0n** [comment]
anyone working on this?

**Comment by pedrobaeza** [comment]
@v3ss0n have you reviewed the module?

**Comment by v3ss0n** [comment]
i am also doing one my own.

**Comment by pedrobaeza** [comment]
Why are you developing a new one instead of using this and maybe finish it? That's against FLOSS philosophy and DRY principle I think.

**Comment by njeudy** [comment]
something to change ? or is it okay

in V10, odoo add ace support and use the same way I use here .. web_widget_text_ace and web_widget_text_markdown are used in production environnement for month. 

@lasley ace is included in web_widget_text_ace module and is 1.2.2

**Comment by njeudy** [comment]
I will push lastest code for web_widget_text_ace and web_widget_text_markdown tomorrow. I cleaned it.

**Comment by njeudy** [comment]
Ok update done.

**Comment by njeudy** [comment]
@pedrobaeza @lasley @v3ss0n please review it and I will push v10 version of it.

Thanks.

**Comment by yajo** [comment]
[Odoo 9 already includes ace](https://github.com/odoo/odoo/tree/9.0/addons/website/static/lib/ace), so please drop (or dramatically reduce) the `web_widget_text_ace` if possible.

**Comment by njeudy** [comment]
@Yajo sorry for the delay .. yes I will update for 9.0 and 10.0 using ace from odoo :)

**Comment by njeudy** [comment]
Close this one for now as I did work in sudokeys anymore and did work with V9 anymore .. Will rewrite markdown module for V11.

If someone want markdown in V9 ask, I will try to backport it.

**Pull request closed without merging**
