### PR TITLE
[FIX] web_responsive: fix hotkey combinations in a shortcut template

### PR DESCRIPTION
**Pull request by kos94ok-3D**
Before:
изображение

After:
изображение

Closed: #1469

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Can you avoid a total replacing so that you don't invalidate possible additions of extra modules?

**Comment by kos94ok-3D** [comment]
> Can you avoid a total replacing so that you don't invalidate possible additions of extra modules?

Is it ok?

**Review by pedrobaeza — APPROVED** [review]
Great, thanks!

**Review by Tardo — APPROVED** [review]
Thanks!

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza @Yajo I think this one should be forward-ported to V13, isn't it?

**Comment by pedrobaeza** [comment]
Yes, please. I think it's only cherry-picking the commit.

**Comment by Cedric-Pigeon** [comment]
ok thanks, we'll do in the next coming days.

**Pull request merged**
