### PR TITLE
[14.0][MIG] web_widget_url_advanced

### PR DESCRIPTION
**Pull request by Peerapong-Supasompob**
Standard Migration.

### CODE REVIEW

**Comment by kittiu** [comment]
Thanks for contributiing to OCA. Just FYI, you when doing migration, you can remove 1) README.rst and 2) index.html
It will be built back by what is in readme folder.

Normally, I will just remove them.

**Comment by Peerapong-Supasompob** [comment]
I run the file through the command oca-gen-addon-readme.

Usually 1) README.rst and 2) index.html, no need to commit to github, right?

please guide me.

**Comment by kittiu** [comment]
> I run the file through the command oca-gen-addon-readme.
> 
> Usually 1) README.rst and 2) index.html, no need to commit to github, right?
> 
> please guide me.

This oca-gen-addon-readme will be run auto when it gets merged. So it is not needed. In my personal opinion, it is better.

**Comment by Peerapong-Supasompob** [comment]
> > I run the file through the command oca-gen-addon-readme.
> > Usually 1) README.rst and 2) index.html, no need to commit to github, right?
> > please guide me.
> 
> This oca-gen-addon-readme will be run auto when it gets merged. So it is not needed. In my personal opinion, it is better.

thank you for suggest.

I've edited the commit as you suggested.

**Review by dsolanki-initos — APPROVED** [review]
No major change. Code review. LGTM

**Comment by simahawk** [comment]
please cherry-pick this fix https://github.com/OCA/web/pull/1918

**Comment by Peerapong-Supasompob** [comment]
> please cherry-pick this fix #1918

done.

**Comment by simahawk** [comment]
thanks but pre-commit complains :man_shrugging:

**Comment by Peerapong-Supasompob** [comment]
> thanks but pre-commit complains 🤷‍♂️

I have fixed the pre-commit error successfully, thanks.

**Review by simahawk — APPROVED** [review]

**Pull request merged**
