### PR TITLE
[16.0][MIG] web_search_with_and

### PR DESCRIPTION
**Pull request by Sandip-scs**

### CODE REVIEW

**Review by nicolascol — CHANGES_REQUESTED** [review]
Hi! Shift doesn't work to do filter AND. Tested in res.partner with field name

**Comment by Sandip-scs** [comment]
> Hi! Shift doesn't work to do filter AND. Tested in res.partner with field name

Please check with my latest commit, I have fixed the issue

**Comment by Sandip-scs** [comment]
@nicolascol Please check with my latest commit, I have fixed the issue

**Review by lmignon — APPROVED** [review]
LGTM (Code review + functional)

**Review by nicolascol — APPROVED** [review]
LGTM (review functional)
@Sandip-scs

**Comment by Sandip-scs** [comment]
> This PR has the `approved` label and has been created more than 5 days ago. It should therefore be ready to merge by a maintainer (or a PSC member if the concerned addon has no declared maintainer). robot

@OCA-git-bot Can you please merge this PR as this reviewed and approved

**Pull request merged**
