### PR TITLE
 [ADD][web_action_conditionable] support forms

### PR DESCRIPTION
**Pull request by hbrunn**
I added a few other improvements in separate commits, you'll see that in the messages

### CODE REVIEW

**Comment by tarteo** [comment]
@pankk

**Review by tarteo — CHANGES_REQUESTED** [review]
`<tree create="'some_group' in _group_refs">` in tree views doesn't hide the 'Create' button anymore.

**Comment by hbrunn** [comment]
@tarteo thanks, didn't consider this use case. Fixed and updated the readme accordingly

**Comment by tarteo** [comment]
The same case is for trees in form views.

**Comment by hbrunn** [comment]
I can't reproduce this locally, can you add an example on runbot?

**Comment by tarteo** [comment]
http://3360805-1205-62dbc4.runbot3.odoo-community.org/web?debug=1#id=3&view_type=form&model=res.groups&action=75

I've changed 

`                                <tree string="Access Rules" editable="top">
`

to

`                                <tree string="Access Rules" editable="top" create="'some_group' in _group_refs">
`

but I can still add items.

**Comment by hbrunn** [comment]
aha! you try this in a many2many field, I believe this never has worked: https://github.com/OCA/OCB/blob/8.0/addons/web/static/src/js/view_form.js#L5024

But simple to fix, so I just added that even though not in the scope of this PR.

**Review by tarteo — APPROVED** [review]
The previous worked with one2many and many2many fields on my local machine. But this is more clear. Thanks!

Can you increase the version number in the manifest.

**Review by tbaden — APPROVED** [review]
code review

**Comment by pedrobaeza** [comment]
@hbrunn can you squash commits at your taste?

**Comment by hbrunn** [comment]
@pedrobaeza done

**Pull request merged**
