### PR TITLE
[16.0][MIG] web_action_conditionable: Migration to 16.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Supersedes https://github.com/OCA/web/pull/2435

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Comment by andreschenkels** [comment]
Can we merge this?

**Comment by simahawk** [comment]
@andreschenkels  @miikanissi @Borruso FYI to speed up merges you could help w/ reviews. They can be technical but if you are not confident you can simply do functional reviews. These will be much appreciated! :wink:

**Review by simahawk — APPROVED** [review]
LG

**Comment by simahawk** [comment]
> /ocabot merge minor

bah bad command, I'm going to kill its build

**Pull request merged**
