### PR TITLE
Create tr.po

### PR DESCRIPTION
**Pull request by SalahAdDin**
Added Turkish language localization file.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use Weblate as already stated in previous PRs.

**Comment by SalahAdDin** [comment]
I cannot create new languages for translate in weblate and also i cannot translate, i already sent the mail to @oca-transbot, i'm waiting.

**Comment by pedrobaeza** [comment]
You were already notified about that (I personally did) that you need to login there. Now I see you have signed in, but not replied. I have added you to Turkish translators now and you should be able to do it.

**Comment by SalahAdDin** [comment]
But, i cannot add a new language, i don't know why.

**Comment by pedrobaeza** [comment]
On the bottom part of the resource, click on "Start new translation":

seleccion_012

**Comment by SalahAdDin** [comment]
bloqueado

https://translation.odoo-community.org/user/SalahAdDin/

**Comment by pedrobaeza** [comment]
Uhm... @sbidoul do you know why?

**Comment by SalahAdDin** [comment]
I'm still have this problem :-1:

**Comment by pedrobaeza** [comment]
Try now.

**Comment by SalahAdDin** [comment]
I still have the same problem, are you sure you gave me proper permissions?

**Comment by pedrobaeza** [comment]
You should try again cleaning cache, as other user reporting the same has told me that is now working.

**Comment by SalahAdDin** [comment]
Tested in a different browser: it stil does not work.

**Comment by SalahAdDin** [comment]
@pedrobaeza I tested it in Windows also, all browsers, and I cannot translate or ask for other languages.
What must I do for solving it?

For now, can you merge this pull request?

**Comment by SalahAdDin** [comment]
Nothing yet.

**Comment by pedrobaeza** [comment]
Sorry, but I have done all I can and it's working for the rest.

**Comment by SalahAdDin** [comment]
For now, it is enough if you reopen this pull request and merge it, Thank you.

**Comment by pedrobaeza** [comment]
Sorry, but we shouldn't make exceptions. You should fix on your part the Weblate part.

**Pull request closed without merging**
