### PR TITLE
[MIG 10.0] migrate m2x_options

### PR DESCRIPTION
**Pull request by jlzhou**
#435

### CODE REVIEW

**Comment by jlzhou** [comment]
There is an issue need help:

In ir/ir_ui_view.py file:
node.set('can_create', 'true' if Comodel.check_access_rights('create', raise_exception=False) else 'false')
node.set('can_write', 'true' if Comodel.check_access_rights('write', raise_exception=False) else 'false')

and then in form_common.js file:
var CompletionFieldMixin = {
    init: function() {
        this.limit = 7;
        this.orderer = new utils.DropMisordered();
        this.can_create = this.node.attrs.can_create || true;
        this.can_write = this.node.attrs.can_write || true;
    },
......

It seems can_create and can_write always returns true, I wonder if it is a bug?

I need this return value to change the visibility of "open" icon next to drop down.

**Review by lmignon — CHANGES_REQUESTED** [review]
@jlzhou Thank you for the contribution!
Nevertheless you need to forward port all the changes done on 9.0 since the creation of the 10.0 first...
Takes a look at  https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0 to know how you can proceed.

**Comment by jlzhou** [comment]
Sure, I have done this already. The PR is based on the latest code of 9.0 branch.

???? iPad

? 2016?11?15??23:15?Laurent Mignon (ACSONE) <notifications@github.com<mailto:notifications@github.com>> ???

@lmignon requested changes on this pull request.

@jlzhouhttps://github.com/jlzhou Thank you for the contribution!
Nevertheless you need to forward port all the changes done on 9.0 since the creation of the 10.0 first...
Takes a look at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0 to know how you can proceed.

##

**Comment by lmignon** [comment]
@jlzhou but the commit history seems to be not preserved and we must keep it. Am I wrong?

**Comment by jlzhou** [comment]
I just copy the m2x module code file from 9.0 to 10.0 branch, I do not familiar with git command.

???? iPad

? 2016?11?16??00:16?Laurent Mignon (ACSONE) <notifications@github.com<mailto:notifications@github.com>> ???

@jlzhouhttps://github.com/jlzhou but the commit history seems to be not preserved and we must keep it. Am I wrong?

##

**Comment by pedrobaeza** [comment]
You have to follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by jlzhou** [comment]
Do you mean the following steps?

Technical method to migrate a module from "9.0" to "10.0" branch
-   $REPO: the OCA repository hosting the module
-   $MODULE: the name of the module you want to migrate
-   $USER_ORG: your GitHub login or organization name

$ git clone https://github.com/OCA/$REPO -b 9.0 # optional if already existing
$ git remote update # optional if you have just cloned the repo
$ git checkout -b 10.0-mig-$MODULE origin/10.0
$ git format-patch --stdout origin/10.0..origin/9.0 -- $MODULE | git am -3
$ # Adapt the module to the 10.0 version and commit the changes
$ ...
$ git add --all
$ git commit -m "[MIG] $MODULE: Migrated to 10.0"
$ # optional if you already have your remote configured
$ git remote add $USER_ORG git@github.commailto:git@github.com:$USER_ORG/$REPO.git # This mode requires an SSH key in the GitHub account
$ ... or ....
$ git remote add $USER_ORG https://github.com/$USER_ORG/$REPO.git # This will required to enter user/password each time
$ # push the changes to GitHub and make the PR
$ git push $USER_ORG 10.0-mig-$MODULE --set-upstream

???? iPad

? 2016?11?16??00:21?Pedro M. Baeza <notifications@github.com<mailto:notifications@github.com>> ???

You have to follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

##

**Comment by pedrobaeza** [comment]
Yes, but as is a PR, the source branch should be the PR one.

**Pull request closed without merging**
