### PR TITLE
[15.0][ADD] web_filter_header_button: New module

### PR DESCRIPTION
**Pull request by chienandalu**
moved from https://github.com/OCA/server-ux/pull/840

This module allows to add some selected filters as buttons in the header control panel.

Peek 12-03-2024 13-50

cc @Tecnativa TT47127

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by sergio-teruel — APPROVED** [review]

**Comment by idamonli** [comment]
@chienandalu Request to migrate to odoo16

**Comment by chienandalu** [comment]
@idamonli sure! all yours :wink:

**Comment by sergio-teruel** [comment]
ping @CarlosRoca13 FYI!

**Pull request merged**
