### PR TITLE
[MIG][10.0] web ir actions act window page

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Review by yajo — APPROVED** [review]
Code review only

**Comment by JordiBForgeFlow** [comment]
Can you provide some use cases in the readme? It is hard to understand where can it be applied.

**Comment by StefanRijnhart** [comment]
@jbeficent done!

**Comment by JordiBForgeFlow** [comment]
@StefanRijnhart Thanks! It is much clearer now. Do you have an actual PR that implements this, to make the functional tests easier?

**Comment by StefanRijnhart** [comment]
No, sorry. That implementation is quite customer specific.

**Comment by pedrobaeza** [comment]
You can include as demo data an action + a button in for example res.users form view for trying out.

**Comment by StefanRijnhart** [comment]
@pedrobaeza you mean, add Python code just for testing? Not sure if that is a good idea.

**Comment by StefanRijnhart** [comment]
Managed to add a demo without code indeed.

image

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Technical and functional review. 
Thanks!!

**Review by pedrobaeza — APPROVED** [review]
Thanks for adding the demo part!

**Pull request merged**
