### PR TITLE
[Updated] Icons to match Odoo's design

### PR DESCRIPTION
**Pull request by jonisunz**
[Added] .svg file

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for all these icons for enriching current modules (and following my suggestions about SVG and the rest). About this one, I'm not sure this icon will be the most suitable for expressing the goal of this module. I think that a mobile + a window representation/ apps switcher icon or similar can fit better the features of the module, don't you think?

**Comment by jonisunz** [comment]
> I think that a mobile + a window representation/ apps switcher icon or similar can fit better the features of the module, don't you think?

Yes, that actually sounds right to me. Is this what you mean by app switcher icon?
image

**Comment by pedrobaeza** [comment]
I meant this AppSwitcher icon (that is a FontAwesome one):

Selección_015

https://fontawesome.com/icons/th-large?style=solid

**Review by bosd — APPROVED** [review]

**Review by bofiltd — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
See my comments

**Pull request closed without merging**
