### PR TITLE
[15.0][MIG] web_listview_range_select: Migration to 15.0 

### PR DESCRIPTION
**Pull request by theangryangel**
Straight forward migration from 14.0, seems to be working as-is. 

I'm not sure if we should look at converting into the Owl equivalent at this point or?

### CODE REVIEW

**Comment by manuelregidor** [comment]
LGTM

**Review by manuelregidor — APPROVED** [review]
LGTM

**Review by HaraldPanten — APPROVED** [review]
Functional review.

@pedrobaeza could you merge, please?

**Comment by HaraldPanten** [comment]
> /ocabot migration web_listview_range_select /ocabot merge nobump

THX! 👍

**Pull request merged**
