### PR TITLE
[15.0][FIX] Fix problem of blank page when using web_responsive

### PR DESCRIPTION
**Pull request by bvanjeelharia**
This PR should fix the error of blank page mentioned in https://github.com/OCA/web/issues/2410

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I have tested this PR, and it's still showing the AppSwitcher, but no icon shown. Maybe you misunderstood me when I refer to AppSwitcher. For me, that's not the button, but the app selector screen. I think you call it "Home screen". For me, the home screen is the one you select as initial action on the user.

And this is important, as we are losing this option since this version, as only if you know which is the action (and if there's a menu for it), you can access such initial action. Do you understand me?

**Comment by bvanjeelharia** [comment]
Yes @pedrobaeza , I got your point. I have made the changes likewise, please review it

**Review by pedrobaeza — APPROVED** [review]
Great! Tested on runboat and working.

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
