### PR TITLE
Added Groupby Expand feature

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**

### CODE REVIEW

**Comment by oihane** [comment]
I think this module has the same functionality as web_group_expand available in https://github.com/OCA/web/pull/201

**Comment by oihane** [comment]
Travis fails:

```
./web_groupby_expand/__init__.py:6:80: E501 line too long (92 > 79 characters)
./web_groupby_expand/__init__.py:23:66: W292 no newline at end of file
./web_groupby_expand/__openerp__.py:28:15: E203 whitespace before ':'
./web_groupby_expand/__openerp__.py:31:11: E203 whitespace before ':'
./web_groupby_expand/__openerp__.py:35:14: E201 whitespace after '['
./web_groupby_expand/__openerp__.py:35:53: E202 whitespace before ']'
./web_groupby_expand/__openerp__.py:39:66: W292 no newline at end of file
```

**Comment by oihane** [comment]
Add a README according OCA's template (https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst) explaining the usage of the module.

**Comment by ghost** [comment]
@oihane Great!
Seems We both eye the same functiionality.
I'll look at the #201 for sure! We did this long ago https://github.com/JayVora-SerpentCS/SerpentCS_Contributions-v8/tree/8.0/web_groupby_expand.
Hope the committer would have checked for the existence of similar functionality. 
#odoo is a great product and we have to combine the forces to reduce the duplicate efforts and thus making the @OCA stronger.

**Comment by LeartS** [comment]
I'm for using https://github.com/OCA/web/pull/201 as I think it's better written and uses much less code, but I think they ( @oihane ) should integrate the button design of this one: it looks better, uses the standard fontawesome, and a toggle icon makes more sense than two icons.

**Comment by pedrobaeza** [comment]
I have tried also both PRs, and I also prefer the other one, but the two button approach is needed, because you can fold in any moment although you haven't unfold all levels. About button appearance, @oihane has already worked on it, but she needs a little more work.

**Comment by pedrobaeza** [comment]
As the other PR has more support and has been merged, I close this one. Sorry for the double-work.

**Pull request closed without merging**
