### PR TITLE
[14.0][mig] web_search_with_and

### PR DESCRIPTION
**Pull request by koenloodts**

### CODE REVIEW

**Comment by keshrath** [comment]
image

**Review by fshah-initos — APPROVED** [review]
Code review. LGTM

**Comment by antoniocanovas** [comment]
Functional review failed.
It doesn't work as expected when pressing shift key.

**Comment by sviluppo-msa** [comment]
In V13 it worked overriding the  _onAutoCompleteSelected method of the search bar.
In V14 the search bar has been refactored and the _onAutoCompleteSelected method has completly gone, so overriding it does nothing :( .

**Comment by alessandro-fiorino** [comment]
In V13 it worked overriding the _onAutoCompleteSelected method of the search bar.
In V14 the search bar has been refactored and the _onAutoCompleteSelected method has completly gone, so overriding it does nothing :( .

**Pull request closed without merging**
