### PR TITLE
[17.0][FIX] web_responsive: Add support to serve menu icon in image url

### PR DESCRIPTION
**Pull request by kafai-lam**
Add support to serve menu icon in image URL format rather than base64.

It can take advantanges from browser caching and Nginx proxy.

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
LGTM, thanks

**Review by PaulGoubert — APPROVED** [review]
OK from my side

**Review by chienandalu — APPROVED** [review]
thanks :+1:

**Pull request merged**
