### PR TITLE
[15.0][MIG] web_send_message_popup: Migration to 15.0

### PR DESCRIPTION
**Pull request by Du-ma**
Migration to `15.0`.

There's already an active PR for this module #2300, but the dev seems to have forgotten about it or smth...
Anyways, came up with a more elegant solution as well as did my best to comment the code for other people that might be interested to migrate this module further.

### CODE REVIEW

**Comment by Du-ma** [comment]
@tarteo @hkapatel-initos @StephaneMangin 
Mind having a look bois?

**Comment by Du-ma** [comment]
@OCA/web-maintainers 
Yo, this PR looks submissive and merge-able :smirk:

**Comment by pedrobaeza** [comment]
You need at least two reviews. You can review other PRs and ask in exchange that they review yours.

**Review by gaikaz — APPROVED** [review]
Code review + functional review on Runboat
Works perfectly as expected 💯

**Review by NICO-SOLUTIONS — COMMENTED** [review]
functional review looks good

**Review by Dariosi — APPROVED** [review]
Looks good to me

**Comment by Du-ma** [comment]
@OCA/web-maintainers 
😏️😉️😉️

**Comment by pedrobaeza** [comment]
/ocabot merge web_send_message_popup
/ocabot merge nobump

Not sure why this one is not in OCA/social though.

**Comment by Du-ma** [comment]
True.
Thx @pedrobaeza i appreciate you man <3

**Pull request merged**
