### PR TITLE
[12.0][web_timeline] Fix bug from group_order: locale instead locate.

### PR DESCRIPTION
**Pull request by denislour**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@tarteo @Tardo can you confirm the validity of this?

**Comment by denislour** [comment]
Ref #1314

**Review by Tardo — APPROVED** [review]
Same fix as https://github.com/OCA/web/pull/1283

**Comment by pedrobaeza** [comment]
OK, I see. It has been a bad forward-port.

**Pull request closed without merging**
