### PR TITLE
[FIX] web_responsive: fix hotkey combinations in a shortcut template

### PR DESCRIPTION
**Pull request by benwillig**
Forward port of https://github.com/OCA/web/pull/1560

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please check Travis?

**Comment by Tardo** [comment]
@benwillig ping

**Review by yajo — CHANGES_REQUESTED** [review]
Fix travis please.

**Comment by Tardo** [comment]
The author of this PR is missing...

**Comment by pedrobaeza** [comment]
@Tardo maybe you can take over this PR

**Pull request closed without merging**
