### PR TITLE
8.0 web widget one2many tags empty field

### PR DESCRIPTION
**Pull request by codingforfun**
Provide well defined value for empty field. 
See discussion here: https://github.com/OCA/web/pull/319/files#r56142379

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
:+1:

**Comment by hbrunn** [comment]
you might add yourself as contributor, but I won't block the PR on this ;-)

**Comment by codingforfun** [comment]
ok, thx for reminding me ;-)

**Comment by codingforfun** [comment]
@hbrunn @pedrobaeza 
Do you understand why this fails? Am I able to do something about it?

**Comment by pedrobaeza** [comment]
It's a glitch of coveralls, that says -0.0% instead of 0.0%. No worry about this.

**Comment by ivantodorovich** [comment]
:+1:

**Pull request merged**
