### PR TITLE
[IMP] web_notify: Add possibility to return an action in a notification

### PR DESCRIPTION
**Pull request by IT-Ideas**
Backport of https://github.com/OCA/web/pull/2598

### CODE REVIEW

**Comment by IT-Ideas** [comment]
Hello @guewen I just back ported @rousseldenis PR.

**Comment by IT-Ideas** [comment]
@gurneyalex

**Review by chienandalu — APPROVED** [review]
Thanks :+1:

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge major

**Pull request merged**
