### PR TITLE
[16.0][MIG] web_chatter_position

### PR DESCRIPTION
**Pull request by BojanOD**
Migrate the web_chatter_position module from 15.0 to 16.0.

### CODE REVIEW

**Comment by yostashiro** [comment]
@BojanOD Thanks for the PR. Looks like the history is lost. Can you please follow the steps described in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0?

**Review by lmignon — CHANGES_REQUESTED** [review]
As mentioned in the previous comment, the history must be preserved. Moreover, the functionality provided by this addon doesn't work on runboat.

**Comment by BojanOD** [comment]
@lmignon @yostashiro I fixed the HISTORY issue can you review the PR.

**Review by lmignon — CHANGES_REQUESTED** [review]
Functionally if I click on the button or change my preference the chatter remains at the same place. (On runboat)

**Comment by BojanOD** [comment]
@lmignon 

Can you double check that it's working on my local instance also when I tried testing on runboat it seemed to be working there as well.

Here are video demonstrating that the functionality is working.

[Local Instance](https://user-images.githubusercontent.com/102147235/215044421-c270bc10-6286-414e-ad75-5712c58d567b.webm)
[Runboat](https://user-images.githubusercontent.com/102147235/215044437-3c1d3edc-58b3-4214-ab98-8e472d1144ce.webm)

**Comment by lmignon** [comment]
@BojanOD Indeed it work but only for small screen. I've to resize my browser to be smaller and once it's small enough, it start working. It would be nice to work in every cases or the button should disappear when it becomes without effect.

**Comment by florian-dacosta** [comment]
Hello @BojanOD Same issue here, it does not work when my browser is full screen, but it work when I downsize it.

**Comment by hoangtiendung070797** [comment]
> @lmignon
> 
> Can you double check that it's working on my local instance also when I tried testing on runboat it seemed to be working there as well.
> 
> Here are video demonstrating that the functionality is working.
> 
> [Local Instance](https://user-images.githubusercontent.com/102147235/215044421-c270bc10-6286-414e-ad75-5712c58d567b.webm) [Runboat](https://user-images.githubusercontent.com/102147235/215044437-3c1d3edc-58b3-4214-ab98-8e472d1144ce.webm)

@BojanOD I also have a similar problem. Maybe in your video, I noticed that your screen resolution is HD. I tried it in HD mode and it worked, but it doesn't work in full HD.

**Comment by anhvu-sg** [comment]
yeah, it does not work with large screen such as 2k 4k

**Comment by miguel-S73** [comment]
@BojanOD I have reproduced this issue https://github.com/OCA/web/issues/2464
Can you try fix this?

**Comment by andreampiovesana** [comment]
no news?

**Comment by vincent-hatakeyama** [comment]
The migration from #2419 has been merged instead of this one.

**Pull request closed without merging**
