### PR TITLE
[12.0][IMP] web_widget_one2many_product_picker: User experience

### PR DESCRIPTION
**Pull request by Tardo**
Now there is no need to wait for the odoo responses

cc @tecnativa TT28908

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Can you rebase?

**Comment by Tardo** [comment]
done

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Is this already included in v13?

**Pull request merged**
