### PR TITLE
[14.0][MIG] web_responsive

### PR DESCRIPTION
**Pull request by pierre-pizzetta**
- chatter is now an owl component
- template name for 'discuss.mobile' is now 'KanbanView.MobileTabs'
- added <viewport> tag in 'web.template' <head>
- css classes '.oe_chatter' and '.o_chatter' are now replaced with '.o_FormRenderer_chatterContainer'

know issues:
- [x] ~~composer on mobile breakpoint doesn't clear the input after sending~~ edit: actually the behavior is the same on current enterprise runbot and seems to be a bug in the new owl composer component
- [x] viewport information were removed from web.layout and prevent scaling on mobile
- [x] chatter has wrong width ratio on desktop

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Wow, another difficult one that you have chosen.

**Comment by DarioLodeiros** [comment]
I think the chatter looks too narrow, revising it with how it looked in previous versions. Is it made like this by preference?
V14:
image
V13:
image

**Comment by pierre-pizzetta** [comment]
@DarioLodeiros not by preference, css class of the chatter seems to have changed and css need to be updated, will look at it. 
edit: Now fixed on runbot , thanks for the feedback

**Review by GSLabIt — COMMENTED** [review]
Got some small issues on tree view accessing  from mobile:
Screenshot_20201020_074921_com sec android app sbrowser beta

Screenshot_20201020_074937_com sec android app sbrowser beta

**Comment by pierre-pizzetta** [comment]
@GSLabIt Actually even on V13 there were some cases where the icons were leaving on the right because it was too narrow, I think part of that was wanting to make it nice and tidy, but if you go on views with action buttons with longer names you'll see it's often broken when using different view. So after adjusting for a while I think the best compromise is to use more lines to account for most content and have streamlined experience that doesn't rely on the perfect case. Would love some feedback before I commit anything.

image

**Comment by GSLabIt** [comment]
> @GSLabIt Actually even on V13 there were some cases where the icons were leaving on the right because it was too narrow, I think part of that was wanting to make it nice and tidy, but if you go on views with action buttons with longer names you'll see it's often broken when using different view. So after adjusting for a while I think the best compromise is to use more lines to account for most content and have streamlined experience that doesn't rely on the perfect case. Would love some feedback before I commit anything.
> 
> image

v 13 is bit different for mobile, view buttons are grouped and group by, filters are hidden and shows up on popup. 

Screenshot_20201020_094126_com sec android app sbrowser beta
}

**Comment by pierre-pizzetta** [comment]
Alright will go back more on 13

**Comment by jcdrubay** [comment]
It's looks great already, super nice :) Congrats!

There is a tiny issue of alignment on the right side the overlay window when opening an invoice line.

image

**Comment by patel1008b** [comment]
@pierre-pizzetta thanks for this module migration. its a great module for community edition. Is this module ready for merge in main branch ?
Thanks.

**Comment by pierre-pizzetta** [comment]
I think they are still a few tweaks to do, some class were removed from 13 to 14 and need to be added back to get it as smooth as the 13 version was on mobile, specificaly the search header

**Comment by patel1008b** [comment]
@pierre-pizzetta  thanks for this module migration. its a great module for community edition. Is this module ready for merge in main branch ?
Thanks.

**Comment by pinscher** [comment]
What about the sidebar for odoo14? Is it working fine?

**Comment by SplashS** [comment]
Hello. I was playing a little bit with this pull request.
I made some fixes that makes web_responsive looks nice with 14.0
I dont know how to propose these changes in repository.
@pierre-pizzetta, you can use them and commit on your own behalf.
There is udiff file from top of your pull request: https://www.paste.org/114814

There are still problem with quick searchview mode. It seems that in 14.0 mobile version of searchview completely moved to Enterprise and there are a lot of work to reproduse it in Communty on Owl.
But my version looks like a compromiss.

**Comment by pedrobaeza** [comment]
Closing as the other PR is more advanced

**Pull request closed without merging**
