### PR TITLE
[MIG] web_view_calendar_list: Migration to 13.0

### PR DESCRIPTION
**Pull request by etobella**
No major changes

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews

**Comment by hkapatel-initos** [comment]
It would be great if we could get the reviews here.

**Comment by hkapatel-initos** [comment]
@simahawk and @MiquelRForgeFlow it would be nice if you both can review here.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it.

**Pull request merged**
