### PR TITLE
[FIX] web_m2x_options: fix ignored field options

### PR DESCRIPTION
**Pull request by matt454357**
The module was ignoring the local field options 'create' and 'create_edit'.
For example, specifying options="{'create': true, 'create_edit': true}" on a
field would not override the web_m2x_options system parameters.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change module version.

@Yajo can you review?

**Review by yajo — APPROVED** [review]

**Comment by matt454357** [comment]
@pedrobaeza,
When updating the module version, do you want me to commit --fixup, rebase, and push --force? In other words, am I expected to rewrite history on my fork?

**Comment by pedrobaeza** [comment]
The easiest way in this case is to add a commit. We can squash on merge for having only 1 final commit on the main repo.

**Review by jabibi — APPROVED** [review]
:+1: 

Just make one new commit to bump module version. Thanks for your fix

**Review by JorgeNieto — APPROVED** [review]
I have tried the correction you make, and fix the error :+1:

**Comment by matt454357** [comment]
I changed the module version from 10.0.1.1.0 to 10.0.1.1.1
As can been seen, I also merged from upstream.  Hope this makes the merge easier.

**Comment by pedrobaeza** [comment]
I'm afraid you have screwed up a bit commit history. You mustn't do merge operations, but rebase.

**Comment by matt454357** [comment]
Yeah.  Sorry.  What now?

**Comment by pedrobaeza** [comment]
Make a rebase to fix it.

**Comment by matt454357** [comment]
Nope.  Still haven't got it right.  Umm.  How about a new branch and a new PR?

**Comment by pedrobaeza** [comment]
OK then

**Pull request closed without merging**
