### PR TITLE
[14.0][MIG] web_sheet_full_width

### PR DESCRIPTION
**Pull request by SimoRubi**
Standard migration from https://github.com/OCA/web/commit/ba119cc7203a0fe1539a492991210037eeca83e6

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test. LGTM

**Review by OpenCode — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test on 14 EE

**Review by tafaRU — APPROVED** [review]

**Comment by SimoRubi** [comment]
@OCA/web-maintainers can this be merged?

**Pull request merged**
