### PR TITLE
[15.0][IMP] web_timeline: Add configuration options

### PR DESCRIPTION
**Pull request by zamberjo**
Added **horizontalScroll** and **verticalScroll** options.

SEE: https://visjs.github.io/vis-timeline/docs/timeline/

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not [ADD], but [IMP], as it's not adding a module, but a feature inside an existing module.

**Comment by zamberjo** [comment]
> This is not [ADD], but [IMP], as it's not adding a module, but a feature inside an existing module.

You're right, I did it quickly and didn't think about it.

**Review by pedrobaeza — APPROVED** [review]

**Review by Jenniferrin — APPROVED** [review]
I have checked the functioning and it is correct.

**Pull request merged**
