### PR TITLE
8.0

### PR DESCRIPTION
**Pull request by tonygalmiche**
add web_widget_tolocalestring

### CODE REVIEW

**Comment by elicoidal** [comment]
@tonygalmiche   Thanks for your contribution to the OCA!
Please follow the principles: 
- Contribution guidelines: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md
- Please follow the updated OCA README template:
  https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
- We recommend to include a screenshot as well to help new comers (nice to have)
- Please use simple headers in all py files following OCA templates
  https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3

**Comment by dreispt** [comment]
@tonygalmiche What happened?

**Comment by hbrunn** [comment]
@dreispt a new branch in https://github.com/OCA/web/pull/309

**Comment by dreispt** [comment]
OK. A note here would have been nice.

**Pull request closed without merging**
