### PR TITLE
[12.0][MIG] web_listview_invert_selection

### PR DESCRIPTION
**Pull request by Martronic-SA**
migrate to 12,
pinned version,
swith to scss

### CODE REVIEW

**Comment by Martronic-SA** [comment]
Is there a simple way to fix the @oca-clabot complain about user? (no github login found)
thanks

**Comment by pedrobaeza** [comment]
That's because the email which you have committed is not registered in our DB linked to a GitHub user with a valid signed CLA.

**Comment by Martronic-SA** [comment]
@pedrobaeza Do I have to delete and recreate th PR with the right committer?

**Comment by pedrobaeza** [comment]
Or send another CLA with this email.

**Pull request closed without merging**
