### PR TITLE
[8.0] web_widget_x2many_2d_matrix: render axis values in received order

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
@hbrunn 

linked to issue https://github.com/OCA/web/issues/494

### CODE REVIEW

**Comment by hbrunn** [comment]
this relies on the rows arriving at the correct order. How about doing an extra search in https://github.com/OCA/web/pull/495/files#diff-d25cee8c92486a0e4cbf5ba21a360bbaR164 to ask the database about the order?

**Comment by Cedric-Pigeon** [comment]
I prefered to not restrict to _order attr of objet. It lets more freedom.

**Comment by hbrunn** [comment]
fine with me, but then make it clear in the readme that the order of the rows matters

**Comment by Cedric-Pigeon** [comment]
Readme updated

**Review by hbrunn — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Please forward port this to v9

**Review by JonathanNEMRY — APPROVED** [review]

**Pull request merged**
