### PR TITLE
[12.0][FIX] web_pivot_computed_measure: Change custom_events addition

### PR DESCRIPTION
**Pull request by Tardo**
Previous this commit, the controller events are discarted. With this commit the existing events are respected

cc  @tecnativa TT23644

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's fast-track it for fixing the annoying behavior:

/ocabot merge patch

**Review by legalsylvain — APPROVED** [review]
thanks

**Comment by pedrobaeza** [comment]
I have cleaned a bit the repo from linter warnings, so let's see if now it can merge:

/ocabot merge patch

**Pull request merged**
