### PR TITLE
[ADD] web_save_discard_button module

### PR DESCRIPTION
**Pull request by legalsylvain**
First PR : https://github.com/OCA/web/pull/2577
Code comes from : https://github.com/OCA/web/pull/2588

- PR correctly squashed
- Add french translation

Field are now translatable, thanks to @synconics refactor.

Should be OK to be merged now : CC : @Tardo, @Rad0van 

@synconics  : here are the command I did to squash the four commits : 

```
git remote rename  origin OCA
git remote add  synconics https://github.com/synconics/web
git remote add  legalsylvain https://github.com/legalsylvain/web
git fetch  synconics 16.0:synconics_16.0
 git checkout synconics_16.0
git rebase -i HEAD~4 
(Squash the four commits, using "s" command)
git pull OCA 16.0 --rebase
git push legalsylvain synconics_16.0
```

### CODE REVIEW

**Review by Rad0van — APPROVED** [review]
LGTM

**Comment by synconics** [comment]
Hi @Tardo @Rad0van , Should we need to do anything ?

**Comment by synconics** [comment]
Hi @Tardo  @Rad0van @legalsylvain , Merge request was merged more then 2 weeks ago, is there any plan to publish module?

**Comment by legalsylvain** [comment]
Well, publication is automatic, once merged : 

- publication on pipy :+1:  https://pypi.org/project/odoo-addon-web-save-discard-button/ 
- publication on OCA website :-1: https://odoo-community.org/shop?&search=web_save_discard_button 
- publication on odoo website :-1: https://apps.odoo.com/apps/modules/browse?search=web_save_discard_button there is a similar non OCA paid module only.

@OCA/board : could you take a look ?

**Pull request merged**
