### PR TITLE
Update README because of wrong license

### PR DESCRIPTION
**Pull request by damdam-s**
Found in this commit: https://github.com/OCA/web/commit/3965057913982b2e976d94490d027c747b2423a8

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
Was wrongly setted at module migration to V11

**Review by tarteo — COMMENTED** [review]
You can instead of fixing it in the current README, use the new splitted readme (https://github.com/OCA/maintainer-tools/tree/master/template/module) than it's also solved and the README will look alot better.

**Comment by leemannd** [comment]
@tarteo He's been asked by an external guy what is the proper license, as there is another one in all other files.
IMO it should be fast-tracked to avoid any problems.

**Comment by leemannd** [comment]
@gurneyalex Do you think it's mergeable?

**Pull request merged**
