### PR TITLE
web responsive error xml templates device

### PR DESCRIPTION
**Pull request by mt-software-de**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you explain the steps to reproduce the error in OCA runbot?

**Comment by mt-software-de** [comment]
No i can not explain how to reproduce it in OCA runbot, because i dont know how your runbot is working, is there an howto for it?
The problem is, that "device" is not defined as an variable the device is callable via env.device.

**Comment by pedrobaeza** [comment]
I'm afraid the problem you are having is only on your side then, as the module is working without problems in a clean environment. OCA runbot can be started from the button "Runbot | Try me" that is on the README.

**Comment by mt-software-de** [comment]
ok i will check this. thanks

**Comment by SplashS** [comment]
@mt-software-de `device` here is defined via deviceContext wrapper.
it provides the automatic rerendering on browser viewport size change.
The way you provide may work but without this automatic rerendering.
Can you describe the problem you've got?

**Comment by mt-software-de** [comment]
sorry for the late answer im very short of time right now. 
i will check why we are facing this error, but for now i will close this pull request

**Pull request closed without merging**
