### PR TITLE
[14.0][FIX] `web_advanced_search`: relational widget on `sale.report`

### PR DESCRIPTION
**Pull request by ivantodorovich**
Steps to reproduce:

1. Install Sales app
2. Go to Sales > Reporting > Sales
3. Add Custom Filter > Product > Is equal to

Without this fix an error is raised:
```
relational.js:39 Uncaught (in promise)
TypeError: Cannot read properties of undefined (reading 'endsWith')
    at Class.init (relational.js:39:28)
```
---

This is a backport of a refactor made in Migration to 15.0
- https://github.com/OCA/web/pull/2153

The code is a bit simpler an less hacky now, respecting widgets hierarchy and responsibilities.

### CODE REVIEW

**Comment by ivantodorovich** [comment]
@flachica @Yajo  could you have a look at this one, too? 🙏🏻

**Review by yajo — APPROVED** [review]
I'm not against the patch, but I tested the STR in main branch and I didn't get the error. Did you miss something there? 🤔

**Comment by ivantodorovich** [comment]
I can't reproduce it neither now.. 😮
Honestly I don't know what happened 😅 I remember reproducing it on runboat before creating this PR

**Comment by yajo** [comment]
So, do you think this PR is still worth it?

**Comment by ivantodorovich** [comment]
Can't reproduce anymore

**Pull request closed without merging**
