### PR TITLE
[15.0] [MIG] web_ir_actions_act_window_message

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Adapt OWL framework

### CODE REVIEW

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM!

**Review by DavidJForgeFlow — APPROVED** [review]
Functional review :+1: and code LGTM

**Comment by gjotten** [comment]
@OCA/web-maintainers this looks ready to be merged.

**Pull request merged**
