### PR TITLE
[15.0][MIG] web_company_color

### PR DESCRIPTION
**Pull request by BernatPForgeFlow**
Standard migration to v15

### CODE REVIEW

**Comment by BernatPForgeFlow** [comment]
@Tardo Do you agree about the changes managing the active_company_id?

**Comment by BernatPForgeFlow** [comment]
@ForgeFlow @ChrisOForgeFlow @LoisRForgeFlow @JoanMForgeFlow

**Review by simahawk — APPROVED** [review]
LG

**Review by ChrisOForgeFlow — APPROVED** [review]
+1

**Review by Tardo — APPROVED** [review]
LGTM Good job!

**Pull request merged**
