### PR TITLE
[ADD] web_x2m_defaults_from_previous

### PR DESCRIPTION
**Pull request by hbrunn**
x2many defaults
===============

This module was written to allow you to use the previous line's input as defaults for the next line you add.

Usage
=====

- on a x2many field, say ``options="{'web_x2m_defaults_from_previous': ['field1', 'field2']}"``
- after the first line of input, succeeding lines will have the last input's values as default
- demo data adds this for the ACL list field in the groups form

Known issues / Roadmap
======================

* many2many fields are not yet supported

### CODE REVIEW

**Review by jjscarafia — APPROVED** [review]
Nice feature! Tested on runbot. Clean code

**Review by moylop260 — APPROVED** [review]
Thank you

**Review by lasley — COMMENTED** [review]
Neat, thanks @hbrunn 

Are the booleans supposed to default as well? In the case of the demo, the access fields.

**Comment by hbrunn** [comment]
No, only `name` and `model_id`: https://github.com/OCA/web/pull/510/files#diff-233b2dfda416b2628574af7a0a43b7e4R9 - but if you patch one of the booleans into the view, this will work too.

**Review by lasley — APPROVED** [review]
Sweet thanks @hbrunn

**Pull request merged**
