### PR TITLE
[9.0][MIG]web_action_conditionable: migration to 9.0

### PR DESCRIPTION
**Pull request by zakiuu**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's already another migration in https://github.com/OCA/web/pull/457

**Comment by zakiuu** [comment]
@pedrobaeza Sorry, didn't see it, but it has been there since 2016, can we close it and take this one?

**Comment by pedrobaeza** [comment]
Please contact first with the author to see if they are going to continue it, because they have priority. If not, we can close it in favor of this one. Any way, yours has Travis red.

**Comment by ovnicraft** [comment]
LGTM
You can make it green if move to `__manifest__.py` and ad license key

**Comment by zakiuu** [comment]
@pedrobaeza @ovnicraft green!

**Review by gurneyalex — APPROVED** [review]

**Review by sbidoul — APPROVED** [review]

**Pull request merged**
