### PR TITLE
[REM] web_widget_datepicker_options: No longer needed

### PR DESCRIPTION
**Pull request by yajo**
This addon is no longer needed since https://github.com/odoo/odoo/pull/25044#issuecomment-396940644, so I remove it.

WIP until:

- [x] https://github.com/odoo/odoo/pull/25235

@tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @moylop260

**Comment by luisg123v** [comment]
@Yajo 
Just to be sure, are you sure the change in Odoo works fine for both date and datetime?

**Comment by yajo** [comment]
You're right, I opened https://github.com/odoo/odoo/pull/25235 to fix that case. Thanks!

I'll set this as WIP until that's merged upstream.

**Review by tarteo — APPROVED** [review]
Can you also remove the pot file, please?

**Comment by yajo** [comment]
Upstream was fixed in https://github.com/odoo/odoo/pull/27541 and we didn't notice it here.

This is ready to merge.

**Pull request merged**
