### PR TITLE
[15.0][MIG] web_advanced_search: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@simahawk can you pls approve the workflow?

**Comment by yankinmax** [comment]
@hbrunn can you pls take a look?

**Comment by celm1990** [comment]
@yankinmax I tested and it isn't working for me.

https://user-images.githubusercontent.com/7775116/151714450-ec2ffd52-7510-43ba-b8f1-ab2ad2f4a068.mp4

**Comment by yankinmax** [comment]
@celm1990 thank you very much for the heads up on this.
Yes, it won't be working till we migrate code that is refactored in `web`.
From what I see at the moment:
1. https://github.com/odoo/odoo/blob/14.0/addons/web/static/src/js/core/patch_mixin.js is gone in V15. 
2. `const { useModel } = require('web.Model');` is now at `legacy` folder in modules.
I tried to migrate one of the scripts `advanced_filter_item.js`, but I stop here, as not a big Odoo JS Framework expert and failed to migrate `filter_menu.js` for example.

**Comment by ivantodorovich** [comment]
Superseeded by:
- [ ]  https://github.com/OCA/web/pull/2153

**Pull request closed without merging**
