### PR TITLE
[12.0][MIG] web_widget_digitized_signature

### PR DESCRIPTION
**Pull request by mgosai**
Migrated Module

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's a warning in runbot, but log is not accessible right now. I have ordered a rebuild for being able to see it, but for sure you can check the warning in the local environment.

**Comment by max3903** [comment]
Superseeded by #1325

**Comment by pedrobaeza** [comment]
Is @mgosai from your team, @max3903 ?

**Comment by max3903** [comment]
@pedrobaeza Yes.

**Pull request closed without merging**
