### PR TITLE
[IMP] web_create_write_confirm: fix JS, usage. Minor refactoring.

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Comment by ilyasProgrammer** [comment]
@simahawk could you please review ? You refactoring changes are here. Also some small JS fixes.

**Comment by francesco-ooops** [comment]
@tarteo fyi :)

**Comment by francesco-ooops** [comment]
@simahawk ping :)

**Comment by francesco-ooops** [comment]
@simahawk in this PR you can find the changes you requested here: https://github.com/OCA/web/pull/2487#pullrequestreview-1543163544

also without this fix a few features in runboat are blocked by this module, so a merge would be very welcome :)

**Comment by francesco-ooops** [comment]
@yajo what do you think? :)

**Comment by yajo** [comment]
Sorry, I don't know this module and I don't know what this is trying to fix, so I'm not the best one to review here.

**Comment by francesco-ooops** [comment]
@OCA/web-maintainers some runboat features are blocked since this module is displaying errors. This PR fixes it. Can we merge please?

**Review by legalsylvain — COMMENTED** [review]
functional review on runboat. Something looks broken.
step to reproduce : 
- > go to settings / users > create new user
- > click on save.

Error:

```

Error: event is undefined
ev@http://oca-web-14-0-pr2576-841db5557087.runboat.odoo-community.org/web_create_write_confirm/static/src/js/pop_up_confirmation.js:100:13
display_popup/<@http://oca-web-14-0-pr2576-841db5557087.runboat.odoo-community.org/web_create_write_confirm/static/src/js/pop_up_confirmation.js:93:26
display_popup@http://oca-web-14-0-pr2576-841db5557087.runboat.odoo-community.org/web_create_write_confirm/static/src/js/pop_up_confirmation.js:44:13
_onSave/<@http://oca-web-14-0-pr2576-841db5557087.runboat.odoo-community.org/web_create_write_confirm/static/src/js/pop_up_confirmation.js:29:22```

**Comment by ilyasProgrammer** [comment]
updated

**Review by legalsylvain — APPROVED** [review]
Functional review. LGTM.

No Code review.

**Comment by francesco-ooops** [comment]
@simahawk when you can. Thanks!

**Comment by francesco-ooops** [comment]
@simahawk what do you say?

**Review by simahawk — APPROVED** [review]
LG

**Pull request merged**
