### PR TITLE
[10.0] Add module web_no_bubble

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't any configuration for this?

**Comment by ghost** [comment]
@pedrobaeza there is the Consume Tour button in debug mode which could do the trick. It consumes all notification bubbles. This module does not remove the notifications but only the odd bubbles that come with it.

**Review by pedrobaeza — APPROVED** [review]
I also see them very annoying, so goodbye!

**Review by rafaelbn — APPROVED** [review]
Thanks!

**Review by guewen — APPROVED** [review]

**Pull request merged**
