### PR TITLE
[16.0][MIG] web_dashboard_tile (from 15.0)

### PR DESCRIPTION
**Pull request by legalsylvain**
migration from 12.0 to 16.0

- remove 12.0 migration scripts
- bump version to 16.0
- use new api convention @api.model_create_multi ; new compute function logic ;
- add dependency to spreasheet_dashboard to use 'Dashboard' main menu item
- use new way to include assets
- remove totally useless controllers
- distinct different errors, depending on domain or format errors
- fix : _compute_data depends on many fields
- update : documentation and printscreens

### Description

This module extends the web module to add new dashboard overview system.

By default, the tile displays items count of a given model restricted to a given domain.

Optionally, the tile can display the result of a function on a field.

- Function is one of ``sum``, ``avg``, ``min``, ``max`` or ``median``.
- Field must be integer or float.

Tile can be:

- Displayed only for a user.
- Global for all users.
- Restricted to some groups.

*Note: The tile will be hidden if the current user doesn't have access to the given model.*

### Configure

First, you have to create tile categories.

* Go to "Dashboards > Configuration > Overview Settings > Dashboard Categories"

* Create categories

Odoo menu and action are automatically created in the "Dashboard > Overview" menu
You should refresh your browser to see new menu items.

tile_category_form

Then you can create tiles.

* Go to "Dashboards > Configuration > Overview Settings > Dashboard Items"

* create a new tile, set a name, a category and a model.

* You can optionally define colors, domain and a specific action to use.

* Setting a user, or a group in "Security" tab will restrict the display of the tile.

tile_tile_form

You can optionally define a secondary value, for that purpose :

* Select a field, a function to apply.

* You can define a specific format. (``.format()`` python syntax)

tile_tile_form_secondary_value

### Usage

* Go to "Dashboard > Overview" and select a category

* The tile configured is displayed with the up to date count and average values of the selected domain.

tile_tile_kanban

* By clicking on the item, you'll navigate to the tree view of the according model.

tile_tile_2_tree_view

### CODE REVIEW

**Comment by legalsylvain** [comment]
CC : @nicomacr, @ivantodorovich

**Review by ivantodorovich — APPROVED** [review]
Code & functional review 👍🏻 LG

Do you still see some use for this module, considering users can achieve the same and more with spreadsheet dashboards?

**Comment by legalsylvain** [comment]
Maybe i missed something, but AFAIK, "spreadsheet dashboards" edition is EE for the time being. Right ?

**Comment by pedrobaeza** [comment]
Not really. There's only missing the "Edit" button in CE, that can be added in a module. I requested the creation of OCA/spreadsheet repository for hosting it, among others. Probably @ivantodorovich will create this module in a glance, as he knows JS very well. We plan to do it, but we need to learn and it will take some time.

**Comment by ivantodorovich** [comment]
I haven't checked in detail but I thought it was CE, considering we have all these `spreadsheet_dashboard_*` modules: https://github.com/odoo/odoo/tree/16.0/addons/spreadsheet_dashboard_account

I need to check that too, @pedrobaeza

**Comment by legalsylvain** [comment]
@ivantodorovich 

**regarding the "spreadsheet" topic**
- the library has been opensourced recently. (september 2022, AFAIK : https://github.com/odoo/o-spreadsheet)
- all the "default dashboard" has been opensourced in V16 in many modules ``spreadsheet_dashboard_xxx``
- the dashboards are now encoded in a non readable / non updatable (by human) syntax. See : https://github.com/odoo/odoo/blob/16.0/addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
-  To create new dashboard or edit existing ones, we need need the "Edit" Button that is in EE. (Also handle edition in multi user context should requires some works I think)

**Regarding the current PR**
in the meantime, could we accept this PR ? Indeed, it's a concurrent way to have dashboard but it's : 
- lighter to configure (no need to understand the ``odoo.balance...`` javascript syntax)
- much less functionality, of course
- possible to use it with a CE edition (waiting for the OCA module)

maybe indeed, the futur spreadsheet CE module will make this module useless.

**Comment by ivantodorovich** [comment]
I'm not against having this module, too 👍🏻

**Review by quentinDupont — APPROVED** [review]
Thanks for demo datas
Functional review, create tiles and tiles categories easily : works fine :heavy_check_mark:

**Comment by legalsylvain** [comment]
Thanks for your reviews ! 

/ocabot merge nobump

**Pull request merged**
