### PR TITLE
[15.0][MIG]web_tree_dynamic_colored_field

### PR DESCRIPTION
**Pull request by Herqs**
Seems to be working as is, straight forward migration

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @Herqs. Thanks for porting this module.

could you cherry pick the following merged commits : 
- https://github.com/OCA/web/pull/1950/commits/7b005c4b6ee58575c6057412d93548a5af08691f 
- https://github.com/OCA/web/pull/1777/commits/ea13a0c93e594e6b1ff1f4744a12eba0cc8465c6
- https://github.com/OCA/web/pull/1777/commits/69219cf995e58bc634dc4bb48b895164a111ec09

and the following unmerged commits : 
- https://github.com/OCA/web/pull/2130/commits/74c0b52e9b68a6ea3cdd12e8a29bf4744555eea6

kind regards.

**Comment by Herqs** [comment]
@legalsylvain Aren't these commits outdated? `Renderbody` method has been removed altogether.

**Comment by legalsylvain** [comment]
The feature are not outdated, AFAIK. Maybe some adaptation should be done, thought. The obejctive of migrate a module is to recover the features previously available.

**Comment by Herqs** [comment]
As from what I see, the feature has been removed post v13 due to changes in the `RelaxNG schema of the tree view`, so the
feature should be implemented differently than in v12. Maybe a new PR with new changes should be made after this PR with v14 functionality is merged?
@legalsylvain

**Comment by legalsylvain** [comment]
> As from what I see, the feature has been removed post v13 due to changes in the RelaxNG schema of the tree view.

No, the feature has been implemented in V12, and not in V13. There are not been removed. The V13 / V14 versions has less functionnalities as V12.

My opinion is to recover all the functionnalities present in the previous version (if it's relevant, but in that case, it is).

If it's not in the scope of your work, please write a line per feature lost, in the ROADMAP.rst file of the module, mentionning precisely the commit to recover and the features to implement again.

regards.

**Comment by Herqs** [comment]
> No, the feature has been implemented in V12, and not in V13. There are not been removed.

It has been redone in https://github.com/OCA/web/commit/0280e0479c3152093000fbca09e4445139c277d4 (v12 -> v13 mig) and then removed later in https://github.com/OCA/web/commit/8469dbb954b6b312872cd2646bbb335faa94afe6 alongside the `_render_body` method.
> If it's not in the scope of your work, please write a line per feature lost, in the ROADMAP.rst file of the module, mentionning precisely the commit to recover and the features to implement again.

I will update the PR to have commit numbers in the ROADMAP.rst file, but the lost feature is already mentioned in v13 and v14 and the current ROADMAP.rst version.
@legalsylvain 
Regards.

**Comment by legalsylvain** [comment]
Closing. the module has been done 2 monthes before here https://github.com/OCA/web/pull/2145 and has been merged.

**Pull request closed without merging**
