### PR TITLE
[IMP] pre-commit update

### PR DESCRIPTION
**Pull request by yajo**
Implement changes from OCA/maintainer-quality-tools#618, OCA/maintainer-quality-tools#628, OCA/maintainer-quality-tools#630 and https://github.com/OCA/maintainer-quality-tools/pull/631.

@Tecnativa TT20357 @sbidoul

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please update with recently merged module.

**Comment by yajo** [comment]
WIP until OCA/maintainer-quality-tools#630 is merged.

**Review by Tardo — APPROVED** [review]
:+1: For my taste, in some points it makes the code difficult to read but in general it improves it.

**Comment by yajo** [comment]
OK, let me use my PSC superpowers to merge my own PR for once, so we stop races with PRs being merged without this.

/ocabot merge

**Pull request merged**
