### PR TITLE
[18.0] help on web repo to apply last pre-commit changes

### PR DESCRIPTION
**Pull request by xaviedoanhduy**

### CODE REVIEW

**Review by chienandalu — COMMENTED** [review]
Can you point the issue you're fixing? Is that reordering happening automatically or something?

**Comment by xaviedoanhduy** [comment]
> Can you point the issue you're fixing? Is that reordering happening automatically or something?

yes, have a warning in CI when run `pre-commit run -a`

```
prettier (with plugin-xml)...............................................Passed
eslint...................................................................Passed
- hook id: eslint
- duration: 0.61s


/home/trobz/code/oca/web/18.0/web_tree_many2one_clickable/static/src/components/many2one_button/many2one_button.esm.js
  11:1  warning  Imports should be sorted alphabetically  sort-imports

✖ 1 problem (0 errors, 1 warning)


trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
```

**Review by chienandalu — APPROVED** [review]
Thanks :)

(how I hate that rule! :sweat_smile: )

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
