### PR TITLE
[ADD] New module website_blog_mgmt

### PR DESCRIPTION
**Pull request by lmignon**
- This module lets you specify a date for the post at which it will be published.
- Posts on the website are ordered by publication date.
- The order of posts is preserved when navigating between posts
- Since it's HARD/not possible to extend controller without rewriting completly
  the overrided functions, the module also fixes https://github.com/odoo/odoo/pull/3097
  (loop issue when pressing the next button on a blog page)

### CODE REVIEW

**Comment by sbidoul** [comment]
I think this PR should go to OCA/website instead.

**Comment by pedrobaeza** [comment]
Me too

**Comment by lmignon** [comment]
You are right. I'll relocale my proposal on 'website'

**Comment by lmignon** [comment]
new PR on OCA/website https://github.com/OCA/website/pull/8

**Pull request closed without merging**
