### PR TITLE
[12.0] [MIG] web_widget_domain_editor_dialog

### PR DESCRIPTION
**Pull request by darshan-odoo**
Issue #1048

### CODE REVIEW

**Review by anandkansagra — APPROVED** [review]

**Review by yajo — CHANGES_REQUESTED** [review]
Code looks good, but when following the instructions from the readme, I got this error:

```
TypeError: dict.value.value is null[Saber más] qweb2.js line 469 > Function:13:62
    anonymous http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js line 469 > Function:13
    foreach http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js:180
    anonymous http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js line 469 > Function:11
    _render http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js:458
    render http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js:450
    _renderPopover http://3370109-1282-be916d.runbot1-2.odoo-community.org/web_edit_user_filter/static/src/js/backend.js:166
    renderFacets http://3370109-1282-be916d.runbot1-2.odoo-community.org/web_edit_user_filter/static/src/js/backend.js:212
    forEach Underscore
    renderFacets http://3370109-1282-be916d.runbot1-2.odoo-community.org/web_edit_user_filter/static/src/js/backend.js:205
    OdooClass.extend/Class.include/</prototype[name]</< http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/src/js/core/class.js:123
    proxy http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/src/js/core/mixins.js:278
    Backbone 3
    start http://3370109-1282-be916d.runbot1-2.odoo-community.org/web_widget_domain_editor_dialog/static/src/js/widget_domain_editor_dialog.js:42
    OdooClass.extend/</prototype[name]</< http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/src/js/core/class.js:90
    _widgetRenderAndInsert http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/src/js/core/widget.js:399
    jQuery 13
    _load http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/src/js/core/ajax.js:493
    add_template http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js:288
    add_template http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js:255
    load_xml http://3370109-1282-be916d.runbot1-2.odoo-community.org/web/static/lib/qweb/qweb2.js:367
```

**Comment by darshan-odoo** [comment]
@Yajo I just created a Filter, in the runbot, and I am trying to reproduce the error you faced, could you help me with that, with providing the exact steps, and at what particular action the error was faced?

**Comment by yajo** [comment]
Yes, you have to go to the web console to see the error:

Peek 16-05-2019 09-09

**Comment by darshan-odoo** [comment]
@Yajo Oh Yes right indeed :)

I will take a look and resolve it, thanks!

**Comment by anandkansagra** [comment]
> Yes, you have to go to the web console to see the error:
> 
> Peek 16-05-2019 09-09

I have seen this issue.
I have noticed that the issue came from `web_edit_user_filter` module.
I have uninstalled it and didn't find this traceback.
I have traced it in web console and there seems an error from `web_edit_user_filter` module. Here is the screenshot.

**Review by yajo — APPROVED** [review]
>  I have noticed that the issue came from `web_edit_user_filter` module.

Indeed, you're right.

**Comment by pedrobaeza** [comment]
But any way, it should be fixed in the repo. @tarteo it was you the one that migrated `web_edit_user_filter`?

**Review by chienandalu — APPROVED** [review]
:+1: Thanks @darshan-odoo

**Pull request merged**
