### PR TITLE
[15.0][MIG] web_widget_mermaid

### PR DESCRIPTION
**Pull request by TheRealRoboHeart**
Migration of module web_widget_mermaid from v12.0 to v15.0

### CODE REVIEW

**Review by tarteo — APPROVED** [review]
LGTM, tested locally

**Comment by ivantodorovich** [comment]
Thanks for the work done!

Please follow the steps described in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#how-to to perform a migration. When migrating a module, we need to keep and respect the commit history: not simply copy & paste the code.

**Comment by bosd** [comment]
What is the status of this one?

**Review by bofiltd — APPROVED** [review]

**Comment by bosd** [comment]
> fatal: repository 'https://github.com/TheRealRoboHeart/web/' not found

@OCA-git-bot The correct repo is
https://github.com/TheRealRoboHeart/oca-web/tree/15.0-mig-web_widget_mermaid

**Comment by dreispt** [comment]
Superseded by #2763

**Review by dreispt — APPROVED** [review]

**Pull request closed without merging**
