### PR TITLE
[16.0][FIX] web_m2x_options: Avoid constant RPC calls 

### LINKED ISSUE #2494: [16.0] web_m2x_options: to much  get_web_m2x_options calls
When you load a page there are lot call to get_web_m2x_options

image

Can you reduce that ?

@anothingguy

### PR DESCRIPTION
**Pull request by nguyenminhchien**
Fix this issue https://github.com/OCA/web/issues/2494

### CODE REVIEW

**Comment by rinaldifirdaus** [comment]
Functional test: no more a lot of call to get_web_m2x_options. speed to open the pages back to normal. nice!

**Comment by pedrobaeza** [comment]
Please amend the commit message:

```
[FIX] web_m2x_options: Avoid constant RPC calls

Instead of calling interactively to the server to get the options, they are stored at the beginning of the session.
```

**Review by pedrobaeza — APPROVED** [review]

**Review by fmdl — APPROVED** [review]

**Comment by nguyenminhchien** [comment]
@pedrobaeza updated

**Pull request merged**
