### PR TITLE
[MIG] 10.0 : web_translate_dialog

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please respect commit history following migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by JayVora-SerpentCS** [comment]
@pedrobaeza we've pushed only 1 commit. And migrated what was in v10. Help plz.

**Comment by pedrobaeza** [comment]
Yeah, but this is the problem: you need to respect the commit history from others, and squash what is needed. Please follow these guides: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch and https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by JayVora-SerpentCS** [comment]
@pedrobaeza I have made #585 and did not pull upstream. If I pull the upstream, I might have to squash. Please guide whether we need to consider #585 as right for now or I rebase my branch with parent?

**Pull request closed without merging**
