### PR TITLE
Update web_no_bubble.css

### PR DESCRIPTION
**Pull request by aman-g202**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why this change?

**Comment by aman-g202** [comment]
Just going through your project..felt like changing it

**Comment by pedrobaeza** [comment]
But what it improves?

**Comment by yajo** [comment]
No sense on aligning a hidden element, don't you think? 🤔

**Comment by simahawk** [comment]
so... anything to do here? :)
@Yajo seems like that element is displayed by tooltip JS.
@darkshadow237 can you provide more info on what you want to do, possibly w/ screenshots?

**Comment by pedrobaeza** [comment]
I don't think so.

**Pull request closed without merging**
