### PR TITLE
IMP 12.0 add char and text fields for numpad dot fuctionality

### PR DESCRIPTION
**Pull request by ljimenezsidoo**
Allow to use numpad dot code in two more fields: Char and Text

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is not valid, as char and text fields can contain the dot for several purposes and you want to keep then even if coming from the numpad part.

What do you think about this, @chienandalu ?

**Comment by chienandalu** [comment]
I think the same. It'd be annoying

**Comment by ljimenezsidoo** [comment]
The regular dot and the numeric keypad dot have a different keycode. You can use the dot in these fields with the regular dot equally and for other situations where you need to use the l10n parameters and change the numpad dot to a comma, you can too

**Comment by angelmoya** [comment]
Please @pedrobaeza and @chienandalu  check @acm1pt-colorado comment, as keypad dot will allways a comma in this case, and you still have regular dot key.

**Comment by pedrobaeza** [comment]
As said, it's confusing to do that replacement in text fields IMO.

**Pull request closed without merging**
