### PR TITLE
[15.0][MIG] web_widget_text_markdown : Migration to 15.0

### PR DESCRIPTION
**Pull request by BernatObrador**
Module migrated to version 15.0

cc https://github.com/APSL 155898

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn please review

### CODE REVIEW

**Comment by mpascuall** [comment]
Please squash your last commit with the migration one

**Comment by peluko00** [comment]
Where is the first formatting commit before the migration commit?

**Review by mpascuall — APPROVED** [review]
LGTM

**Review by javierobcn — APPROVED** [review]
Tested locally with custom development using this component. It's working!

**Review by peluko00 — APPROVED** [review]
Code review, LGTM

**Comment by BernatObrador** [comment]
@pedrobaeza Is this ready to merge?

**Pull request merged**
