### PR TITLE
Separated Lint tests

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi, @yvaucher, can you explain what is this new param (LINT_CHECK) ? Is it about Pylint Test ? 
Regards.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@legalsylvain, this responds to my initiative to isolate the test in one environment. You can check details here: https://github.com/OCA/maintainer-quality-tools/issues/126

**Comment by tafaRU** [comment]
:+1:

**Pull request merged**
