### PR TITLE
[15.0][IMP] web_widget_numeric_step: Add border to buttons shown

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa 

ping @sergio-teruel @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please put images of the before/after.

**Comment by CarlosRoca13** [comment]
Before this change:
image

After this change:
image

**Comment by pedrobaeza** [comment]
I'm not sure it's best with border, and in fact, v16 goes against this in its design. Why do you want this?

**Comment by CarlosRoca13** [comment]
I think that using the border makes it clearer the limits of the buttons and a mobile user will know more clearly where to click.

**Comment by pedrobaeza** [comment]
On a non precise environment like mobiles, where the "cursor" is your finger, the important thing is the focus center, and this one is clearly shown by the + / - icon, so I still think it's better the old approach, as putting a lot of borders makes you vision to need more concentration on the elements. That's why the "clean" approach that UIs are taking (can be called also minimalist) try to save the maximum all the superfluous UI elements.

**Comment by legalsylvain** [comment]
> I'm not sure it's best with border, and in fact, v16 goes against this in its design. Why do you want this?

Agree with @pedrobaeza on that topic. The general design of Odoo 16 is "no border". I don't think it's the good idea if each ``web`` module implement design that does'nt match with the general one.

however, if you don't like this direction (as I do !), you can use this OCA module : https://github.com/OCA/web/tree/16.0/web_theme_classic

regards.

**Review by sergio-teruel — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
Ok, so let's close this PR

Thanks for the reviews

**Pull request closed without merging**
