### PR TITLE
[14.0][FIX] web_drop_target: check controller is not null

### PR DESCRIPTION
**Pull request by Saran440**
fix it from issue https://github.com/OCA/web/issues/2298

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please fix pre commit

**Review by pedrobaeza — APPROVED** [review]
It works itself. Let's see how it works with DMS.

**Comment by KKamaa** [comment]
Hey guys this fix messed up the module could you please retest. I'm going through it too cause once it was added we can't be able to drag and drop files.

**Comment by Saran440** [comment]
@KKamaa Sorry, I'm not expert JS. Can you help fix it, please?

**Comment by KKamaa** [comment]
> @KKamaa Sorry, I'm not expert JS. Can you help fix it, please?

did the fix [here ->PR](https://github.com/OCA/web/pull/2369)

**Pull request merged**
