### PR TITLE
[14.0][mig]web_send_message_popup

### PR DESCRIPTION
**Pull request by hkapatel-initos**
Migration to 14.0

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
It would be nice if could anyone review this PR?

**Review by dsolanki-initos — APPROVED** [review]
No major change. LGTM

**Comment by hkapatel-initos** [comment]
@StephaneMangin  and @gaikaz  can you please review this PR?

**Review by gaikaz — COMMENTED** [review]
Tested functionally on runbot and it doesn't seem to work.
Chrome DevTools console output screenshot with asset debugging enabled :
image

**Comment by hkapatel-initos** [comment]
> Tested functionally on runbot and it doesn't seem to work.
> Chrome DevTools console output screenshot with asset debugging enabled :
> image

hello @gaikaz,
I have checked the functionality in v13 merged module with asset debugging enabled :
I saw the same warning ( image
and the module functionality is working properly, so I don't think the warning needs to be solved. 
Thanks

**Comment by gaikaz** [comment]
@hkapatel-initos 
Ok, but it doesn't change the fact that it just doesn't work on v14 runbot. I can't approve.
If it does work for you there, maybe you'll have some ideas as to why it doesn't for me and how we can solve this. But if you are getting the same console errors even on v13, I don't understand how it could work, as the JS part wouldn't be loaded.

Video of it not working on v14 runbot:

https://user-images.githubusercontent.com/17097810/125798471-75c77d58-ab4b-409c-954c-7abc76b6f60c.mp4

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos
> Ok, but it doesn't change the fact that it just doesn't work on v14 runbot. I can't approve.
> If it does work for you there, maybe you'll have some ideas as to why it doesn't for me and how we can solve this. But if you are getting the same console errors even on v13, I don't understand how it could work, as the JS part wouldn't be loaded.
> 
> Video of it not working on v14 runbot:
> 
>  popup.not.working.mp4

Can you please see this video working on v14 runbot:
https://www.awesomescreenshot.com/video/4531825?key=fe271246ad32687f5ebeb119fd9e25b5

**Comment by gaikaz** [comment]
Sorry, but do you even know what the module does?
When you click the "Send Message", it should give you a popup to full message editor.
It's not working in your video either.

**Comment by hkapatel-initos** [comment]
Hello, @gaikaz 
I have checked this module functionality in v13. It doesn't show poup when you click "Send message". Popup is raised when the email icon is clicked on the posed message in the chatter.

Same works in v14. I have shared some pictures and videos from v13 
you can have a look.

Thank You!
https://www.awesomescreenshot.com/video/4558288?key=df90bcb069160693cf26d2c8e3b85bf2

**Comment by gaikaz** [comment]
What you are describing is standard Odoo.
Look at the description of the module you are migrating:
image

**Comment by hkapatel-initos** [comment]
> What you are describing is standard Odoo.
> Look at the description of the module you are migrating:
> image

Hello, I don't think V13 a module functionality works properly. I took reference from the v12 module and i will make it compatible with v14

**Comment by gaikaz** [comment]
Okay, thank you! 
v13 does work, but strangely slow. In v12 it used to open the popup right after the click, but v13 somehow opens the little text box first and only after a couple of seconds opens the popup. It really is annoying.
Hopefully you can make it work better for v14 🙂

**Comment by hkapatel-initos** [comment]
it would be nice if someone helps me to resolve this warning because it is generated only on runbot generate and needs code review.

**Comment by gaikaz** [comment]
> it would be nice if someone helps me to resolve this warning because it is generated only on runbot generate and needs code review.

@hkapatel-initos Are you talking about this error?

error

It seems to be generated by another module from this OCA/web repository called `web_access_rule_buttons`
If you uninstall that one, the error goes away. Also, we get it even when this (`web_send_message_popup`) module is not even installed, so... Submitting that as an issue here: #2007

If this is not the warning you are talking about, then please provide more details.

**Comment by hkapatel-initos** [comment]
Thanks for your suggestion, @gaikaz, when web_access_rule_buttons install it is generated this error and it is not related to my module so...
I uninstalled the module (web_access_rule_buttons) uninstall this module and test this module, it's working. it would be nice if you give the approval to this pull.

**Review by gaikaz — APPROVED** [review]
Thank you for your patience @hkapatel-initos 🙂 Good work.

Code review and functional testing
LGTM 👍🏻

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
@simahawk Can we merge this?

**Pull request merged**
