### PR TITLE
[17.0][MIG] web_timeline: Migration to version 17.0

### PR DESCRIPTION
**Pull request by carlos-lopez-tecnativa**
- Convert Moment.js to Luxon.
- Replace Underscore.js with native JavaScript code.
- Migrate legacy views to the new system and add an architecture parser to separate logic.
- added basic test

TT50999

@Tecnativa @pedrobaeza @CarlosRoca13 @victoralmau @chienandalu could you please review this

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Functional review in https://github.com/OCA/project/pull/1354

**Review by CarlosRoca13 — APPROVED** [review]
Nice work :smile: thanks

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@carlos-lopez-tecnativa I'm now remembering that you didn't update the vis library. Why?

**Comment by carlos-lopez-tecnativa** [comment]
> @carlos-lopez-tecnativa I'm now remembering that you didn't update the vis library. Why?

Sorry, I forgot, please see https://github.com/OCA/web/pull/2972

**Pull request merged**
