### PR TITLE
[12.0][add] web_session_allow_public

### PR DESCRIPTION
**Pull request by fredzamoabg**
add web_session_allow_public from https://github.com/OCA/web/pull/402

### CODE REVIEW

**Comment by tafaRU** [comment]
@fredzamoabg I'm not clear what this module is intended for. Could you please provide more info?
I'd also ask for some feedback from @OCA/web-maintainers.

**Comment by simahawk** [comment]
Not sure it's still the case for v12 but here's the historical issue on v11: https://github.com/odoo/odoo/issues/24289

**Comment by simahawk** [comment]
regarding the name and the position, it's probably more suitable for OCA/server-auth as `auth_public_session` or something similar.

**Comment by fredzamoabg** [comment]
> regarding the name and the position, it's probably more suitable for OCA/server-auth as `auth_public_session` or something similar.

moved to https://github.com/OCA/server-auth/pull/313.

**Pull request closed without merging**
