### PR TITLE
[14.0][MIG] web_widget_image_webcam

### PR DESCRIPTION
**Pull request by legalsylvain**
Finish : https://github.com/OCA/web/pull/2195

- cherry-picked : @alexis-via work 
- fix jslint : https://github.com/OCA/web/commit/7807b0e92f4204c64eaef330584c01904cc509be
- move lib file in the correct folder : https://github.com/OCA/web/commit/78394cae6996faa258f521b9966d5cbb29c88bb3

Tested locally. It works great.

@bosd, @alexis-via, @bud-e, @ivantodorovich

review welcome.

### CODE REVIEW

**Comment by bosd** [comment]
Functional test on Deepin Linux;
Tested with Chrome and "browser" both programs gave me this error:
image

There was no pop=up asking for permissions to use the webcam.

Tested the webcam from another program it is working fine.

**Comment by legalsylvain** [comment]
@bosd : Thanks for your test ! Could you try with your failing env (chrome....) to use the V12 version. 
I'd like to know if it's a regression.
Thanks !

**Comment by bud-e** [comment]
@legalsylvain @bosd ,
I didn't go through the code but tested it in Chrome & it's working. But As it was mentioned in the README, that webcam will only work with secure sites (with `https://` only).

Ref. https://github.com/OCA/web/pull/2323/files#diff-696553b5b2479b8a1471c93d570a099fe02a8bc7ce8de8ec04ec162ea2bb50a7R41

So, I add Runboat URL in `Insecure origins treated as secure` section of the `chrome://flags/` settings. & I can see that website now asking the webcam permission & module working as expected.

I think that `web_widget_image_webcam.flash_fallback_mode` is not working anymore in the latest browsers... (https://github.com/OCA/web/pull/2323/files#diff-696553b5b2479b8a1471c93d570a099fe02a8bc7ce8de8ec04ec162ea2bb50a7R48)

Thanks @legalsylvain for your effort of migrating this module.

**Comment by bosd** [comment]
@bud-e 
Thanks for this additional info. I am ashamed to say. I did not read the readme.

In my failling chrome (I went to the basic test of the js library.
Try the basic demo: https://pixlcore.com/demos/webcamjs/demos/basic.html
Over there it is working and asking me for camera access.

> add Runboat URL in Insecure origins treated as secure section of the chrome://flags/ settings. & I can see that website now asking the webcam permission & module working as expected.

Works for me as well, now it captures images from the webcam (It did not ask for permissions).
(Works now in both browsers, turns out both browsers are chrome based)

Did not test the flash versions, as it appears the flash demos are not working on my system.
Prefer to use the js version as well.

Thanks for migrating!
LGTM now :+1

**Comment by bud-e** [comment]
@bosd , Yes I think the flash mode is not working anymore.

**Review by bud-e — APPROVED** [review]
LGTM!

**Comment by bosd** [comment]
> @bosd , Yes I think the flash mode is not working anymore.

Do you think it is something to test before meeging this PR?

Edit: Never mind, tried yet nother system, the flash demo of the js library is not working. (Partly due to lack of flash support for those browsers). Possibly the functionality is there, if someone still needs it. I'm fine by merging this in the current state.

**Review by bosd — APPROVED** [review]

**Comment by bud-e** [comment]
@bosd, I think it's fine if the flash mode not working. As new browsers don't support flash. 

But we can still keep that configuration in the module so, someone with an older browser or with flash support can easily use that flash fallback mode.

Just for info.. Google already removed flash support from Chrome - https://www.blog.google/products/chrome/saying-goodbye-flash-chrome/

**Comment by legalsylvain** [comment]
Thanks for all the greats information. (I didn't read the readme too !)

/ocabot merge patch

**Pull request merged**
