### PR TITLE
[14.0][MIG] web_widget_datepicker_fulloptions

### PR DESCRIPTION
**Pull request by HekkiMelody**
Migration from 12.0 using https://github.com/OCA/odoo-module-migrator

Nothing to do, module works out of the box.

ping @quentinDupont

### CODE REVIEW

**Review by bosd — APPROVED** [review]
LGTM 👍

**Review by quentinDupont — APPROVED** [review]
Code reviewed :+1:  
Not tested

Thank you !!

**Comment by bosd** [comment]
So canb this one be merged?

**Comment by HekkiMelody** [comment]
@OCA/web-maintainers :pray: :pray: :pray:

**Comment by legalsylvain** [comment]
thanks for porting this module.

/ocabot merge nobump

**Pull request merged**
