### PR TITLE
[MIG] web_calendar_slot_duration: migration to 13.0

### PR DESCRIPTION
**Pull request by yajo**
Most normal migration ever.

@Tecnativa TT30987

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
diff review. LGTM. (no test)

**Review by chienandalu — APPROVED** [review]
Tested! :+1:

**Review by pedrobaeza — APPROVED** [review]
Although there's not too much pre-commit stuff, please next time separate both commits.

**Pull request merged**
