### PR TITLE
New module 'web_one2many_list_action'

### PR DESCRIPTION
**Pull request by codingforfun**
Enable tree_but_open interface to be used for list views embedded into
form views for one2many relational fields.
My use case was to delegate opening a pop up view to another model. I.e. the line model is kind of a proxy where I do want to open the target model on click instead of the line model. 
But I think this can be useful for other circumstances too.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Wow, this is amazing! I'll review it soon. Thanks for bringing this to OCA.

@oihane @anajuaristi, this is a clean alternative to https://github.com/odoomrp/odoomrp-utils/tree/8.0/sale_order_line_form_button, which has some problems I pointed out as you know.

**Comment by codingforfun** [comment]
I hacked this very fast for my use case, so testing and input how this applies to the general case is very welcome.
One issue I already know is that actions with `target='new'` always open in edit mode (we discussed this here: https://github.com/OCA/web/issues/314) This is only loose related and not caused by my code, but you should be aware of if you want to do things similar to my use case and open popups of other models. I solved this by adding special flags into the computed action.

**Comment by hbrunn** [comment]
:+1:

**Comment by OSguard** [comment]
:+1: now can be merged

**Pull request merged**
