### PR TITLE
add "web_list_html_widget" module

### PR DESCRIPTION
**Pull request by OSguard**
This module allows to use a widget="html" for fields in
list(tree) views.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Some questions:
- It is possible/advisable to sanitize first HTML?
- Have you tried to propose this to core?

Regards

**Comment by OSguard** [comment]
It is the same behavior as HTML.fields in form view
And the module is from the pre Github times, as our MR was ignored, so we build modules if it is possible to ship it ;) - And yet not retry again.

**Comment by hbrunn** [comment]
I think the warning in the manifest suffices. If you deal with anything the remotely comes from external input, you'll wrap this in a function field that does the sanitizing I'd say. :+1:

**Comment by max3903** [comment]
Can you generate the translation file so the description could be translated ?

Otherwise LGTM

**Comment by OSguard** [comment]
done

**Pull request merged**
