### PR TITLE
13.0 mig web decimal numpad dot

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Comment by sbidoul** [comment]
@emagdalenaC2i yes, in the travis log you can see the two pre-commit checks failing, as well as the diff that is needed to get it green. Fixing them is easy:

- install [pre-commit](https://pre-commit.com/) (you need to do this once)
- run `pre-commit run --all-files`, which will apply the necessary code formatting fixes
- commit and push the changes

To have these checks done automatically for you, run `pre-commit install` after cloning any 13.0 branch to install the pre-commit hook. The checks (and many automatic fixes) will be done for you when you commit.

I also recommend to configure Black in your favorite editor.

**Comment by pedrobaeza** [comment]
Please check JS warnings:
```
/home/travis/build/OCA/web/web_dialog_size/static/src/js/web_dialog_size.js
   2:1   warning  Expected indentation of 4 spaces but found 0         indent
   4:1   warning  Expected indentation of 4 spaces but found 0         indent
   5:1   warning  Expected indentation of 4 spaces but found 0         indent
   7:1   warning  Expected indentation of 4 spaces but found 0         indent
   8:1   warning  Expected indentation of 8 spaces but found 4         indent
   9:1   warning  Expected indentation of 8 spaces but found 4         indent
  10:1   warning  Expected indentation of 4 spaces but found 0         indent
  12:1   warning  Expected indentation of 4 spaces but found 0         indent
  14:1   warning  Expected indentation of 8 spaces but found 4         indent
  15:1   warning  Expected indentation of 12 spaces but found 8        indent
  16:1   warning  Expected indentation of 12 spaces but found 8        indent
  17:1   warning  This line has a length of 92. Maximum allowed is 88  max-len
  17:1   warning  Expected indentation of 16 spaces but found 12       indent
  18:1   warning  This line has a length of 91. Maximum allowed is 88  max-len
  18:1   warning  Expected indentation of 16 spaces but found 12       indent
  19:1   warning  Expected indentation of 16 spaces but found 12       indent
  19:40  warning  Missing space before function parentheses            space-before-function-paren
  20:1   warning  Expected indentation of 20 spaces but found 16       indent
  21:1   warning  Expected indentation of 24 spaces but found 20       indent
  22:1   warning  Expected indentation of 20 spaces but found 16       indent
  23:1   warning  Expected indentation of 24 spaces but found 20       indent
  24:1   warning  Expected indentation of 20 spaces but found 16       indent
  25:1   warning  Expected indentation of 16 spaces but found 12       indent
  26:1   warning  Expected indentation of 12 spaces but found 8        indent
  27:1   warning  Expected indentation of 8 spaces but found 4         indent
  29:1   warning  Expected indentation of 8 spaces but found 4         indent
  29:21  warning  Missing space before function parentheses            space-before-function-paren
  29:22  warning  'handler' is defined but never used                  no-unused-vars
  30:1   warning  Expected indentation of 12 spaces but found 8        indent
  30:64  warning  Missing space before function parentheses            space-before-function-paren
  30:66  warning  Missing space before opening brace                   space-before-blocks
  31:1   warning  Expected indentation of 16 spaces but found 12       indent
  32:1   warning  Expected indentation of 20 spaces but found 16       indent
  33:1   warning  Expected indentation of 24 spaces but found 20       indent
  34:1   warning  Expected indentation of 24 spaces but found 20       indent
  34:34  warning  Missing trailing comma                               comma-dangle
  35:1   warning  Expected indentation of 20 spaces but found 16       indent
  36:1   warning  Expected indentation of 16 spaces but found 12       indent
  37:1   warning  Expected indentation of 12 spaces but found 8        indent
  38:1   warning  Expected indentation of 8 spaces but found 4         indent
  40:1   warning  Expected indentation of 8 spaces but found 4         indent
  40:20  warning  Missing space before function parentheses            space-before-function-paren
  41:1   warning  Expected indentation of 12 spaces but found 8        indent
  42:1   warning  Expected indentation of 16 spaces but found 12       indent
  43:1   warning  Expected indentation of 16 spaces but found 12       indent
  44:1   warning  Expected indentation of 20 spaces but found 16       indent
  45:1   warning  Expected indentation of 16 spaces but found 12       indent
  46:1   warning  Expected indentation of 12 spaces but found 8        indent
  47:1   warning  Expected indentation of 12 spaces but found 8        indent
  48:1   warning  Expected indentation of 8 spaces but found 4         indent
  50:1   warning  Expected indentation of 8 spaces but found 4         indent
  50:25  warning  Missing space before function parentheses            space-before-function-paren
  51:1   warning  Expected indentation of 12 spaces but found 8        indent
  52:1   warning  Expected indentation of 12 spaces but found 8        indent
  53:1   warning  Expected indentation of 12 spaces but found 8        indent
  54:1   warning  Expected indentation of 12 spaces but found 8        indent
  55:1   warning  Expected indentation of 8 spaces but found 4         indent
  57:1   warning  Expected indentation of 8 spaces but found 4         indent
  57:23  warning  Missing space before function parentheses            space-before-function-paren
  58:1   warning  Expected indentation of 12 spaces but found 8        indent
  59:1   warning  Expected indentation of 12 spaces but found 8        indent
  60:1   warning  Expected indentation of 12 spaces but found 8        indent
  61:1   warning  Expected indentation of 12 spaces but found 8        indent
  62:1   warning  Expected indentation of 8 spaces but found 4         indent
  64:1   warning  Expected indentation of 4 spaces but found 0         indent
/home/travis/build/OCA/web/web_environment_ribbon/static/src/js/ribbon.js
   8:54  warning  Missing space before function parentheses            space-before-function-paren
   9:1   warning  Expected indentation of 4 spaces but found 0         indent
  15:28  warning  Missing space before function parentheses            space-before-function-paren
  56:1   warning  This line has a length of 99. Maximum allowed is 88  max-len
```

**Comment by emagdalenaC2i** [comment]
@pedrobaeza those warnings are from other PR already merged web_dialog_size and web_environment_ribbon

**Comment by pedrobaeza** [comment]
I spit out the log without seeing, sorry. I will check for removing then in another PR.

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot and working correctly

**Review by chienandalu — APPROVED** [review]
:+1: Tested in runbot. Thanks :)

**Comment by emagdalenaC2i** [comment]
@pedrobaeza It seems that the warnings of web_dialog_size and web_environment_ribbon must be fixed before merging this PR

I have created a PR #1403 to fix web_environment_ribbon.
Do I create another one to fix web_dialog_size?

**Comment by pedrobaeza** [comment]
Please do it in the same, or we will have the same problem, or even do it here in a separate commit.

**Comment by pedrobaeza** [comment]
Can you include `web_dialog_size` fix here as well?

**Comment by emagdalenaC2i** [comment]
@pedrobaeza a little doubt abbout this warning in /home/travis/build/OCA/web/web_dialog_size/static/src/js/web_dialog_size.js:
`29:22  warning  'handler' is defined but never used                  no-unused-vars`

Should I delete the variable?
```javascript        opened: function() {
            return this._super.apply(this, arguments).then(function (){
                if (this.$modal) {
                    this.$modal.draggable({
                        handle: '.modal-header',
                        helper: false
                    });
                }
            }.bind(this));
        },
```

or use it anywhere

In addition, there are now two new warnings from another module merged

```/home/travis/build/OCA/web/web_responsive/static/src/js/web_responsive.js
  101:22  warning  'n' is never reassigned. Use 'const' instead  prefer-const
  173:36  warning  'Promise' is not defined                      no-undef```

**Comment by pedrobaeza** [comment]
Remove it.

And the new warnings are mandatory? I merged yesterday without problem...

**Comment by emagdalenaC2i** [comment]
I send two more PR yesterday before pre-commit changes and there are green in travis... This one, no

**Comment by sbidoul** [comment]
eslint checks are optional. What failed was black wanting to format the manifest.
Note here https://travis-ci.org/OCA/web/jobs/597501292#L253-L260 how the black check is marked failed while the eslint check passed (albeit with a lot of warnings).

**Comment by emagdalenaC2i** [comment]
@sbidoul So, is there something I should fix or is that something to fix with travis?

@pedrobaeza there is only 1 warning that I don't know how to fix in /home/travis/build/OCA/web/web_responsive/static/src/js/web_responsive.js

`173:36  warning  'Promise' is not defined                      no-undef`

This is the code:
```javascript        /**
         * Schedule a search on current menu items.
         */
        _searchMenusSchedule: function () {
            this._search_def = new Promise((resolve) => {
                setTimeout(resolve, 50);
            });
            this._search_def.then(this._searchMenus.bind(this));
        },```

**Comment by pedrobaeza** [comment]
@emagdalenaC2i you have to run pre-commit in local like stated in https://odoo-community.org/blog/the-oca-blog-1/post/black-isort-pre-commit-97

**Comment by pedrobaeza** [comment]
Let's merge this and clarify the doubt elsewhere: /ocabot merge

@Tardo can you please check the warning in web_responsive?

**Pull request merged**
