### PR TITLE
[16.0][MIG] web_disable_export_group: Migration to 16.0

### PR DESCRIPTION
**Pull request by chienandalu**
please review @CarlosRoca13 @victoralmau 

cc @Tecnativa TT45881

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Tests are red

/ocabot migration web_disable_export_group

**Comment by chienandalu** [comment]
Fixed

**Review by CarlosRoca13 — APPROVED** [review]
:+1:

**Review by victoralmau — APPROVED** [review]
Code and functional review.

**Pull request merged**
