### PR TITLE
[17.0][FIX] web_m2x_options: add fieldColor to KanbanMany2ManyTagsAvatarField

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Fixes new issued identified in https://github.com/OCA/web/issues/2934

Based on same fixes applied on https://github.com/OCA/web/pull/2921

CC @CRogos @chienandalu @pedrobaeza

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
I wonder if there's a generic way to do that, as I already stated before.

**Review by chienandalu — COMMENTED** [review]
Maybe we could avoid some boilerplate code using a common object. Somethin like:

```js
const fieldColorProps = {
    fieldColor: {type: String, optional: true},
    fieldColorOptions: {type: Object, optional: true},
}

//...

WhatEverField.props = {
    ...WhatEverField.props,
    ...fieldColorProps,
};

**Comment by JordiMForgeFlow** [comment]
> Maybe we could avoid some boilerplate code using a common object. Somethin like:
> 
> ```js
> const fieldColorProps = {
>     fieldColor: {type: String, optional: true},
>     fieldColorOptions: {type: Object, optional: true},
> }
> 
> //...
> 
> WhatEverField.props = {
>     ...WhatEverField.props,
>     ...fieldColorProps,
> };
> ```

Makes sense, changes applied! :)

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
This is still requiring to inherit each widget. I meant a way to do it on the "base", but anyway, let's merge meanwhile:

/ocabot merge patch

**Pull request merged**
