### PR TITLE
[10.0][MIG] web_widget_datepicker_options: Upgrade to v10

### PR DESCRIPTION
**Pull request by kellylougheed**
Forward port of #546

### CODE REVIEW

**Comment by kellylougheed** [comment]
Got mixed up with the versioning, but this branch will eventually be used to upgrade web_widget_datepicker_options to v10.

**Review by simahawk — APPROVED** [review]
code review: LGTM

**Comment by lasley** [comment]
@kellylougheed - Please double check that all changes from #546 are present here, this looks different in a few ways.

**Comment by kellylougheed** [comment]
@lasley I updated the Readme -- that was the only difference I saw

**Comment by lasley** [comment]
There are still changes missing. I recommend resetting this to 10.0, performing the format-patch to bring the 9.0 version in, then cherry picking your upgrade to v10 commit.

**Comment by kellylougheed** [comment]
@lasley OK, I reset to 10.0, did format-patch, and added my v10 upgrade.

**Pull request closed without merging**
