### PR TITLE
[13.0][MIG] web_tree_image_tooltip

### PR DESCRIPTION
**Pull request by phuctranfxvn**

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
I tested on my personal computer. It works :

image

Thank you for this migration

**Review by nikul-serpentcs — APPROVED** [review]
Code review LGTM :+1:

**Comment by tarteo** [comment]
@phuctranerp Can you have a look at the linting errors: https://travis-ci.org/github/OCA/web/jobs/712921214#L518

**Comment by fla-subteno-it** [comment]
all check are green, it is possible to merge ?

**Comment by pedrobaeza** [comment]
It seems not over latest branch. The author of the PR must rebase the branch and check the errors.

**Pull request merged**
