### PR TITLE
[FIX] [8.0] - fix README.rst errors across the repository

### PR DESCRIPTION
**Pull request by nedaszilinskas**

### CODE REVIEW

**Review by yajo — DISMISSED** [review]
If you take the time to fix READMEs, please do it with the new split readme system introduced in https://github.com/OCA/maintainer-tools/pull/339.

Thanks!

**Comment by simahawk** [comment]
@Yajo isn't it too much overhead for ppl fixing a broken repo on an ooooooooold version? :innocent:

**Comment by okuryan** [comment]
@pedrobaeza @simahawk @Yajo This is only about making build green. So we can contribute in another PR. I cannot dedicated so much of dev time to fixing everything. We have also production projects. I agree with @simahawk  that it is "too much".

**Comment by pedrobaeza** [comment]
Yes, we can't abuse of the favor that Nedas is doing us cleaning the branch.

Nedas, there are still 2 errors to fix (they don't appear in red, but they are blocking):
```
web_menu_autohide/__openerp__.py:21: [C8101(manifest-required-author), ] Missing author required "Odoo Community Association (OCA)" in manifest file
web_action_conditionable/__openerp__.py:3: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
```

cc @moylop260 why they don't appear in red?

**Comment by pedrobaeza** [comment]
Fast-tracking as it turns the branch green

**Pull request merged**
