### PR TITLE
[16.0][MIG] web_calendar_slot_duration: Migration to 16.0

### PR DESCRIPTION
**Pull request by norlinhenrik**

### CODE REVIEW

**Comment by norlinhenrik** [comment]
This module is good.
Tests fail because of `web_domain_field`.

**Comment by CRogos** [comment]
Are you sure this is still working? Either I do something wrong, or it is not working. 
I've also realized that the Odoo default calendar snap duration changed from 30 min to 15 min.

image
Have you tried something else than 0:15:00?

**Comment by norlinhenrik** [comment]
So that's what this module is for. I agree, the action context does not change the behavior in the calendar view in 16.0.

I did a basic migration because it is a dependency for `calendar/resource_booking`.

**Comment by pedrobaeza** [comment]
Superseded by #2646

**Pull request closed without merging**
