### PR TITLE
[11.0][MIG] web_widget_dropdown_dynamic: Backport to 11.0

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@tarteo @pedrobaeza as I have no knowledge of v11, please take a look at this. Tests pass and it seems working on Runbot

**Review by ghost — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@tarteo @pedrobaeza it's a simple and working backport, if possible please merge

**Pull request merged**
