### PR TITLE
[IMP] Added draggable support to dialogs

### PR DESCRIPTION
**Pull request by wpichler**

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Tested on runbot. Works great!

**Comment by JordiBForgeFlow** [comment]
cc @lreficent @mreficent

**Comment by JordiBForgeFlow** [comment]
cc @hveficent Can you review?

**Review by bealdav — APPROVED** [review]
Just tested, really works.

Thanks a lot

**Comment by HviorForgeFlow** [comment]
It works fine. :+1:

**Comment by JordiBForgeFlow** [comment]
@wpichler Can you update the readme to add this new capability?

**Comment by wpichler** [comment]
good idea - done

**Review by LoisRForgeFlow — APPROVED** [review]
Tested on runbot, Looks great! :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Awesome! :heart_eyes:

**Pull request merged**
