### PR TITLE
[9.0][web_duplicate_visibility][web_readonly_bypass] Fix Travis.

### PR DESCRIPTION
**Pull request by yajo**
Travis was broken due to these addons. Now they run their tests always, tests work, and BTW some cosmetic upgrades landed too.

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Wow, good JS test revamping!

**Review by lasley — APPROVED** [review]
Travis is freaking out on the `push` check, but the error is related to git so it seems it's unrelated. 👍

**Comment by pedrobaeza** [comment]
Let's merge this one for fixing the branch.

**Comment by lasley** [comment]
image

**Comment by pedrobaeza** [comment]
hehe, that's because I trust in you review :laughing:

**Pull request merged**
