### PR TITLE
[14.0][IMP] web_environment_ribbon: hide the ribbon when navigation is in use

### PR DESCRIPTION
**Pull request by HekkiMelody**
Backport of fce9051d581cc3cbae86313c73e00ea4f65c62b4

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't like this option, and more to backport it to a version that already works the other way.

**Comment by legalsylvain** [comment]
> I don't like this option,

Could you elaborate ? #2311 introduces that change on last 16 release.

**Review by ap-wtioit — APPROVED** [review]
Tested on Firefox and Chrome, works in 14.0 as well.

@pedrobaeza and i had a little discussion about this in #2055, starting here https://github.com/OCA/web/pull/2055#issuecomment-1021935032, i still think if there is a problem with some code a separate issue should be opened to make it easier to work on a solution and not spreading the discussion on multiple PRs

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
As discussed.

I didn't have time to redact such "issue" asked by Andreas, but what it can't be is to backport something debatable.

**Comment by HekkiMelody** [comment]
I thought it was a nice QoL improvement but I didn't realize it was a controversial change and I can definitely live without it. I do not mind closing the PR.

**Pull request closed without merging**
