### PR TITLE
[14.0][IMP] web_responsive: Add chatter position view_users_form

### PR DESCRIPTION
**Pull request by andreampiovesana**
Allow to change chatter position also in base.view_users_form

### CODE REVIEW

**Review by marcelofrare — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
Please pass pre-commit. You can install it locally in an easy way through `pipx`.

**Comment by pedrobaeza** [comment]
Great, can you squash both commits into one for proceeding with the merge?

**Review by tarteo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Aborting. @dreispt please check whole thread before triggering mergings. I'm asking a squash because having 2 commits for this little thing is too much. I didn't want to put a "Requested changes" for not being very harsh, but this shouldn't be merged.

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
For avoiding misunderstandings, I put this for asking for the squashing.

**Comment by dreispt** [comment]
Hello Pedro, I agree. I won’t also trigger a merge if I see a Needs Fixing or a Question tag.

--dr

**Review by robyf70 — APPROVED** [review]
LGTM

**Comment by Maralai** [comment]
Hello! I would love it if this was merged into the main branch is that something that will happen soon? It just seems logical to have this field be something that can be managed by an Admin for each user as well as allowing the user themselves to manage it.

**Comment by dreispt** [comment]
Superseded by #2229

**Pull request closed without merging**
