### PR TITLE
[16.0][FIX] Fix problem when uninstalling web_dark_mode

### PR DESCRIPTION
**Pull request by fkantelberg**
This PR should fix the error when uninstalling web_dark_mode mentioned in #2402

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the fix. Please respect commit message structure:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

Something like `[FIX] web_dark_mode: Fix uninstallation`

**Comment by fkantelberg** [comment]
@pedrobaeza Thanks for the reminder

**Comment by fkantelberg** [comment]
@legalsylvain Would you review the fix for your issue?

**Review by legalsylvain — APPROVED** [review]
Thanks ! 

/ocabot merge patch

**Pull request merged**
