### PR TITLE
[IMP] web_responsive: Add search feature

### PR DESCRIPTION
**Pull request by lasley**
* Add feature to search menus in the app drawer

Forward port of #714

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
There's an error here loading JS when trying on runbot

**Comment by pedrobaeza** [comment]
Travis is failing now.

**Comment by lasley** [comment]
Woot I was actually going for a fail. Was worried why the last one was showing as green. Got busy with the upgrade thing though and forgot to hop back here. Will nail today

**Comment by pedrobaeza** [comment]
What is the status of this?

**Comment by yajo** [comment]
Continuing in #1007.

**Pull request closed without merging**
