### PR TITLE
[MIG] web_domain_field: Migration to 15.0

### PR DESCRIPTION
**Pull request by rven**

### CODE REVIEW

**Review by JoanMForgeFlow — APPROVED** [review]

**Review by JoanMForgeFlow — APPROVED** [review]
Functional usage is working!
LGTM.

**Review by JoanMForgeFlow — APPROVED** [review]
LGTM!

**Comment by Maralai** [comment]
Thank you guys for the work on this. I was able to download the branch referenced on this pull request, copy the addon directory to my addons folder and get this addon installed and working without issue on my v15.0 project. I appreciate all of the OCA's members' work more and more as I continue my Odoo journey. Looking forward to pulling the latest from v15.0 when this addon migration is complete.

**Comment by albertopoljak** [comment]
Hi,

I've updated this module myself recently and encountered js erorr when testing it on my odoo.sh test database.
Now I saw that you've updated the module too so I though I'd try yours too but unfortunately the same thing happened.
Looks like we did the same thing from what I can see (just updated manifest to include js instead of previous views way).

I'm not sure if this error will help you understand the problem (sure as hell doesn't for me) but here it is:

```
TypeError: second argument to Function.prototype.apply must be an array
    eval_domains/<@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:3849:20
    _.forEach@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:151:566
    _.mixin/</_.prototype[name]@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:208:526
    eval_domains@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:3846:265
    pyeval@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:3871:24
    stringToArray@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:3813:147
    _getDomain@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:4652:98
    _search@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:4261:508
    _bindAutoComplete/source/<@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:4250:280
    _.forEach@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:151:566
    source@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:4250:75
    _search@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:2621:140
    $.widget/</proxiedPrototype[prop]@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:2133:159
    search@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:2621:13
    $.widget/</proxiedPrototype[prop]@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:2133:159
    $.widget.bridge/$.fn[name]/<@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:2138:31
    each@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:1484:170
    each@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:1475:192
    $.widget.bridge/$.fn[name]@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:2135:327
    _toggleAutoComplete@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:4258:313
    _onInputClick@https://REDACTED.dev.odoo.com/web/assets/847-7e713b9/web.assets_backend.min.js:4268:6
    proxy/<@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:4851:11
    dispatch@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:1785:447
    add/elemData.handle@https://REDACTED.dev.odoo.com/web/assets/843-8e535c0/web.assets_common.min.js:1771:166
```

Problem is that locally it works,but on odoo.sh I get that error.
The part that's confusing is that I have the same custom addons locally as I have online (git makes sure of that,but
I also double checked web_domain_version (15.0.1.0.0), Odoo version (Odoo 15.0+e (Enterprise Edition) ) and web dependency version (15.0.1.0))
So I am sure that I have the same addons on both sides. Next I checked the database and I even manually uploaded my local database to odoo.sh and still the same error.

I've managed to recreate the issue locally -using field as domain but web_domain_field is uninstalled.
But I can clearly see that on odoo.sh it is installed.

Any idea what might be happening? Or any tips I could do to get closer to the root of the problem?

**Comment by rven** [comment]
@Maralai if you approve these changes the sooner it gets incorporated into the 15.0 branch ;-)

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by JoanMForgeFlow** [comment]
@pedrobaeza could you please merge this module?
Thanks in advance.

**Comment by Maralai** [comment]
> @Maralai if you approve these changes the sooner it gets incorporated into the 15.0 branch ;-)

I wish I knew how! Lol it's it as easy as APPROVED?

**Pull request merged**
