### PR TITLE
[12.0][FIX] web_timeline correct readme

### PR DESCRIPTION
**Pull request by andreampiovesana**
typo error

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
True, thanks

**Comment by pedrobaeza** [comment]
Fast-tracking this:

/ocabot merge patch

**Comment by alepit** [comment]
Please can you check if this feature is still present in v.13 and v.14?
I can't find it on readme files

**Comment by pedrobaeza** [comment]
Such options seems to not be on upper versions

**Pull request merged**
