### PR TITLE
7.0 web percent

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Ported from https://code.launchpad.net/~therp-nl/web-addons/7.0-add_percentage_widget/+merge/217602

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
To answer @pedrobaeza's comments on the Launchpad merge proposal: the conversion mechamisn that you requested assume that the value of a percentage field is between 0.0 and 1.0. Now, exactly for lack of a widget that does these conversions, existing percentage fields are more likely to be a value between 0 and 100. That makes this widget backwards incompatible with these columns.

**Comment by pedrobaeza** [comment]
I think the best name for the module would be _web_widget_percentage_ to indicate that it's a widget (we discussed this before).

What I said was to have the widget UI with a value between 0 to 100, and internally return a value between 0.0 to 1.0 to be consistent with the base functionality. Discount fields in sales and accounting don't follow this rule, but we can include a widget option to configure the range if you want.

**Comment by ovnicraft** [comment]
@StefanRijnhart now the widget just add % at the field ? conversion to [0,1] and validation [0,100] does not support yet ?

**Comment by StefanRijnhart** [comment]
A widget option as suggested by @Pedrobaeza is in fact a good idea. I'll think about that (sorry for losing track of this one).

**Comment by pedrobaeza** [comment]
@StefanRijnhart, are you going to continue this PR?

**Comment by pedrobaeza** [comment]
No answer, so closing. Feel free to reopen if needed.

**Pull request closed without merging**
