### PR TITLE
[16.0][MIG] web_group_expand: Migration to 16.0

### PR DESCRIPTION
**Pull request by mayank-ptl**

### CODE REVIEW

**Review by CRogos — APPROVED** [review]
LGTM code + test

Minor issue regarding the migration guide in the commit history:
Missing: "[IMP] web_group_expand: pre-commit stuff"

**Review by MohamedOsman7 — APPROVED** [review]

**Review by tarteo — CHANGES_REQUESTED** [review]
Thanks for your work! I tested this locally, there seems to be an issue with the pagination. 
If you for example group modules (Apps) by name you get multiple pages of groups:

image

If I go to the next page: 
image

And then expand all groups by clicking the button it goes to the first page again.

**Comment by dipak-shah** [comment]
I appreciated the efforts behind this migration. It seems like it's been stuck since May. any chance to get this merged? @tarteo @MohamedOsman7 @mayank-ptl

**Comment by CRogos** [comment]
@tarteo do you have an idea how to fix this?

**Comment by juliam3991** [comment]
Hello all ,  I want to extend my gratitude for the hard work and dedication that the team has put into this endeavor. Could you kindly provide an update on the current status of the migration process? 

Thank you once again!

**Comment by PaolaEras** [comment]
Runbot

**Comment by pedrobaeza** [comment]
Superseded by #2599

**Pull request closed without merging**
