### PR TITLE
[FIX][11.0][web_dialog_size] Fix discard

### PR DESCRIPTION
**Pull request by angelmoya**
On any form, if you edit and try to discard you get an error

check this lines:
https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/views/basic/basic_controller.js#L82
https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/core/dialog.js#L235

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's already #927. Isn't the same?

**Comment by angelmoya** [comment]
No, my PR  fix error when discard any form in edit mode.

The other PR is for fix discard modal.

**Comment by qtheuret** [comment]
Thanks @angelmoya to have fixed this issue.

**Comment by rafaelbn** [comment]
Thanks @angelmoya ! Is useful too put a tittle with the module name like [FIX][11.0][web_dialog_size] :smile:

**Review by rafaelbn — APPROVED** [review]
Functionally tested in runbot :+1:

**Comment by angelmoya** [comment]
Thanks @rafaelbn it was a quick fix directly on github, I fixed the tittle

**Review by pedrobaeza — APPROVED** [review]
It lacks module version bump, but as there's 2 consecutive PRs, I amend it after merging both

**Pull request merged**
