### PR TITLE
   [14.0] [MIG] web_widget_mpld3_chart

### PR DESCRIPTION
**Pull request by GenisPForgeFlow**
Standard migration to v14.0

@LoisRForgeFlow

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews

**Comment by hkapatel-initos** [comment]
It would be great if someone could review here.

**Comment by hkapatel-initos** [comment]
@LoisRForgeFlow and @AdriaGForgeFlow it would be nice if you both can review here.

**Comment by hkapatel-initos** [comment]
It would be great if someone could review here.

**Review by TDu — APPROVED** [review]

**Comment by hkapatel-initos** [comment]
@JordiBForgeFlow can we try to merge it?

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza I lost my superpowers. Can you merge?

**Comment by pedrobaeza** [comment]
I don't have all of them, but do this one:

/ocabot merge nobump

**Pull request merged**
