### PR TITLE
[IMP] rid off delay for deffered obj

### PR DESCRIPTION
**Pull request by i-vyshnevska**
backport improvements from comment https://github.com/OCA/web/pull/1341#discussion_r307946835

### CODE REVIEW

**Review by simahawk — APPROVED** [review]

**Review by Tardo — APPROVED** [review]
LGTM :+1:, code review + tested on runbot

**Comment by sbidoul** [comment]
@simahawk I'm investigating why it failed.

**Comment by sbidoul** [comment]
Trying again with https://github.com/OCA/oca-github-bot/pull/52/commits/f77e9be54ba9b3372b4970e121ef780f36c87942

/ocabot merge patch

**Pull request closed without merging**
