### PR TITLE
[IMP]web_readonly_bypass:migrated from 9 to 10

### PR DESCRIPTION
**Pull request by hemnanikalpana**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check CLA and linter errors:

```
************* Module web_readonly_bypass
web_readonly_bypass/static/src/js/readonly_bypass.js:1: [W7903(javascript-lint), ] Use the function form of "use strict".
web_readonly_bypass/static/src/js/readonly_bypass.js:24: [W7903(javascript-lint), ] Use '===' to compare with 'false'.
web_readonly_bypass/static/src/js/readonly_bypass.js:46: [W7903(javascript-lint), ] ['readonly_fields'] is better written in dot notation.
web_readonly_bypass/static/src/js/readonly_bypass.js:47: [W7903(javascript-lint), ] ['readonly_by_pass'] is better written in dot notation.
web_readonly_bypass/static/src/js/readonly_bypass.js:48: [W7903(javascript-lint), ] ['readonly_by_pass'] is better written in dot notation.
web_readonly_bypass/static/src/js/readonly_bypass.js:50: [W7903(javascript-lint), ] ['readonly_by_pass'] is better written in dot notation.
web_readonly_bypass/static/src/js/readonly_bypass.js:3: [W7903(javascript-lint), ] 'openerp' is not defined.
web_readonly_bypass/static/src/js/readonly_bypass.js:23: [W7903(javascript-lint), ] '$' is not defined.
web_readonly_bypass/static/src/js/readonly_bypass.js:29: [W7903(javascript-lint), ] '$' is not defined.
web_readonly_bypass/static/src/js/readonly_bypass.js:49: [W7903(javascript-lint), ] '$' is not defined.
web_readonly_bypass/static/src/js/readonly_bypass.js:48: [W7903(javascript-lint), ] '_' is not defined.
web_readonly_bypass/static/src/js/readonly_bypass.js:50: [W7903(javascript-lint), ] '_' is not defined.
web_readonly_bypass/static/test/web_readonly_bypass.js:65: [W7903(javascript-lint), ] Missing semicolon.
web_readonly_bypass/static/test/web_readonly_bypass.js:116: [W7903(javascript-lint), ] Missing semicolon.
web_readonly_bypass/views/readonly_bypass.xml:1: [W7908(missing-newline-extrafiles), ]  Missing newline
************* Module web_readonly_bypass.__manifest__
web_readonly_bypass/__manifest__.py:25: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
web_readonly_bypass/__manifest__.py:25: [C8106(manifest-version-format), ] Wrong Version Format "9.0.1.0.0" in manifest file. Regex to match: "(10.0)\.\d+\.\d+\.\d+"
```

**Comment by hemnanikalpana** [comment]
@pedrobaeza I have followed all the steps and mailed signed CLA at cla@odoo-community.org. Let me know what else need to be done?

**Comment by pedrobaeza** [comment]
OK, checking the CLA right now. We also need that you fix current linter errors that I put before.

**Comment by hemnanikalpana** [comment]
sure I will work on that and once I will fix, will make a pull request.

Thank you so much for consideration.

_Thank You and Regards,Kalpana Hemnani_
_Contact : 7405477141_
_E-mail : hemnani.kalpana@gmail.com hemnani.kalpana@gmail.com_

**Comment by lasley** [comment]
@hemnanikalpana No need for another pull request, just push your new code and it will show up here 😄 

Whenever you're done, just let us know.

**Comment by hemnanikalpana** [comment]
@pedrobaeza I have made fix of manifest file(licencing terms), but not able to re produce the js and xml errors, and I am able to perform the functionality as expected.

if you facing error, can you provide me steps to reproduce. commit id : f54cd8cf4baf8356e880923b3acf20c1719ea627

**Comment by pedrobaeza** [comment]
They are not errors, but stylistic guidelines, like PEP8, but for JS. Please read the error and follow the text, like changing the [] by dot notation, that means if you have `variable[field]`, then use `variable.field`.

**Comment by BT-fgarbely** [comment]
Hello @hemnanikalpana 

What is the status of this pull request?
I also need the module web_readonly_bypass in version 10 (enterprise).

Thanks for your feedback.

Regards,

**Comment by hemnanikalpana** [comment]
Hello @BT-fgarbely ,

I successfully installed and using the above module successfully in version 10, the warnings/error showing in above build is violating Travis, but which is coming from the existing code only.

Regards,
Kalpana Hemnani

**Comment by pedrobaeza** [comment]
Are you not going to finish the PR then? Coming or not from existing code, a contribution consists on adjusting code for passing existing checks and tests. If it's apparently working, but a check or test fails, maybe later this will impact in something.

**Comment by hemnanikalpana** [comment]
Hi @pedrobaeza ,

I tried, but java script is out of my scope, and these are just Travis warnings as per my best knowledge, still give me some time, I will get back to this.

**Comment by pedrobaeza** [comment]
Any news with this?

**Comment by blutecsolutions** [comment]
Greetings! Any updates on this migration?
Thanks

**Comment by pedrobaeza** [comment]
It seems that there's no interest in continuing the PR. Things to do:

- Repair Travis.
- Make this to work.

**Comment by blutecsolutions** [comment]
I would appreciate an update on this, if you need help i can get our developers involved :)
Thanks @pedrobaeza & @hemnanikalpana

**Comment by pedrobaeza** [comment]
Hi, @blutecsolutions, then it's needed a developer that fixes the 2 points I put the other day.

**Comment by hemnanikalpana** [comment]
Hello Pedro,

It is working successfully, but I am not able to repair Travis. Sorry for
late response. I am available for any other help needed


* <https://drive.google.com/open?id=0B_EzIrqUt0IVMWVERzBJQlYxWGc>*

*KALPANA HEMNANI*
------------------------------

[image: ?]

+91 7405477141

[image: ?]

hemnani.kalpana1 [image: ?] <https://in.linkedin.com/in/kalpanahemnani>




<https://in.linkedin.com/in/kalpanahemnani>

**Comment by lasley** [comment]
@hemnanikalpana I'm confused on why you can't fix Travis - it's a piece of cake error IMO:

> web_readonly_bypass/__manifest__.py:9:80: E501 line too long (82 > 79 characters)

https://travis-ci.org/OCA/web/jobs/196901929#L500

**Comment by simahawk** [comment]
@pedrobaeza I'd say you can close this. I'm carry on here https://github.com/OCA/web/pull/743

**Pull request closed without merging**
