### PR TITLE
[FIX] web_group_expand : Fixed the behavior on tree view fixes #580

### LINKED ISSUE #580: [8.0] : web_group_expand : Error on TREE view
The problem appears on Tree view, with multiple clicks:
screenshot from 2017-03-09 18 38 13
screenshot from 2017-03-09 18 37 33
screenshot from 2017-03-09 18 33 54

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @oihane

**Comment by JayVora-SerpentCS** [comment]
Please respond to merge.

**Comment by pedrobaeza** [comment]
@JayVora-SerpentCS if you want your PR to be merged, review other's PRs and ask in exchange to review yours.

**Comment by JayVora-SerpentCS** [comment]
Sure, this way sharing the workload.

**Review by oihane — APPROVED** [review]
LGTM :+1:

**Comment by claudiagn** [comment]
LGTM! :+1:

**Pull request closed without merging**
