### PR TITLE
Symlink pwa -> web_pwa

### PR DESCRIPTION
**Pull request by eLBati**
See https://github.com/OCA/web/pull/1612#pullrequestreview-424150398

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by bealdav — APPROVED** [review]

**Review by legalsylvain — APPROVED** [review]
@eLBati could you just mention in the readme file, the reason of this link ? 

otherwise, :+1: . Thanks again for this usefull module.

**Comment by eLBati** [comment]
@legalsylvain thanks, done

**Comment by legalsylvain** [comment]
thanks ! 

/ocabot merge patch

**Comment by legalsylvain** [comment]
@sbidoul : do you think we should fix this PR, or the bot / oca-gen-addon-readme (ignoring symbolic link for example ?)

**Comment by sbidoul** [comment]
Can we do without the symlink? That has always caused troubles when we
tried that before.

Le jeu. 4 juin 2020 à 15:57, Sylvain LE GAL <notifications@github.com> a
écrit :

**Comment by legalsylvain** [comment]
> Can we do without the symlink?

The symlink is the workaround to have the new  module OCA/web/web_pwa available on apps.odoo.com. (conflict with this module https://apps.odoo.com/apps/modules/12.0/web_pwa/)

So just a nice to have IMO.

**Comment by sbidoul** [comment]
Yeah but why not naming the module pwa in the first place?

Le jeu. 4 juin 2020 à 16:05, Sylvain LE GAL <notifications@github.com> a
écrit :

**Comment by legalsylvain** [comment]
> Yeah but why not naming the module pwa in the first place?

;-)

because https://github.com/OCA/web/pull/1612

See also https://github.com/OCA/web/pull/1602#issuecomment-638689627 for the automated solution ;-)

**Comment by sbidoul** [comment]
Then `web_responsive_pwa`, whatever. But the symlink will give the impression to most of our tooling that we have two addons: pwa and web_pwa. That will be a nightmare to manage, trust me. We had it once with bank_statement_import(_oca), and a lot of things behaved badly.

**Comment by legalsylvain** [comment]
@elbati, regarding last @sbidoul remark I propose you to close this PR.

**Comment by eLBati** [comment]
Closing.

So, I propose to reopen https://github.com/OCA/web/pull/1612 and discuss there

**Comment by pedrobaeza** [comment]
As said, I don't want that renaming and I don't care about the other module. OCA module is unique, that is what matters. We have a similar problem with `l10n_es_aeat_sii`, that was taken by an individual, but at the end, we are working the same without problems: OCA apps store is indexing the good one properly, and everyone that goes to the GitHub repository see also the proper one.

**Comment by eLBati** [comment]
https://github.com/OCA/web/pull/1612#issuecomment-639014241

**Pull request closed without merging**
