### PR TITLE
[13.0][ADD] web_orgchart_library

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
This PR adds the module web_orgchart_library which adds the OrgChart library (https://github.com/dabeng/OrgChart) to be used in other modules.

cc ~ @ForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Are you going to use this library for more than one module? Even so, not sure this should be bundled separately from the main module using it. You know also the possible version conflicts.

**Comment by AdriaGForgeFlow** [comment]
> Are you going to use this library for more than one module? Even so, not sure this should be bundled separately from the main module using it. You know also the possible version conflicts.

The main problem is that, in my case, I'm going to use this in a module I plan to include in OCA/hr (hr_orgchart_overview) and that repository has the lib folder included in the .gitignore. How should I do this in your opinion?

**Comment by pedrobaeza** [comment]
You should change the gitignore, or at least do it less restrictive (like only /lib). Who put initially that ignore? Maybe it was a mistake. Any way, Odoo already contains an HR org chart. Do you know it?

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza The Odoo org chart is a little bit simpler, we want a "full" org chart overview for the whole company in only one screen

**Comment by pedrobaeza** [comment]
OK, but I think you should put it in the same module then.

**Comment by AdriaGForgeFlow** [comment]
Closing this PR, library was included inside the module as requested by @pedrobaeza in here [OCA/hr/pull/849](https://github.com/OCA/hr/pull/849)

**Pull request closed without merging**
