### PR TITLE
[13.0][FIX] web_responsive: Show history section in discuss mobile

### LINKED ISSUE #1939: [13.0][BUG] web_responsive: History tab in Discuss module is always empty!
Hi everyone,

If you go to Discuss module and click on History tab - it is always empty (if you look on desktop - there is content present).

### PR DESCRIPTION
**Pull request by Tardo**
Fix #1939

cc @tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@vbezl  please review

**Comment by vbezl** [comment]
@pedrobaeza Thanks! Looks good! When will it be merged into 13.0?

**Comment by pedrobaeza** [comment]
Well, the regular process is that you approve the pull request, but let's fast-track it:

/ocabot merge minor

@Tardo please fw-port it to v14.

**Comment by vbezl** [comment]
@pedrobaeza wow, that was fast :) Thanks again!

**Pull request merged**
