### PR TITLE
[MIG] web_advanced_search_wildcard: Migration to 14.0

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
@max3903 
Tested on [runbot](http://3466535-1828-5211ed.runbot2.odoo-community.org/web#action=178&model=crm.lead&view_type=list&cids=&menu_id=124) but wildcard option not visible?

**Comment by CasVissers-360ERP** [comment]
@max3903 Any updates on this PR?

**Comment by MeetKD** [comment]
Is this pr still in WIP?

**Comment by alexis-via** [comment]
I tried this PR, but the advanced search doesn't show "Starts With" and other additional filters on a char field, cf my screenshot:

wildcard_missing_startswith

**Comment by fshah-initos** [comment]
Hi, @max3903 I've tested the module but the wildcard option is not visible and shows the same issue as @alexis-via attached screenshot.

**Comment by alexis-via** [comment]
If you need something that works in v14, you can try this patch on odoo: https://people.via.ecp.fr/~alexis/odoo-v14-advanced_search_startswith.diff
FYI, I tried to include this feature in Odoo master ; I received a lot of support/reviews but it was eventually rejected https://github.com/odoo/odoo/pull/80146

**Comment by andreampiovesana** [comment]
can you fix ?

**Comment by ikapasi-initos** [comment]
@max3903 Any updates on this PR?

**Pull request closed without merging**
