### PR TITLE
12.0 mig web_decimal_numpad_dot

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Teste on runbot. You can squash some commits. Thanks! :wink:

**Review by cristinamartinrod — APPROVED** [review]
LGTM 👍🏻

**Comment by pedrobaeza** [comment]
@ernestotejeda please install maintainer-tools for generate the README directly in the PR, or at least don't empty README file, as it's double diff (one removing the content, and another adding it again very similar).

**Review by pedrobaeza — COMMENTED** [review]
Working as expected, but waiting for the generated README.

**Pull request merged**
