### PR TITLE
[15.0][MIG] web_pwa_oca: Migration to 15.0

### PR DESCRIPTION
**Pull request by ieski**
Standard Migration for version 15.0

### CODE REVIEW

**Review by tarteo — CHANGES_REQUESTED** [review]
Tested locally, JS is not migrated:

image

Also manifest is not loading:
image

**Comment by saxomanu** [comment]
Hi ! Is this PR Still alive ? 
Can i do something to help ?

**Comment by sergio-teruel** [comment]
@tarteo the manifest are not loading due to your instance starts with a multi db setting anable... 
Start your odoo instance as single database mode... 
--db-filter = foo
--database= foo

**Comment by pedrobaeza** [comment]
Superseded by #2310

**Pull request closed without merging**
