### PR TITLE
[BUILD] web_responsive: resign as maintainer

### PR DESCRIPTION
**Pull request by yajo**

### CODE REVIEW

**Comment by yajo** [comment]
fast-tracking

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Just for reference, `[BUILD]` is not a valid tag: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#71commit-message

**Comment by yajo** [comment]
Sorry, I got confused with conventional commits, which I'm more used to lately. In any case, I don't see any commit tag that fits this kind of change.

**Comment by pedrobaeza** [comment]
It's true that this doesn't fit in any of the existing one, but `[BUILD]` doesn't seem also the best one. We can propose to add one. Suggestions? I think in `[CONF]`, `[MANT]` or `[OCA]`.

**Comment by yajo** [comment]
In the world of conventional commits you'd use `docs`, `chore` or `build`. The standard is based on the one pioneered by AngularJS, and they removed `chore` in 2017 because it was often abused (https://github.com/conventional-commits/conventionalcommits.org/issues/303).

I think we can stick with `[BUILD]` (after all, changes on maintainership affect to the development cycle, which is generally a good fit for `[BUILD]`) or `[CHORE]`.

**Comment by pedrobaeza** [comment]
For me that's counter-intuitive, but if others see it natural, no special problem for me.

**Comment by simahawk** [comment]
FWIW to me is just an "update". Nothing more. Don't get too complicated w/ these tags guys! :smile:

**Comment by pedrobaeza** [comment]
`[UPD]` is also a non valid tag according current guidelines.

**Pull request merged**
