### PR TITLE
[FIX] web_widget_numeric_step: always display on touch screens; avoid layout jumping otherwise

### PR DESCRIPTION
**Pull request by yajo**
Before this patch:
- On a tablet, buttons wouldn't display (big screen; can't hover).
- On a PC, fields would make layout jumps while hovering.

  Before: 

  https://github.com/OCA/web/assets/973709/2d21cbe9-2723-49eb-a735-263555b66d0d
  
  
  
  
  After: 

  https://github.com/OCA/web/assets/973709/c0b32934-ca9a-486a-9e8f-ecb4d83a8ce7

@moduon MT-4472

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
LGTM,. thank you @yajo

**Review by rafaelbn — APPROVED** [review]
👍🏼 Thank you!

**Comment by sergio-teruel** [comment]
Why adopt de module??

**Comment by rafaelbn** [comment]
Hello @sergio-teruel , we add our selves because we will maintain the module. Original author @quentinDupont or other contributors can add it selves as maintainers in a simple PR but module actually don't have any maintainer defined.

The OCA must grow in contributors and neither maintain nor decrease. The modules require more maintainers. You can discuss it here too https://github.com/OCA/maintainer-tools/issues/592

**Comment by quentinDupont** [comment]
Hi there!
For your information, I haven't started working on version 16 yet + I don't feel comfortable enough with JS code to be the main maintainer, as the code has been greatly improved by people other than myself ;)
thanks for keeping this module alive, excellent additions with this PR!

**Pull request merged**
