### PR TITLE
[16.0][MIG] web_notify: migrate to 16.0

### PR DESCRIPTION
**Pull request by tuanle96**
web_notify: enhancement

Update JS source with Owl Mode.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by tuanle96** [comment]
Hi @pedrobaeza , 

So I have to migrate to 15.0  before migrate to 16.0 version because this module not migrated for 15.0 version yet?

**Comment by pedrobaeza** [comment]
No, please read full text. Anyway, the PR for 15.0 already exists, and you will see that there are deep changes to do.

**Comment by pedrobaeza** [comment]
The PR should contain all the commit history, and the version finally merged in v15 contains also an important refactoring to ES6, so it's worth to start again the process. I'm closing this for not confusing reviewers.

**Comment by pramadhana92** [comment]
> Download files for odoo version 15 and edit web_notify\static\src\js\services\notification_services.esm.js ` /** @odoo-module **/ import { browser } from "@web/core/browser/browser"; import { registry } from "@web/core/registry";
> 
> export const webNotificationService = { dependencies: ["bus_service", "notification"],
> 
> ```
> start(env, { bus_service, notification }) {
>     let webNotifTimeouts = {};
>            
>     bus_service.addEventListener('notification', ({ detail: notifications }) => {            
>         for (const {payload, type} of notifications) {
>             if (type === "web.notify") {
>                 displaywebNotification(payload);
>             }
>         }            
>         
>     });                     
>     /**
>      * Displays the web notification on user's screen
>      */
> 
>     function displaywebNotification(notifications) {
>         Object.values(webNotifTimeouts).forEach((notif) =>
>             browser.clearTimeout(notif)
>         );
>         webNotifTimeouts = {};
> 
>         notifications.forEach(function (notif) {
>             browser.setTimeout(function () {
>                 notification.add(notif.message, {
>                     title: notif.title,
>                     type: notif.type,
>                     sticky: notif.sticky,
>                     className: notif.className,
>                 });
>             });
>         });
>     }
> 
> },
> ```
> 
> };
> 
> registry.category("services").add("webNotification", webNotificationService); `

hello @Popeye1001,

I tried to install web_notify v15 in odoo 16 it is not working.

I tried to use your solution, but it's not working too..

Is there any way to display pop-up notification without using return?

Thanks

**Pull request closed without merging**
