### PR TITLE
[13.0][mig] web_send_message_popup

### PR DESCRIPTION
**Pull request by StephaneMangin**

### CODE REVIEW

**Review by dsolanki-initos — COMMENTED** [review]
Code review No major change

**Review by dsolanki-initos — APPROVED** [review]

**Comment by dsolanki-initos** [comment]
Cna someone add reviews here?

**Comment by dsolanki-initos** [comment]
It would be great if we could reviews and merge the PR ASAP.

**Comment by dsolanki-initos** [comment]
It would be great if we could reviews and merge the PR ASAP.

**Comment by MeetKD** [comment]
Can you please check why checks are failing?

**Comment by StephaneMangin** [comment]
All checks are green, ready for approval

**Review by MeetKD — APPROVED** [review]
Tested functionally works fine.

**Comment by dsolanki-initos** [comment]
Seems that PR is ready to merge. IT would be great if maintainers could merge it.

**Comment by dsolanki-initos** [comment]
Seems that PR is ready to merge. IT would be great if maintainers could merge it.

**Review by gaikaz — APPROVED** [review]
LGTM, tested on runbot

**Comment by dsolanki-initos** [comment]
It would be nice if the maintainers could merge the PR

**Comment by StephaneMangin** [comment]
> It would be nice if the maintainers could merge the PR

Hi @pedrobaeza could you do it ?

**Pull request merged**
