### PR TITLE
[MIG] web_editor_background_color: Migrate to v11

### PR DESCRIPTION
**Pull request by yajo**
- Better JS framework usage.
- Split readme.
- Update bootstrap-colorpicker lib.
- Remove image, serve it from GitHub CDN.

It looks like this:

peek 11-10-2018 12-48

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@cristinamartinrod please review

**Comment by pedrobaeza** [comment]
Trying on runbot, full colour pallete is not shown in the picker selector:

seleccion_004

Am I doing something wrong?

**Comment by cristinamartinrod** [comment]
Awesome functionality! Was the same to me. Works fine but I can't see full color palette preview. (tested in chrome)

**Comment by yajo** [comment]
Weird, somehow Odoo's less was prefixing the base64 image url with the addon path... :confused: 

Well, it uses now the upstream precompiled distributed CSS sources, which should just work.

I have to squash before merging.

**Comment by pedrobaeza** [comment]
Error on manifest version:
```
web_editor_background_color/__manifest__.py:3: [C8106(manifest-version-format), ] Wrong Version Format "10.0.1.0.0" in manifest file. Regex to match: "(11\.0)\.\d+\.\d+\.\d+$"
```

**Comment by pedrobaeza** [comment]
The palette is now correct, so fixing Travis is :+1: for me.

**Comment by yajo** [comment]
Fixed now. I squashed all migration stuff.

**Comment by pedrobaeza** [comment]
Merging as the comment is attended.

**Pull request merged**
