### PR TITLE
[13.0][FIX] web_view_calendar_list fix viewType

### PR DESCRIPTION
**Pull request by Martronic-SA**
Add viewType attribute otherwise it can break the default calendar and doesn't select the correct view button.

### CODE REVIEW

**Comment by etobella** [comment]
Can you rebase? It makes sense

**Review by olgamarcocb — APPROVED** [review]
Thanks it was necessary for 14 too, So I added your commits on #2121

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
@Martronic-SA If you rebase and fix pre-commit we can proceed with merge :wink:

**Comment by etobella** [comment]
Superseeded

**Pull request closed without merging**
