### PR TITLE
[12.0][MIG] web_sheet_full_width

### PR DESCRIPTION
**Pull request by vvrossem**
As I've read in https://github.com/OCA/web/issues/1048, this module is now integrated in `web_responsive`.
However, a client used `web_sheet_full_width` in 9.0. In 12.0, he doesn't wish all the features that are included in `web_responsive`, hence the migration.

### CODE REVIEW

**Review by lfreeke — APPROVED** [review]
Functional test

**Review by yostashiro — APPROVED** [review]
LGTM 👍

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by andreampiovesana — APPROVED** [review]
go

**Comment by vvrossem** [comment]
Thank you @dreispt for having merged this PR :)

**Pull request merged**
