### PR TITLE
[15.0][IMP] web_responsive: public message chatter color

### PR DESCRIPTION
**Pull request by chienandalu**
We give a color clue to the users so they can better tell if they're sending an internal note or a public message.

Peek 08-09-2023 10-10

Dislaimer: we use the `has()` pseudo class mainly because is simpler to implement and the support is quite extended right now. Even Firefox will catch up soon (now it has support behing a config flag).

So users with compatible browser will enjoy it, while others will just stay as they were.

cc @Tecnativa TT44953

please review @carolinafernandez-tecnativa @pedrobaeza

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Do you know how much time to get it into Firefox?

**Comment by pedrobaeza** [comment]
This should go into the README, including the GIF.

**Comment by chienandalu** [comment]
> This should go into the README, including the GIF.

Done

**Review by carolinafernandez-tecnativa — APPROVED** [review]
Worked perfectly

**Comment by chienandalu** [comment]
> Do you know how much time to get it into Firefox?

I think they're already late on their schedule :smile: https://connect.mozilla.org/t5/ideas/when-is-has-css-selector-going-to-be-fully-implemented-in/idi-p/23794

**Review by pedrobaeza — APPROVED** [review]
Although I'm not able to enjoy yet (being a Firefox user), it's a good addition.

**Comment by pedrobaeza** [comment]
/ocabot merge patch

Now to v16.

**Pull request merged**
