### PR TITLE
[MIG] web_advanced_search: Migrate to v12

### PR DESCRIPTION
**Pull request by yajo**
Routine migration.

@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot

**Comment by pedrobaeza** [comment]
@tarteo may I ask your review?

**Review by chienandalu — APPROVED** [review]
:+1: Tested on runbot

Would it be possible in the advanced filter to have the button to the selected records dialog?

**Review by alexey-pelykh — APPROVED** [review]
Runbot 👍

**Comment by yajo** [comment]
Merge please.

**Comment by pedrobaeza** [comment]
What about the question:

> Would it be possible in the advanced filter to have the button to the selected records dialog?

**Comment by yajo** [comment]
If I understand the question fine, the answer is that it depends on the domain selector widget itself, not on the search feature here.

You can see some improvements being made for v11 in https://github.com/OCA/web/pull/1200.

**Pull request merged**
