### PR TITLE
[12.0][FIX] web_widget_x2many_2d_matrix: total cell calculation

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Addresses #1160

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@tarteo @anandkansagra please review

**Review by anandkansagra — APPROVED** [review]
LGTM :+1:

**Review by simahawk — APPROVED** [review]
doh! :man_facepalming: 

LG, pls update version number by 0.0.1

**Comment by alexey-pelykh** [comment]
Bumped version

**Comment by tarteo** [comment]
:+1: Thanks!!

**Pull request merged**
