### PR TITLE
[14.0][FIX] web_timeline: order group_by field (and update JS lib)

### PR DESCRIPTION
**Pull request by alexis-via**
Fix bug #2266: before this fix, the lines of the timeline view were always sorted by alphabetical order, ignoring the native order of the model on which the group_by field points to.

Fix duplicate entries in the 'fields' argument when the 'colors' parameters uses the same field in multiple conditions.

### CODE REVIEW

**Comment by alexis-via** [comment]
I took the opportunity of this PR to update the JS lib to a newer version. But it's not linked to the bug ; the bug fix is in the first commit.

**Review by chienandalu — COMMENTED** [review]
@CarlosRoca13 can you check it?

**Review by CarlosRoca13 — APPROVED** [review]
I will add the changes to the migration to 15.0

Thanks!

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
I have manually added a timeline view in project and use `date_deadline` as starting time for making it work, and I found some weird behavior:

Peek 03-08-2022 18-28

**Comment by CarlosRoca13** [comment]
Hmm I did not found that problems... I have done the test with project_timeline in local machine 
Peek 04-08-2022 06-42

**Comment by pedrobaeza** [comment]
I see that you are not moving any task to "Unassigned". Can you try?

**Comment by CarlosRoca13** [comment]
unassigned

No problems found...

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
OK, then it should be the hot change I did on runbot. Let's merge it:

/ocabot merge major

**Comment by chienandalu** [comment]
Could it be a browser specific compatibility issue?

**Comment by pedrobaeza** [comment]
I was doing the tests on Firefox. I will test it again when merged.

**Pull request merged**
