### PR TITLE
Updated module version tooltip support

### PR DESCRIPTION
**Pull request by jpaquete**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Same comment as the other PR.

**Comment by jpaquete** [comment]
Sorry man. New to github. I did not figure out how to include in the same
request

Em 24/12/2017 16:49, "Pedro M. Baeza" <notifications@github.com> escreveu:

**Comment by pedrobaeza** [comment]
You have to handle the branch locally in your system with git.

**Comment by jpaquete** [comment]
[image: Inline image 1]

Hi Pedro, I have forked the project to my account made the changes (3
files), commited and pushed to my repository. I am on pycharm. Is this the
way to correctly make the pull request ? Please confirm. Tks
Merry C. :)

**Comment by pedrobaeza** [comment]
Well, not really, as you have to push to your branch called `patch-1`, as that's the branch you made the pull request against.

**Comment by jpaquete** [comment]
Like this ?...

[image: Inline image 1]

**Comment by jpaquete** [comment]
ok figured it out, files already updated. My issue was cloning from the
patch-1
Tks
jp

**Pull request closed without merging**
