### PR TITLE
[16.0][MIG] web_widget_datepicker_fulloptions

### PR DESCRIPTION
**Pull request by quentinDupont**
- Migration of `web_widget_datepicker_fulloptions`  from 14.0 to 16.0
- Migrate to owl
- :warning: Clearing field doesn't work anymore because there is a left 'todo' in Odoo core code
- Commit to review : https://github.com/OCA/web/pull/2738/commits/ab82cd7402d904573ca710a47b991a73751d95e2

Before / After

image

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot migration web_widget_datepicker_fulloptions 

CC : @aleuffre, @bosd

**Review by bosd — APPROVED** [review]
Funcitonal test, LGTM

**Review by flotho — APPROVED** [review]
thanks,
LGTM

**Comment by legalsylvain** [comment]
/ocabot merge nobump

Thanks for the migration and the reviews.

**Pull request merged**
