### PR TITLE
Fix inconsistency of line length between flake8 and black

### PR DESCRIPTION
**Pull request by jcdrubay**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Comment by jcdrubay** [comment]
That was a fast approval :) Thanks @bealdav

**Comment by simahawk** [comment]
@sbidoul it seems this is present in all repos: do we need a global update?

**Comment by sbidoul** [comment]
No, the current version (80, ignore E501, enable B950) is correct.
See https://github.com/psf/black#line-length for more details.

@jcdrubay do you experience specific issues with the current setup?

**Comment by simahawk** [comment]
@sbidoul but what's the deal of keeping it like this? It can be confusing. If changing it is harmless then I'd sync those numbers. :thinking:

**Comment by sbidoul** [comment]
@simahawk I can't explain better than the Black doc does.

Also, regarding these linter files, when they are deployed on a branch, If it ain't broke don't fix it, to avoid unnecessary noise :) Improvements can be discussed in OCA/maintainer-quality-tools to prepare for the next version.

[updated] OCA/maintainer-quality-tools, not OCA/maitnainer-tools

**Comment by simahawk** [comment]
@sbidoul for me is fine, what could help is a simple comment on top of the file. @jcdrubay could you open an issue on https://github.com/OCA/maintainer-tools ?

**Comment by jcdrubay** [comment]
@sbidoul Yes I am facing an issue but on a non OCA repository for a piece of code which is:

- split on several lines with each line less than 80 characters before running pre-commit
- re-formatted by black into a single line of more than 80 characters.
- then I get a pre-commit exit 1 due to flake8

Example:

Before pre-commit,
```
                {
                    "time_log_type_id":
                        training_task.program_id.time_log_type_id.id,
                }
```

After pre-commit, the line is 85 characters long:
```
                {
                    "time_log_type_id": training_task.program_id.time_log_type_id.id,
                }
```

**Comment by jcdrubay** [comment]
Closed in favor of: https://github.com/OCA/maintainer-tools/issues/448

**Comment by sbidoul** [comment]
@jcdrubay sorry, I meant OCA/maintainer-**quality**-tools, that's where the sample files are.

For you specific case, can you check if you have the flake8-bugbear pluging. It's the one that allows occasional increased line lenght:

https://github.com/OCA/maintainer-quality-tools/blob/ce728c28d14afc983c0b58081cd92243c0f9085e/sample_files/pre-commit-13.0/.pre-commit-config.yaml#L61

**Comment by jcdrubay** [comment]
@sbidoul

Thanks for the pointers.

Issue has been created on maintainers-quality-tools and closed on maintainer-tools.

Even with the flake8-bugbear plugin, I still get some issues.
Seems to be due to this: https://github.com/psf/black/issues/1161

I still believe that the issue is valid for consistency, but at a much lower priority.

**Pull request closed without merging**
