### PR TITLE
[FIX] Destroy the editor properly. This prevents errors like

### PR DESCRIPTION
**Pull request by StefanRijnhart**
'this.getWindow(...).$ is undefined' in Firefox after closing
a popup containing an editor instance.
was opened in a popup window.

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
@StefanRijnhart this causes problems with x2many popup forms, as they are used for topics in the newsletter module (just create a new topic, fill in some text, and try to save that):

```
TypeError: a is null
http://localhost:9911/web_ckeditor4/static/lib/ckeditor/ckeditor.js:789
```

I suspect there's still some event listener lurking somewhere causing this behavior

**Comment by StefanRijnhart** [comment]
@hbrunn Thanks. Solved in https://github.com/StefanRijnhart/web/commit/a190e20a6584407b4b92244a17bb67de28b54421, which contains https://github.com/ckeditor/ckeditor-dev/pull/200 which in its uglified form translate to two occurrences of **if(a)**. This is now documented in the updated README.rst.

**Comment by hbrunn** [comment]
:+1:

**Comment by mad-odoo** [comment]
Hello,
One more issue found while destroying editor: #350 

Thanks

**Pull request merged**
