### PR TITLE
[MIG] web_tree_many2one_clickable: Migration to 15.0

### PR DESCRIPTION
**Pull request by XanderDeMatteis**

### CODE REVIEW

**Review by marylla — APPROVED** [review]
I made a functional review.
It works as expected. :+1:

**Review by jcdrubay — COMMENTED** [review]
Tested on Runboat, it works fine, but not in the list view of Customer Invoice. Maybe there is some conflict with some custom js on that view?

`<tree string="Invoices" js_class="account_tree" decoration-info="state == 'draft'" decoration-muted="state == 'cancel'" sample="1">`

**Comment by pedrobaeza** [comment]
That view is a special one, the same as the lines of sales / purchases / invoices that requires a glue module for adding the option there, so it's out of the scope of this migration. It can be included in the ROADMAP though.

**Comment by pedrobaeza** [comment]
@XanderDeMatteis please fix pre-commit

**Comment by pfranck** [comment]
Any help needed ?

**Comment by pedrobaeza** [comment]
Superseded by #2388

**Pull request closed without merging**
