### PR TITLE
add fa.po

### PR DESCRIPTION
**Pull request by saeed-raeisi**
add persian support

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi thanks for contributing ! you can not add translation this way in OCA. You should do it via weblate. 
Please ping us if you don't know how to do.
Regards 
Closing in the meantime

**Comment by saeed-raeisi** [comment]
Hi
Thanks for following up
There is no Persian language in this project
https://translation.odoo-community.org/projects/web-14-0/web-14-0-web_responsive/

**Comment by saeed-raeisi** [comment]
Permission Denied
Insufficient privileges to display this page.

**Comment by pedrobaeza** [comment]
https://odoo-community.org/page/translate

**Pull request closed without merging**
