### PR TITLE
[16.0][MIG] web_company_color

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Standard migration to v16.

@ForgeFlow

### CODE REVIEW

**Review by antoniocanovas — APPROVED** [review]
Functional review OK !!

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Oh, wait, there's already #2404 and #2449

Please review if one of them are correct, as they have priority.

**Comment by pedrobaeza** [comment]
I cancelled the action, so this shouldn't be merged yet...

**Pull request merged**
