### PR TITLE
[ADD] Add new module to allow the removal of the Duplicate button on …

### PR DESCRIPTION
**Pull request by rousseldenis**
…every form

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @rousseldenis thanks! But please follow the templates given in https://github.com/OCA/maintainer-tools

**Comment by sbidoul** [comment]
Or, easier, use https://pypi.python.org/pypi/bobtemplates.odoo

**Comment by hbrunn** [comment]
are you aware of https://github.com/OCA/web/tree/9.0/web_duplicate_visibility ? I'd propose to backport that, or at least use the same module and attribute name in your addon. Having addons with different names in different versions is quite a pain.

Then also pylint is unhappy: https://travis-ci.org/OCA/web/jobs/142483436#L440

**Comment by rousseldenis** [comment]
Ok, I'll do the backport of the v9 module.

**Comment by rousseldenis** [comment]
@sbidoul I'll have a look at bobtemplate and try it for the next one :smile:

**Pull request closed without merging**
