### PR TITLE
[16.0] [MIG] `web_chatter_position`

### PR DESCRIPTION
**Pull request by ivantodorovich**
Superseeds https://github.com/OCA/web/pull/2391

NOTE: In core, the chatter is now responsive. For this reason this module value may need to be checked. You may not need it. However, if you do, note that there's a new `auto` setting set by default.

### CODE REVIEW

**Comment by liebana** [comment]
Functional tested, in mobile and in desktop.

For me, its approved, thank you very much.

**Review by legalsylvain — APPROVED** [review]
Functional test. No code review.

note : @liebana : you can approve via github. So the bot knows that the PR has 2 approvals...

**Comment by kikopeiro** [comment]
Seems work fine!

Please update the readme file as it would not be possible to change chatter settings on the fly

**Review by liebana — APPROVED** [review]

**Comment by ivantodorovich** [comment]
I did change the `readme/DESCRIPTION.rst` and `readme/USAGE.rst`
The actual readme will automatically be re-genereated by ocabot upon merge

**Review by sebalix — APPROVED** [review]

**Review by CasVissers-360ERP — APPROVED** [review]
Miss the button to easily switch in the header, but can understand is has been removed.

**Review by bvanjeelharia — COMMENTED** [review]
Its not working as expected when you zoom in for sided chatter, the scrollbar shows up above the html editor.Please check the screenshot
Screenshot from 2023-03-02 16-08-00

**Review by marcelofrare — APPROVED** [review]
Functional OK for me. Thanks!

**Pull request merged**
