### PR TITLE
[IMP] web_environment_ribbon: conditional ribbon

### PR DESCRIPTION
**Pull request by sylvainc**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you document your changes in the README?

**Comment by lmignon** [comment]
@sylvainc Good idea but can you put a default value for the new parameter and document your change as asked by @pedrobaeza

**Comment by rafaelbn** [comment]
Could you explain me the purpose? I can try to test it

**Comment by sylvainc** [comment]
Hello,

Sorry for my late reply,

@pedrobaeza : changes are now documented in the README.rst file

@lmignon : I have added a default parameter for the ribbon's name

@rafaelbn : As documented in the README.rst,  you can now change the ribbon's name ("TEST") by editing the default configuration parameter "ribbon.name" , to hide the ribbon, set this parameter to "False"  or delete it.

Thanks

**Comment by laetitia-gangloff** [comment]
Nice :+1:  (functional)

**Comment by tafaRU** [comment]
So useful, thanks! :+1:

**Comment by pedrobaeza** [comment]
You have to remove known issues section, because it's what you have done!

**Comment by pedrobaeza** [comment]
Tested on runbot, :+1:

I'll merge when the other remark is done

**Comment by sylvainc** [comment]
@pedrobaeza : roadmap section of the README.rst updated accordingly

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
