### PR TITLE
[16.0][MIG] web_pwa_oca

### PR DESCRIPTION
**Pull request by MBSALDarwish**
Migration  "web_pwa_oca" to v16.0
Add Arabic translation

### CODE REVIEW

**Comment by MBSALDarwish** [comment]
I don't know what the issue with pre-commit
I tried it locally but remained the same

**Comment by CarlosRoca13** [comment]
You haven’t applied the pre-commit reformatting. You can do so by using the command `pre-commit run -a` and pushing the changes it applies.

**Comment by CarlosRoca13** [comment]
Furthermore, you haven’t maintained the change history. To do it, you can follow the migration guide for version 16.0: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

**Comment by pedrobaeza** [comment]
Incorrect PR. Try #2640 instead.

**Pull request closed without merging**
