### PR TITLE
[FIX] Page reference not exists if name was slugified

### PR DESCRIPTION
**Pull request by suriyan**

### CODE REVIEW

**Comment by moylop260** [comment]
:+1: (wo test it)

**Comment by hbrunn** [comment]
@suriyan are you going to hand in a CLA?

**Comment by suriyan** [comment]
@hbrunn I've sent back signed CLA since 09/09/2015.

**Comment by pedrobaeza** [comment]
I have checked the CLA and is OK.

:+1: for this and I merge.

Thanks for the contribution.

**Comment by hbrunn** [comment]
@suriyan my thanks too. Could you inquire why the CLA bot thinks you don't have signed the CLA? This will speed up subsequent PRs.

**Pull request merged**
