### PR TITLE
[17.0][MIG] web_widget_bokeh_chart

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Migration to 17.0

Supersede #2805 

Also updates bokeh lib from 3.1.1 to 3.4.1 to include the fix like #2793 

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
cc @robyf70 you might want to review this one

**Review by robyf70 — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
