### PR TITLE
[FIX] web_timeline: Change vis-timeline library import

### PR DESCRIPTION
**Pull request by Tardo**
Fixes https://github.com/OCA/project/pull/656 reported issues

cc @tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Weird thing, didn't you remove minified sources before?

**Comment by mikolodz** [comment]
@Tardo After your commit, a view is loading, but while opening and then while trying to move the view (click, hold, move), I'm getting this error:

```
TypeError: undefined is not an object (evaluating 'datas._data[key]')

https://xxx/web/content/1556-70a2fde/web.assets_backend.js:3933
Traceback:
draw_dependencies@https://xxx/web/content/1556-70a2fde/web.assets_backend.js:3933:98
draw_canvas@https://xxx/web/content/1556-70a2fde/web.assets_backend.js:3932:527
https://xxx/web/content/1556-70a2fde/web.assets_backend.js:3932:428
https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:17815:28
[native code]
_redraw@https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:24837:30
_redraw@https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:37574:35
_redraw@[native code]
https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:23787:26
https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:17815:28
[native code]
_redraw@https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:24827:34
_redraw@https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:37574:35
_redraw@[native code]
https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:23787:26
https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:17815:28
[native code]
_redraw@https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:24827:34
_redraw@https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:37574:35
_redraw@[native code]
https://xxx/web_timeline/static/lib/vis-timeline/vis-timeline-graph2d.js:9006:12
```

odoo-13-web-timeline-error

**Comment by Tardo** [comment]
@pedrobaeza not for javascript... i think that the main problem was a "collision" between xml import and javascript import.

**Comment by pedrobaeza** [comment]
Merging as confirmed in project_timeline module.

/ocabot merge minor

**Pull request merged**
