### PR TITLE
[16.0][FIX] web_refresher: new record refresh

### PR DESCRIPTION
**Pull request by TesaLazarenko**
Issue: https://github.com/OCA/web/issues/2836

### CODE REVIEW

**Comment by TesaLazarenko** [comment]
@amarcosg
@kikopeiro

**Review by kikopeiro — APPROVED** [review]
LGTM (without code review)

:+1:

**Comment by amarcosg** [comment]
Thank you so much @LazarusUA,refresh record just created works as expected and the general behaviour remains the same.

https://github.com/user-attachments/assets/ef97aea9-4034-4ff1-be57-341e5b1c6730

LGTM!

**Review by amarcosg — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please fw-port it to 17?

/ocabot merge patch

**Comment by TesaLazarenko** [comment]
> Can you please fw-port it to 17?
> 
> /ocabot merge patch

previously created [MR](https://github.com/OCA/web/pull/2890) is not suitable?

**Comment by pedrobaeza** [comment]
Sorry, didn't see it.

**Pull request merged**
