### PR TITLE
[10.0] web_environment_ribbon forward port

### PR DESCRIPTION
**Pull request by sbidoul**
Forward port of #621 with a couple of small improvements:
- make the backend model abstract as it does not need a db table
- make the backend model easier to extend with additional variables

### CODE REVIEW

**Comment by lfreeke** [comment]
:+1: (test)

**Review by elicoidal — APPROVED** [review]
:+1:

**Comment by moylop260** [comment]
The color changed for this version:
 - screen shot 2017-07-13 at 10 06 04

Shouldn't be same color like as old version?

 - screen shot 2017-07-13 at 10 06 58

**Comment by sbidoul** [comment]
@moylop260 on runbot, the system parameter has been changed: 
image

I assume another tester changed it manually, because this PR does not touch de default value.

**Comment by moylop260** [comment]
Thanks for clarify and migration!

**Pull request merged**
