### PR TITLE
[10.0][ADD][web_x2many_delete_all]

### PR DESCRIPTION
**Pull request by tarteo**
Adds a button to Many2many and One2many fields that removes all linked records.

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Comment by espo-tony** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Hi, thanks for this useful module!

One thing I have found is that the button is not hidden when the one2many field is readonly (directly or via attrs property). Can you check it?

Do you plan to backport this to v9?

**Comment by pedrobaeza** [comment]
Another interesting improvement is to add a tooltip to the trash button.

**Comment by pedrobaeza** [comment]
Sorry, I tried on the sales order view thinking that confirmed orders lock this, but it's not that way. It seems that the readonly flag is preserved.

Then it only rest the suggestion about the tooltip.

**Comment by tarteo** [comment]
@pedrobaeza Thanks for your feedback and test!

**Comment by tarteo** [comment]
@pedrobaeza made the tooltip! :)

**Review by lasley — APPROVED** [review]
Code + test 👍  - thanks @tarteo

**Comment by pedrobaeza** [comment]
Do you plan to backport it to v9?

**Comment by tarteo** [comment]
@pedrobaeza Yea sure, I can do that.

**Comment by pedrobaeza** [comment]
Thanks!

**Pull request merged**
