### PR TITLE
[12.0][IMP] web_responsive: mouseover menu

### PR DESCRIPTION
**Pull request by Tardo**
Don't shows menus when mouse over if are waiting for an action to end

Cc @tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot and working great.

**Review by chienandalu — APPROVED** [review]
Code looks good. I don't know what to test in runbot though. Some steps to reproduce?

**Comment by pedrobaeza** [comment]
@chienandalu: click on a menu that takes a bit to load. Move your cursor to other menus. Before: they got unfolded. Now: they are kept as is.

**Comment by chienandalu** [comment]
Ok, tested on runbot as well :+1:

**Pull request merged**
