### PR TITLE
[FIX] web_environment_ribbon : Fix menu_navbar overlap

### PR DESCRIPTION
**Pull request by hparfr**
Set correct z-index on ribbon
Move position accordingly

Cf #191

### CODE REVIEW

**Comment by tafaRU** [comment]
Now we have:

ribbon_1

Instead using the current PR we have:

ribbon_2

So :+1:

**Comment by pedrobaeza** [comment]
:+1: 

Please sign the CLA

**Comment by lmignon** [comment]
:+1:

**Comment by oscarolar** [comment]
:+1:

**Comment by bealdav** [comment]
:+1:

**Comment by pedrobaeza** [comment]
With the new PR merged (https://github.com/OCA/web/pull/230), I'm not sure if this is still good idea, because the word is going to be hidden. Please check it rebasing.

**Comment by hparfr** [comment]
It still a good idea.
With or without the change, the user can always enter a too long word.

**Comment by pedrobaeza** [comment]
Please rebase to see if the change if affordable or not, because I'm afraid the word is going to be hidden

**Comment by hparfr** [comment]
I increased the margin in the 8dda848.
And tested it on a rebased branch (with the condionnal ribbon). It's working well.

This PR doens't change the fact that if the text is too long it will be ugly.
But I think it's ok regarding the current purpose of this module.

**Comment by pedrobaeza** [comment]
Please push your rebase branch in order to see the final result.

**Comment by alexis-via** [comment]
:+1: great improvement !

**Comment by pedrobaeza** [comment]
Please don't merge until we can see the result of this PR with latest changes

**Comment by bealdav** [comment]
@pedrobaeza I don't know why we should wait for more time to merge ?
If you want to see the result of the PR, just git pull this branch. What is the problem ?

**Comment by pedrobaeza** [comment]
There's a change in upstream branch that is not included here, and it changes a bit the appearance of the ribbon and I'm worried that this change hides a lot of the text. That's why I ask for the rebase to see on runbot the result. Make all of this in local makes no sense and takes a lot of time having automated testing like runbot. Rebase is an operation that takes only 2 minutes.

**Comment by bealdav** [comment]
ok @hparfr, could you rebase ?

**Comment by hparfr** [comment]
I did the rebase as requested.

This branch is based on 4fb137a wich includes 0867977 (Merge pull request #230 from akretion/8.0-conditional-ribbon - Pedro M. Baeza ).

I don't see any new commits about the ribbon module in branch 8.0 since then.

It's working in runbot.

**Comment by pedrobaeza** [comment]
OK, I have seen that you have tried a long name. Thanks for your patience and efforts.

:+1: Merging.

**Pull request merged**
