### PR TITLE
web_tree_image:

### PR DESCRIPTION
**Pull request by kurniawanlucky**
* Change 16" to 32" because 16" is very small

### CODE REVIEW

**Comment by yajo** [comment]
Please explain how to test the patch :blush:

**Comment by StefanRijnhart** [comment]
I originally wrote this module to display __icons__ in the tree view, plus it fits the size of the standard Odoo row without an image, so the small size is on purpose. Then again, the size can be managed by the height attribute so I have no principle qualms with this change. I'll abstain from reviewing.

**Comment by pedrobaeza** [comment]
I agree with Stefan that it's not needed to change the default. Just put in your view definition the desired height.

:-1:

**Review by legalsylvain — CHANGES_REQUESTED** [review]
> so the small size is on purpose

agree with @StefanRijnhart. I think that default value should be the default Odoo value, so 16.

If you want to globally change this value (as your PR does), an acceptable improvment could be to add an extra settings default 16 to the ir.config.parameter, that could be changed.

In the xml file, something like

`t-att-height="widget.height || widget.default_tree_image_height"`

but it is a more complex PR.

**Pull request closed without merging**
