### PR TITLE
[15.0][MIG]web_decimal_numpad_dot

### PR DESCRIPTION
**Pull request by manuelregidor**
Standard migration

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Comment by pedrobaeza** [comment]
Afaik, this one is not needed anymore.

**Comment by ValentinVinagre** [comment]
> Afaik, this one is not needed anymore.

is base?

**Comment by pedrobaeza** [comment]
Yes, in core

**Comment by ValentinVinagre** [comment]
> Yes, in core

YEAH!!!! 🤞🏻

**Comment by HaraldPanten** [comment]
THX Pedro. Do you mind adding a small comment in the migration issue, please?

@manuelregidor not needed anymore. 👍

**Comment by pedrobaeza** [comment]
Done

**Comment by HekkiMelody** [comment]
There's a small functionality in this module that is still needed (tested in v16): when you're operating on a time field, you can still use the numpad dot to insert a colon `:` https://github.com/OCA/web/pull/2205/files#diff-bde1ba4bd88585dff5db6250875e22941db32bd07899f91c67d179a4b052c9b5R11-R14

Base still accepts a regular dot `.` but it will interpret it as a decimal number i.e. `5.50` becomes 5 hours and 30 minutes.

**Comment by HaraldPanten** [comment]
Not sure if that can be suggested in odoo/odoo as an improvement, in order to minimize external modules. WDYT?

**Pull request closed without merging**
